import { NextResponse } from "next/server";
import { reconstructRoof, summarize } from "@/lib/roof-geometry";
import { components, confidence, haversine, heatmapDataUrl, LAB_CONSTANTS, parseTiff, pctDiff, pricing, rgbDataUrl, SQFT_PER_M2 } from "@/lib/roof-measurement-lab";
export const runtime="nodejs";export const dynamic="force-dynamic";export const maxDuration=60;
const solar="https://solar.googleapis.com/v1";
async function json(url:string){const r=await fetch(url,{cache:"no-store"}),p=await r.json();if(!r.ok)throw new Error(`${r.status} ${r.statusText}: ${JSON.stringify(p)}`);return p}
async function asset(url:string,key:string){const id=new URL(url).searchParams.get("id");if(!id)throw new Error("Raster URL has no asset id");const r=await fetch(`${solar}/geoTiff:get?${new URLSearchParams({id,key})}`,{cache:"no-store"});if(!r.ok)throw new Error(`GeoTIFF ${r.status}: ${await r.text()}`);return Buffer.from(await r.arrayBuffer())}
export async function POST(req:Request){try{
  const key=process.env.GOOGLE_SECRET_KEY;if(!key)return NextResponse.json({error:"GOOGLE_SECRET_KEY is not configured"},{status:500});
  const body=await req.json(),address=String(body.address||"").trim();let latitude=Number(body.latitude),longitude=Number(body.longitude),formattedAddress=address;
  if(!Number.isFinite(latitude)||!Number.isFinite(longitude)){if(!address)return NextResponse.json({error:"Address or coordinates required"},{status:400});const g=await json(`https://maps.googleapis.com/maps/api/geocode/json?${new URLSearchParams({address,key})}`),r=g.results?.[0];if(!r)throw new Error(`Geocoding failed: ${g.status} ${g.error_message||""}`);latitude=r.geometry.location.lat;longitude=r.geometry.location.lng;formattedAddress=r.formatted_address}
  const common={"location.latitude":String(latitude),"location.longitude":String(longitude),requiredQuality:"BASE",exactQualityRequired:"false",key},biUrl=`${solar}/buildingInsights:findClosest?${new URLSearchParams(common)}`,dlUrl=`${solar}/dataLayers:get?${new URLSearchParams({...common,radiusMeters:"70",pixelSizeMeters:"0.1",view:"FULL_LAYERS"})}`;
  const[building,layers]=await Promise.all([json(biUrl),json(dlUrl)]);for(const name of["dsmUrl","maskUrl","rgbUrl"])if(!layers[name])throw new Error(`dataLayers did not return ${name}`);
  const[dsmBuffer,maskBuffer,rgbBuffer]=await Promise.all([asset(layers.dsmUrl,key),asset(layers.maskUrl,key),asset(layers.rgbUrl,key)]),dsm=parseTiff(dsmBuffer),mask=parseTiff(maskBuffer),rgb=parseTiff(rgbBuffer);
  if(dsm.width!==mask.width||dsm.height!==mask.height)throw new Error(`DSM/mask grid mismatch: DSM ${dsm.width}x${dsm.height}, mask ${mask.width}x${mask.height}`);
  const center=building.center,detected=components(mask,center),pixelArea=mask.pixelWidthM*mask.pixelHeightM,eligible=detected.filter(c=>c.pixels.length*pixelArea>=LAB_CONSTANTS.minimumPlaneAreaM2);if(!eligible.length)throw new Error("Mask contains no qualifying connected rooftop component");
  const models=eligible.map((component,index)=>{const model=reconstructRoof(dsm,component.pixels,index+1),summary=summarize(model.facets,model.edges);return{id:index+1,label:index===0?"Main Structure":`Accessory Structure #${index+1}`,isMain:index===0,maskPixels:component.pixels.length,groundAreaM2:component.pixels.length*pixelArea,distanceFromCenterPixels:component.distancePx,...model,...summary}}),main=models[0],allFacets=models.flatMap(x=>x.facets),allEdges=models.flatMap(x=>x.edges),combined=summarize(allFacets,allEdges);
  const sp=building.solarPotential||{},whole=sp.wholeRoofStats||{},stats=sp.buildingStats||{},segments=sp.roofSegmentStats||[],raw=Number(whole.areaMeters2),rawGround=Number(whole.groundAreaMeters2),buildingGround=Number(stats.groundAreaMeters2),coverage=rawGround/buildingGround,corrected=raw*buildingGround/rawGround,segmentArea=segments.reduce((s:number,x:any)=>s+Number(x.stats?.areaMeters2||0),0),segmentGround=segments.reduce((s:number,x:any)=>s+Number(x.stats?.groundAreaMeters2||0),0);
  const distance=haversine({latitude,longitude},center),areaDiff=pctDiff(main.surfaceAreaM2,corrected)??100,maskDiff=pctDiff(main.groundAreaM2,buildingGround)??100,conf=confidence({quality:building.imageryQuality||layers.imageryQuality||"BASE",distance,coverage,maskDiff,areaDiff,planeCoverage:main.assignedRoofPercent,residual:main.weightedRmsResidualM}),useDsm=conf.components.planeQuality>=13&&areaDiff<=5,includeAccessories=body.includeAccessories===true,recommendedMain=useDsm?main.surfaceAreaM2:corrected,recommended=includeAccessories?combined.surfaceAreaM2:recommendedMain,areaSource=includeAccessories?"DSM PLANE MODEL — ALL STRUCTURES":useDsm?"DSM PLANE MODEL":"CORRECTED GOOGLE FALLBACK",price=pricing(recommended*SQFT_PER_M2,includeAccessories?allFacets:main.facets);
  const safeModels=models.map(m=>({...m,facets:m.facets.map(f=>({...f,pixels:undefined})),edges:m.edges}));
  return NextResponse.json({notice:"Ephemeral, read-only laboratory response. No database client is imported or called.",constants:LAB_CONSTANTS,formattedAddress,coordinates:{geocoded:{latitude,longitude},buildingCenter:center,distanceMeters:distance,match:distance<=5?"STRONG":distance<=10?"WARNING":"LOW CONFIDENCE"},google:{buildingCenter:center,boundingBox:building.boundingBox,imageryDate:building.imageryDate,imageryProcessedDate:building.imageryProcessedDate,imageryQuality:building.imageryQuality,wholeRoofStats:whole,buildingStats:stats,roofSegmentStats:segments},layers:{imageryQuality:layers.imageryQuality,imageryDate:layers.imageryDate,imageryProcessedDate:layers.imageryProcessedDate,dsmUrl:layers.dsmUrl,rgbUrl:layers.rgbUrl,maskUrl:layers.maskUrl},raster:{dsm:dsm.diagnostic,mask:mask.diagnostic,rgb:rgb.diagnostic,rgbPreview:rgbDataUrl(rgb),dsmHeatmap:heatmapDataUrl(dsm),bounds:dsm.bounds,width:dsm.width,height:dsm.height,structures:safeModels},areas:{rawGoogleRoofAreaM2:raw,rawGoogleGroundAreaM2:rawGround,buildingGroundAreaM2:buildingGround,coverageRatio:coverage,correctionFactor:buildingGround/rawGround,correctedGoogleRoofAreaM2:corrected,segmentRoofAreaM2:segmentArea,segmentGroundAreaM2:segmentGround,rasterGroundAreaM2:main.groundAreaM2,rasterDerivedAreaM2:main.surfaceAreaM2,recommendedAreaM2:recommended,allStructuresAreaM2:combined.surfaceAreaM2,agreementPercent:areaDiff,areaSource},facets:main.facets.map(f=>({...f,pixels:undefined})),edges:main.edges,lengths:{...main.lengths,wallFlashing:null,stepFlashing:null,flashingStatus:"Not confidently detectable"},pitchDistribution:main.pitchDistribution,predominantPitch:main.predominantPitch,confidence:conf,planeQuality:{assignedRoofPercent:main.assignedRoofPercent,weightedRmsResidualM:main.weightedRmsResidualM},price,combined,raw:{buildingInsights:building,dataLayers:layers},endpoints:{geocoding:"https://maps.googleapis.com/maps/api/geocode/json",buildingInsights:biUrl.replace(key,"REDACTED"),dataLayers:dlUrl.replace(key,"REDACTED"),geoTiff:`${solar}/geoTiff:get?id=ASSET_ID&key=REDACTED`}}, {headers:{"Cache-Control":"no-store, no-cache, must-revalidate",Pragma:"no-cache"}})
}catch(e){return NextResponse.json({error:e instanceof Error?e.message:String(e),confidence:"LOW",priceReliable:false},{status:502,headers:{"Cache-Control":"no-store"}})}}
