"use client";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {defaultSwitches,type Override,type Switches} from "@/lib/mega-estimator/engine";
import {aggregateStructures,calculateOption,createOptions,defaultRates,emptyStructure,selectFieldProduct,type OptionKey,type OptionSettings,type Product,type RoofStructure,type WorksheetDefaults} from "@/lib/mega-estimator/worksheet";
import {MATERIAL_PRODUCTS} from "@/lib/mega-estimator/product-catalog";
import "./mega-estimator.css";
const money=(n:number)=>n.toLocaleString("en-CA",{style:"currency",currency:"CAD",minimumFractionDigits:2,maximumFractionDigits:2});
const qty=(n:number,digits=2)=>n.toLocaleString("en-CA",{minimumFractionDigits:0,maximumFractionDigits:digits});
const measurementFields=[['eaves','Eaves'],['rakes','Rakes'],['valleys','Valleys'],['ridgesHips','Hips / Ridges'],['transition','Transitions'],['goosenecks','Goosenecks'],['oatey','Oatey / Plumbing'],['bVents','B Vents'],['stepFlashing','Step Flashing'],['wallFlashing','Wall Flashing'],['chimneyBackpan','Chimney Backpan'],['layers','Layers'],['storeys','Storeys']] as const;
function DraftNumber({value,onCommit,label,step="0.01"}:{value:number;onCommit:(n:number)=>void;label:string;step?:string}){const[draft,setDraft]=useState(value?String(value):"");useEffect(()=>setDraft(value?String(value):""),[value]);return <label>{label}<input inputMode="decimal" step={step} placeholder="0" value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>onCommit(draft.trim()===""?0:Number(draft)||0)}/></label>}
export type MegaSnapshot={structures:RoofStructure[];options:Record<OptionKey,OptionSettings>;switches:Switches;defaultsSnapshot:WorksheetDefaults;customer:string;property:string;active:OptionKey;clauses:string[]};
export default function MegaEstimator({estimateId,initial,companyDefaults=defaultRates,productCatalog=MATERIAL_PRODUCTS}:{estimateId?:string;initial?:Partial<MegaSnapshot>;companyDefaults?:WorksheetDefaults;productCatalog?:Record<number,Product[]>}){
 const router=useRouter();const[customer,setCustomer]=useState(initial?.customer??""),[property,setProperty]=useState(initial?.property??""),[structures,setStructures]=useState<RoofStructure[]>(initial?.structures?.length?initial.structures:[emptyStructure()]),[options,setOptions]=useState(initial?.options??createOptions()),[active,setActive]=useState<OptionKey>(initial?.active??"good"),[switches,setSwitches]=useState(initial?.switches??defaultSwitches),[defaults,setDefaults]=useState(initial?.defaultsSnapshot??companyDefaults),[notice,setNotice]=useState("Blank estimate ready"),[proposal,setProposal]=useState(false),[clauses,setClauses]=useState(initial?.clauses??["Protect the property and landscaping before work begins.","Remove and dispose of the existing roofing system.","Install the selected complete roofing system.","Complete cleanup and final quality inspection."]);
 const calculations=useMemo(()=>Object.fromEntries((Object.keys(options) as OptionKey[]).map(key=>[key,calculateOption(structures,options[key],defaults,switches)])) as Record<OptionKey,ReturnType<typeof calculateOption>>,[structures,options,defaults,switches]);const current=calculations[active],setting=options[active];
 const setStructure=(id:string,fn:(s:RoofStructure)=>RoofStructure)=>setStructures(all=>all.map(s=>s.id===id?fn(s):s));
 const move=(index:number,direction:-1|1)=>setStructures(all=>{const to=index+direction;if(to<0||to>=all.length)return all;const next=[...all];[next[index],next[to]]=[next[to],next[index]];return next});
 const setOption=(key:OptionKey,fn:(o:OptionSettings)=>OptionSettings)=>setOptions(all=>({...all,[key]:fn(all[key])}));
 const save=async()=>{setNotice("Saving…");const snapshot={structures,options,switches,defaultsSnapshot:defaults,customer,property,active,clauses};const response=await fetch(estimateId?`/admin/estimates/api/mega/${estimateId}`:"/admin/estimates/api/mega",{method:estimateId?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({customer,property,finalPrice:current.finalPrice,snapshot})});const body=await response.json();if(!response.ok){setNotice(body.error||"Save failed.");return}setNotice("Estimate saved; measurements and overrides preserved.");if(!estimateId)router.push(`/admin/estimates/${body.id}`);router.refresh()};
 const saveDefaults=async()=>{const response=await fetch('/admin/estimates/api/defaults',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(defaults)});setNotice(response.ok?'Company defaults saved for future estimates.':'Company defaults could not be saved.')};
 return <main className="mega-sheet"><header><div><p className="eyebrow">Trusted Roofing · Estimating</p><h1>Roofing Estimate Worksheet</h1><p>Every calculation is automatic. Every calculated value is editable.</p></div><div className="actions"><button onClick={save}>Save Estimate</button><button onClick={()=>setDefaults(companyDefaults)}>Reset Rates to Default</button><button onClick={saveDefaults}>Save Rates as Company Default</button></div></header><div className="notice" role="status">{notice}</div>
 <section><h2>Customer / Property</h2><div className="form-grid"><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Customer name"/></label><label>Property<input value={property} onChange={e=>setProperty(e.target.value)} placeholder="Property address"/></label></div></section>
 <section><div className="estimate-heading"><div><h2>Structures / Buildings</h2><p>Each structure has independent pitch areas and measurements.</p></div><button onClick={()=>setStructures(s=>[...s,emptyStructure(`Structure ${s.length+1}`)])}>Add Structure</button></div>{structures.map((structure,index)=><article className="structure-card" key={structure.id}><div className="structure-toolbar"><label>Structure name<input value={structure.name} onChange={e=>setStructure(structure.id,s=>({...s,name:e.target.value}))}/></label><label>Status<select value={structure.status} onChange={e=>setStructure(structure.id,s=>({...s,status:e.target.value as RoofStructure['status']}))}><option value="included">Included</option><option value="optional">Optional Add-On</option><option value="excluded">Excluded</option></select></label><label className="check"><input type="checkbox" checked={structure.selected} onChange={e=>setStructure(structure.id,s=>({...s,selected:e.target.checked}))}/>Selected</label><div className="actions"><button disabled={!index} onClick={()=>move(index,-1)}>↑</button><button disabled={index===structures.length-1} onClick={()=>move(index,1)}>↓</button><button onClick={()=>setStructures(s=>[...s,{...structuredClone(structure),id:crypto.randomUUID(),name:`${structure.name} Copy`,pitches:structure.pitches.map(p=>({...p,id:crypto.randomUUID()}))}])}>Duplicate</button><button disabled={structures.length===1} onClick={()=>setStructures(s=>s.filter(x=>x.id!==structure.id))}>Delete</button></div></div><h3>Pitch Areas</h3><div className="pitch-list">{structure.pitches.map((pitch,pi)=><div className="pitch-row" key={pitch.id}><label>Pitch<select value={pitch.pitch} onChange={e=>setStructure(structure.id,s=>({...s,pitches:s.pitches.map((p,i)=>i===pi?{...p,pitch:Number(e.target.value)}:p)}))}>{Array.from({length:17},(_,i)=><option value={i+1} key={i}>{i===16?'XX/12':`${i+1}/12`}</option>)}</select></label><DraftNumber label="Area (sq ft)" value={pitch.areaSqFt} onCommit={areaSqFt=>setStructure(structure.id,s=>({...s,pitches:s.pitches.map((p,i)=>i===pi?{...p,areaSqFt}:p)}))}/><button disabled={structure.pitches.length===1} onClick={()=>setStructure(structure.id,s=>({...s,pitches:s.pitches.filter((_,i)=>i!==pi)}))}>Remove</button></div>)}</div><button onClick={()=>setStructure(structure.id,s=>({...s,pitches:[...s.pitches,{id:crypto.randomUUID(),pitch:4,areaSqFt:0}]}))}>Add Pitch</button><h3>Measurements</h3><div className="measure-grid">{measurementFields.map(([key,label])=><DraftNumber key={key} label={label} value={structure.measurements[key]} onCommit={value=>setStructure(structure.id,s=>({...s,measurements:{...s.measurements,[key]:value}}))}/>)}</div></article>)}<div className="area-summary">Total measured area <strong>{qty(aggregateStructures(structures).totalArea)} sq ft</strong></div></section>
 <section><h2>Option Comparison</h2><div className="option-comparison">{(Object.keys(options) as OptionKey[]).map(key=>{const result=calculations[key];return <button className={active===key?'active':''} key={key} onClick={()=>setActive(key)}><b>{options[key].label}</b><span>{options[key].products[12].name}</span><span>Cost {money(result.subtotalCost)}</span><span>Suggested {money(result.suggested)}</span><span>Final {money(result.finalPrice)}</span></button>})}</div></section>
 <section><h2>{setting.label} Pricing</h2><div className="pricing-controls"><DraftNumber label="Contingency % (markup on line cost)" value={setting.contingencyPercent} onCommit={v=>setOption(active,o=>({...o,contingencyPercent:v}))}/><DraftNumber label="Profit / Markup % (markup on subtotal cost)" value={setting.markupPercent} onCommit={v=>setOption(active,o=>({...o,markupPercent:v}))}/><DraftNumber label="Manual final selling price" value={setting.manualFinalPrice??0} onCommit={v=>setOption(active,o=>({...o,manualFinalPrice:v||null}))}/></div><div className="structure-selection"><b>Structures in this option:</b>{structures.filter(s=>s.status!=="excluded").map(s=><label className="check" key={s.id}><input type="checkbox" checked={setting.selectedStructureIds.length?setting.selectedStructureIds.includes(s.id):s.status==="included"&&s.selected} onChange={e=>setOption(active,o=>{const base=o.selectedStructureIds.length?o.selectedStructureIds:structures.filter(x=>x.status==="included"&&x.selected).map(x=>x.id);return{...o,selectedStructureIds:e.target.checked?[...new Set([...base,s.id])]:base.filter(id=>id!==s.id)}})}/>{s.name}</label>)}</div></section>
 <section><h2>Optional Workbook Switches</h2><div className="toggles">{Object.keys(switches).map(key=><label key={key}><input type="checkbox" checked={switches[key as keyof Switches]} onChange={e=>setSwitches(s=>({...s,[key]:e.target.checked}))}/>{key.replace(/([A-Z])/g,' $1')}</label>)}</div></section>
 {(['materials','labour','general_requirements'] as const).map(category=><section className="worksheet-table-section" key={category}><h2 className="sticky-section-title">{category==='general_requirements'?'General Requirements':category[0].toUpperCase()+category.slice(1)}</h2><div className="table-wrap"><table><thead><tr><th>Include</th><th>Item / Product</th><th>Quantity</th><th>Waste</th><th>Order Qty</th><th>Rate / Unit Cost</th><th>Total</th><th>Calculation Details</th></tr></thead><tbody>{current.rows.filter(r=>r.category===category).map(row=>{const products=(productCatalog[row.row]??[]).filter(product=>product.active);return <tr className={row.included?'':'inactive'} key={row.row}><td><input type="checkbox" checked={row.included} onChange={e=>setOption(active,o=>({...o,overrides:{...o.overrides,[row.row]:{...o.overrides[row.row],included:e.target.checked}}}))}/></td><td>{products.length?<select value={setting.products[row.row]?.name??products[0].name} onChange={e=>{const product=products.find(p=>p.name===e.target.value)!;setOption(active,o=>row.row===12?selectFieldProduct(o,product,productCatalog):({...o,products:{...o.products,[row.row]:structuredClone(product)}}))}}>{products.map(p=><option key={p.name}>{p.name}{p.quoteRequired?' — quote required':''}</option>)}</select>:row.item}</td><td>{qty(row.effectiveQuantity,row.priceUnit==='sq'?2:3)} {row.priceUnit}</td><td>{qty((row.multiplier-1)*100,2)}%</td><td>{qty(row.roundedOrderQuantity,3)}</td><td><label className="money-input"><span>$</span><input value={row.rate.toFixed(2)} onChange={e=>setOption(active,o=>({...o,overrides:{...o.overrides,[row.row]:{...o.overrides[row.row],rate:Number(e.target.value)||0}}}))}/><small>/ {row.priceUnit}</small></label></td><td>{money(row.extension)}</td><td><details><summary>Details</summary><dl><dt>Source</dt><dd>{qty(row.sourceQuantity,4)}</dd><dt>Required</dt><dd>{qty(row.requiredQuantity,4)}</dd><dt>Coverage</dt><dd>{qty(row.coverage,4)} {row.coverageUnit}</dd><dt>Raw order</dt><dd>{qty(row.rawOrderQuantity,4)}</dd><dt>Rounded</dt><dd>{qty(row.roundedOrderQuantity,4)}</dd><dt>Workbook row</dt><dd>B 1!{row.row}</dd><dt>Formula source</dt><dd>{row.source}</dd></dl></details></td></tr>})}</tbody></table></div></section>)}
 <section className="totals"><h2>{setting.label} Totals</h2><dl><div><dt>Measured Roof Area</dt><dd>{qty(current.measurements.totalArea)} sq ft</dd></div><div><dt>Purchased / Costed Squares</dt><dd>{qty(current.workbookSquares)} sq</dd></div><div><dt>Line Cost</dt><dd>{money(current.lineCost)}</dd></div><div><dt>Contingency ({qty(setting.contingencyPercent)}%)</dt><dd>{money(current.contingency)}</dd></div><div><dt>Subtotal Cost</dt><dd>{money(current.subtotalCost)}</dd></div><div><dt>Profit / Markup ({qty(setting.markupPercent)}%)</dt><dd>{money(current.markup)}</dd></div><div><dt>Suggested Selling Price</dt><dd>{money(current.suggested)}</dd></div><div><dt>Manual Final Selling Price</dt><dd>{setting.manualFinalPrice===null?'Not set':money(setting.manualFinalPrice)}</dd></div><div><dt>GST</dt><dd>{money(current.gst)}</dd></div><div className="grand"><dt>Customer Total</dt><dd>{money(current.customerTotal)}</dd></div></dl></section>
 <section><h2>Scope and Proposal</h2>{clauses.map((clause,i)=><div className="scope" key={i}><input type="checkbox" defaultChecked/><textarea value={clause} onChange={e=>setClauses(all=>all.map((x,j)=>j===i?e.target.value:x))}/></div>)}<button onClick={()=>setProposal(true)}>Generate Proposal</button>{proposal&&<article className="proposal-inline"><h3>{customer||'Customer'} · {setting.label}</h3><p>{property}</p><strong>{money(current.customerTotal)}</strong><ol>{clauses.map(x=><li key={x}>{x}</li>)}</ol><button onClick={()=>window.print()}>Download / Print</button></article>}</section>
 </main>
}
