"use client";
import {useEffect,useMemo,useState} from "react";
import {calculate,defaultSwitches,signalHill,type Measurements,type Override,type Switches} from "@/lib/mega-estimator/engine";
import "./mega-estimator.css";
const money=(n:number)=>n.toLocaleString("en-CA",{style:"currency",currency:"CAD"});
const number=(n:number)=>Number.isFinite(n)?n.toLocaleString("en-CA",{maximumFractionDigits:3}):"—";
const optionNames=["Good","Better","Best","Custom"];
function DraftNumber({value,onCommit,label}:{value:number;onCommit:(n:number)=>void;label:string}){const [draft,setDraft]=useState(String(value||""));useEffect(()=>setDraft(String(value||"")),[value]);return <label>{label}<input inputMode="decimal" placeholder="0" value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>onCommit(draft.trim()===""?0:Number(draft)||0)}/></label>}
export default function MegaEstimator(){
 const [measurements,setMeasurements]=useState<Measurements>(signalHill),[switches,setSwitches]=useState<Switches>(defaultSwitches),[option,setOption]=useState(0),[overrides,setOverrides]=useState<Record<number,Override>>({}),[defaults,setDefaults]=useState<Record<number,Override>>({}),[notice,setNotice]=useState("Signal Hill workbook fixture loaded"),[clauses,setClauses]=useState(["Protect the property and landscaping before work begins.","Remove and dispose of the existing roofing system.","Install the selected complete roofing system to manufacturer requirements.","Complete magnetic cleanup and final quality inspection."]);
 useEffect(()=>{const saved=localStorage.getItem("trusted-mega-estimate");const company=localStorage.getItem("trusted-mega-defaults");if(company)setDefaults(JSON.parse(company));if(saved){const d=JSON.parse(saved);setMeasurements(d.measurements);setSwitches(d.switches);setOverrides(d.overrides)}},[]);
 const rows=useMemo(()=>calculate(measurements,switches,overrides),[measurements,switches,overrides]); const subtotal=rows.reduce((a,r)=>a+r.extension,0),contingency=subtotal*.04,profit=(subtotal+contingency)*.3,total=subtotal+contingency+profit;
 const updateMeasurement=(key:keyof Measurements,n:number)=>setMeasurements(m=>({...m,[key]:n}));const update=(row:number,key:keyof Override,value:any)=>setOverrides(o=>({...o,[row]:{...o[row],[key]:value}}));
 const save=()=>{localStorage.setItem("trusted-mega-estimate",JSON.stringify({measurements,switches,overrides}));setNotice("Estimate snapshot saved — overrides preserved.")};
 return <main className="mega-sheet"><header><div><p className="eyebrow">Trusted Roofing · Internal estimating</p><h1>Roofing Estimate Worksheet</h1><p>Every calculation is automatic. Every calculated value is editable.</p></div><div className="actions"><button onClick={save}>Save estimate</button><button onClick={()=>{setOverrides(defaults);setNotice("Current company defaults restored.")}}>Reset to Default</button><button onClick={()=>{localStorage.setItem("trusted-mega-defaults",JSON.stringify(overrides));setDefaults(overrides);setNotice("Saved for future estimates; this estimate was not changed.")}}>Save as Company Default</button></div></header><div className="notice">{notice}</div>
 <section><h2>Customer / property</h2><div className="form-grid">{["Customer name","Phone","Email","Property address","City","Postal code"].map(x=><label key={x}>{x}<input placeholder={x}/></label>)}</div></section>
 <section><h2>Structures / buildings</h2><div className="form-grid"><label>Building label<input defaultValue="Main house"/></label><label>Included<select><option>Included in base</option><option>Optional</option><option>Excluded</option></select></label><DraftNumber label="Stories" value={1} onCommit={()=>{}}/></div></section>
 <section><h2>Pitch-area and roof measurements</h2><div className="measure-grid">{Array.from({length:17},(_,i)=>i+1).map(p=><DraftNumber key={p} label={p===17?"XX/12 custom":`${p}/12 area`} value={measurements.pitches[p]||0} onCommit={n=>setMeasurements(m=>({...m,pitches:{...m.pitches,[p]:n},totalArea:Object.values({...m.pitches,[p]:n}).reduce((a,b)=>a+b,0)}))}/>)}{([['ridgesHips','Ridges / hips'],['valleys','Valleys'],['rakes','Rakes'],['eaves','Eaves'],['transition','Transition'],['goosenecks','Goosenecks'],['oatey','Oatey'],['bVents','B vents'],['stepFlashing','Step flashing'],['wallFlashing','Wall flashing'],['chimneyBackpan','Chimney backpan']] as [keyof Measurements,string][]).map(([k,l])=><DraftNumber key={String(k)} label={l} value={measurements[k] as number} onCommit={n=>updateMeasurement(k,n)}/>)}</div><strong>Total roof area: {number(measurements.totalArea)} sq ft</strong></section>
 <section><h2>Options</h2><nav className="option-tabs">{optionNames.map((x,i)=><button className={option===i?"active":""} onClick={()=>setOption(i)} key={x}>{x}</button>)}</nav><p>{option===3?"Custom option cloned from Good; every product and rate remains editable.":`${optionNames[option]} workbook-mapped roofing selection.`}</p></section>
 <section><h2>Optional workbook switches</h2><div className="toggles">{Object.keys(switches).map(k=><label key={k}><input type="checkbox" checked={switches[k as keyof Switches]} onChange={e=>setSwitches(s=>({...s,[k]:e.target.checked}))}/>{k.replace(/([A-Z])/g," $1")}</label>)}</div></section>
 {(["materials","labour","general_requirements"] as const).map(cat=><section key={cat}><h2>{cat==="general_requirements"?"General Requirements / Add-ons":cat[0].toUpperCase()+cat.slice(1)}</h2><div className="table-wrap"><table><thead><tr><th>In</th><th>Item</th><th>Source quantity</th><th>Required</th><th>Waste / multiplier</th><th>Coverage</th><th>Raw order</th><th>Rounded order</th><th>Effective quantity</th><th>Unit cost / rate</th><th>Extension</th></tr></thead><tbody>{rows.filter(r=>r.category===cat).map(r=><tr className={r.included?"":"inactive"} key={r.row}><td><input aria-label={`Include ${r.item}`} type="checkbox" checked={r.included} onChange={e=>update(r.row,"included",e.target.checked)}/></td><td><input aria-label={`Item ${r.row}`} value={r.item} onChange={e=>update(r.row,"product",e.target.value)}/><small>Row {r.row} · {r.source}</small></td><td>{number(r.sourceQuantity)}</td><td>{number(r.requiredQuantity)}</td><td><input aria-label={`Multiplier ${r.row}`} value={r.multiplier} onChange={e=>update(r.row,"multiplier",Number(e.target.value)||0)}/></td><td><input aria-label={`Coverage ${r.row}`} value={r.coverage} onChange={e=>update(r.row,"coverage",Number(e.target.value)||0)}/></td><td>{number(r.rawOrderQuantity)}</td><td>{number(r.roundedOrderQuantity)}</td><td><input aria-label={`Quantity ${r.row}`} value={r.effectiveQuantity||""} placeholder="0" onChange={e=>update(r.row,"quantity",e.target.value===""?0:Number(e.target.value))}/></td><td><input aria-label={`Rate ${r.row}`} value={r.rate||""} placeholder="0" onChange={e=>update(r.row,"rate",e.target.value===""?0:Number(e.target.value))}/></td><td>{money(r.extension)}</td></tr>)}</tbody></table></div></section>)}
 <section className="totals"><h2>Totals and final selling price</h2><dl><div><dt>Line subtotal</dt><dd>{money(subtotal)}</dd></div><div><dt>Contingency (4%)</dt><dd>{money(contingency)}</dd></div><div><dt>Profit (30%)</dt><dd>{money(profit)}</dd></div><div className="grand"><dt>Final selling price</dt><dd>{money(total)}</dd></div></dl></section>
 <section><h2>Scope selections</h2>{clauses.map((c,i)=><div className="scope" key={i}><input type="checkbox" defaultChecked/><textarea value={c} onChange={e=>setClauses(a=>a.map((x,j)=>j===i?e.target.value:x))}/><button disabled={i===0} onClick={()=>setClauses(a=>{const n=[...a];[n[i-1],n[i]]=[n[i],n[i-1]];return n})}>Move up</button></div>)}</section>
 <section><h2>Generate proposal</h2><p>Create the polished customer proposal using the selected, ordered scope clauses and active option.</p><button onClick={()=>setNotice("Proposal draft generated from the selected scope.")}>Generate proposal</button></section>
 </main>;
}
