import type{PricingCatalogItem,PricingCatalogVersion,PricingRateItem}from"./types";
export type MaterialWarning={item:string;field:"coverage"|"price"|"quote_required"|"mapping";message:string;catalogVersion:string;sourceReference:string|null};
export type MaterialTrace={catalogVersionId:string;catalogVersionName:string;catalogItemId:string;itemName:string;supplier:string|null;unitPrice:number|null;currency:string;unit:string;coverage:number|null;coverageUnit:string|null;quoteRequired:boolean;sourceReference:string|null;requiredQuantity:number;wasteFactor:number;requiredAfterWaste:number;rawCalculatedUnits:number|null;orderQuantity:number|null;extension:number|null;productionReady:boolean;warnings:MaterialWarning[]};
export function orderIndivisibleUnits(required:number,coverage:number){if(required<=0)return 0;if(!Number.isFinite(coverage)||coverage<=0)throw new Error("Valid positive coverage is required.");return Math.max(1,Math.ceil(required/coverage))}
export function orderShingleBundles(squares:number,bundlesPerSquare:number,wasteFactor:number){if(squares<=0)return 0;if(!Number.isFinite(bundlesPerSquare)||bundlesPerSquare<=0)throw new Error("Valid bundles-per-square coverage is required.");return Math.max(1,Math.ceil(squares*bundlesPerSquare*(1+wasteFactor)))}
export function calculateMaterial(item:PricingCatalogItem,version:PricingCatalogVersion,required:number,wasteFactor=0):MaterialTrace{const adjusted=required*(1+wasteFactor),warnings:MaterialWarning[]=[];if(item.quote_required)warnings.push(warn(item,version,"quote_required","Supplier quote required."));if(item.price===null||!Number.isFinite(item.price))warnings.push(warn(item,version,"price","Missing unit price."));if(item.coverage===null||!Number.isFinite(item.coverage)||item.coverage<=0)warnings.push(warn(item,version,"coverage","Missing or invalid coverage."));const bundleCoverage=/bundles?\s*(per|\/)\s*square/i.test(item.coverage_unit??"");const raw=item.coverage&&item.coverage>0?(bundleCoverage?required*item.coverage*(1+wasteFactor):adjusted/item.coverage):null;const units=raw===null?null:Math.max(required>0?1:0,Math.ceil(raw));return{catalogVersionId:version.id,catalogVersionName:version.name,catalogItemId:item.id,itemName:item.name,supplier:item.supplier,unitPrice:item.price,currency:item.currency,unit:item.unit,coverage:item.coverage,coverageUnit:item.coverage_unit,quoteRequired:item.quote_required,sourceReference:item.source_reference,requiredQuantity:required,wasteFactor,requiredAfterWaste:adjusted,rawCalculatedUnits:raw,orderQuantity:units,extension:units!==null&&item.price!==null?units*item.price:null,productionReady:warnings.length===0,warnings}}
const warn=(i:PricingCatalogItem,v:PricingCatalogVersion,field:MaterialWarning["field"],message:string):MaterialWarning=>({item:i.name,field,message,catalogVersion:v.name,sourceReference:i.source_reference});
export type RateTrace={rateItemId:string;trade:string;rateType:string;name:string;rate:number;unit:string;sourceReference:string|null;appliedQuantity:number;extension:number};
export function calculateRate(item:PricingRateItem,quantity:number):RateTrace{return{rateItemId:item.id,trade:item.trade,rateType:item.rate_type,name:item.name,rate:item.rate,unit:item.unit,sourceReference:item.source_reference,appliedQuantity:quantity,extension:item.rate*quantity}}
export type PricingStrategy={type:"fixed_profit"|"cost_plus_percentage"|"target_margin"|"strategic_price";value:number};
export function applyPricingStrategy(cost:number,strategy:PricingStrategy){let sellingPrice=cost;if(strategy.type==="fixed_profit")sellingPrice=cost+strategy.value;if(strategy.type==="cost_plus_percentage")sellingPrice=cost*(1+strategy.value/100);if(strategy.type==="target_margin")sellingPrice=strategy.value>=100?cost:cost/(1-strategy.value/100);if(strategy.type==="strategic_price")sellingPrice=strategy.value;const profit=sellingPrice-cost;return{cost,sellingPrice,profit,grossMarginPercent:sellingPrice===0?0:profit/sellingPrice*100,loss:profit<0}}
