import{getServiceClient}from"@/lib/db";import type{CatalogStatus,PricingCatalogItem,PricingCatalogVersion,PricingColourOption,PricingRateItem}from"./types";
function db(){const client=getServiceClient();if(!client)throw new Error("Supabase service access is required for the pricing catalogue.");return client}
export async function listCatalogVersions(status?:CatalogStatus){let q=db().from("pricing_catalog_versions").select("*").order("effective_date",{ascending:false});if(status)q=q.eq("status",status);const{data,error}=await q;if(error)throw error;return(data??[])as PricingCatalogVersion[]}
export async function selectCatalogVersion(input:{versionId?:string;allowDraft?:boolean}={}){if(input.versionId){const{data,error}=await db().from("pricing_catalog_versions").select("*").eq("id",input.versionId).single();if(error)throw error;const version=data as PricingCatalogVersion;if(version.status!=="approved"&&!(input.allowDraft&&version.status==="draft"))throw new Error("Only approved catalogues are available for production; draft selection requires explicit admin test mode.");return version}const versions=await listCatalogVersions("approved");if(!versions.length)throw new Error("No approved pricing catalogue is available.");return versions[0]}
export async function listCatalogItems(input:{versionId:string;category?:string;subcategory?:string;name?:string;quoteRequired?:boolean;active?:boolean;missingPrice?:boolean}){let q=db().from("pricing_catalog_items").select("*").eq("catalog_version_id",input.versionId).order("category").order("subcategory").order("name");if(input.category)q=q.ilike("category",input.category);if(input.subcategory)q=q.ilike("subcategory",input.subcategory);if(input.name)q=q.ilike("name",`%${input.name}%`);if(input.quoteRequired!==undefined)q=q.eq("quote_required",input.quoteRequired);if(input.active!==undefined)q=q.eq("active",input.active);if(input.missingPrice)q=q.is("price",null);const{data,error}=await q;if(error)throw error;return(data??[]).map(normalizeItem)}
export async function findCatalogItemByExactName(versionId:string,name:string){const{data,error}=await db().from("pricing_catalog_items").select("*").eq("catalog_version_id",versionId).eq("active",true).ilike("name",name).limit(2);if(error)throw error;const rows=(data??[]).map(normalizeItem);if(rows.length!==1)throw new Error(`${name}: expected one active catalogue match, found ${rows.length}.`);return rows[0]}
export async function listRateItems(input:{versionId:string;trade?:string;rateType?:string;active?:boolean}){let q=db().from("pricing_rate_items").select("*").eq("catalog_version_id",input.versionId).order("trade").order("rate_type").order("name");if(input.trade)q=q.ilike("trade",input.trade);if(input.rateType)q=q.ilike("rate_type",input.rateType);if(input.active!==undefined)q=q.eq("active",input.active);const{data,error}=await q;if(error)throw error;return(data??[]).map(r=>({...r,rate:Number(r.rate)}))as PricingRateItem[]}
export async function listColourOptions(versionId:string,productName:string){const{data,error}=await db().from("pricing_colour_options").select("*").eq("catalog_version_id",versionId).eq("active",true).ilike("product_name",productName).order("colour_name");if(error)throw error;return(data??[])as PricingColourOption[]}
const normalizeItem=(r:any):PricingCatalogItem=>({...r,price:r.price===null?null:Number(r.price),coverage:r.coverage===null?null:Number(r.coverage)});
