create table if not exists proposals(id uuid primary key default gen_random_uuid(),proposal_number text not null unique,estimate_id uuid not null references estimates(id),revision_number integer not null default 1,status text not null default 'draft' check(status in('draft','archived')),customer_snapshot jsonb not null,property_snapshot jsonb not null,estimate_snapshot jsonb not null,roofing_options_snapshot jsonb not null,sections_snapshot jsonb not null default '[]',subtotal numeric not null default 0,gst numeric not null default 0,total numeric not null default 0,expiry_date date not null,proposal_date date not null default current_date,estimator_name text not null,cover_image_snapshot jsonb not null default '{"source":"none"}',cover_image_id uuid,requires_pricing_configuration boolean not null default false,created_by text not null,updated_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists proposal_sections(id uuid primary key default gen_random_uuid(),proposal_id uuid not null references proposals(id) on delete cascade,section_type text not null,title text not null,enabled boolean not null default true,display_order integer not null,content text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists proposal_images(id uuid primary key default gen_random_uuid(),proposal_id uuid not null references proposals(id) on delete cascade,estimate_id uuid not null references estimates(id),property_id uuid references estimate_properties(id),category text not null default 'cover',original_storage_path text,display_storage_path text,source text not null check(source in('street_view','upload')),attribution text,caption text,crop_data jsonb,zoom numeric not null default 1,position_data jsonb,rotation numeric not null default 0,width integer,height integer,display_order integer not null default 0,include_in_proposal boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists proposal_documents(id uuid primary key default gen_random_uuid(),proposal_id uuid not null references proposals(id) on delete cascade,revision_number integer not null,storage_path text not null,file_size integer,mime_type text not null default 'application/pdf',source_snapshot jsonb not null,created_by text not null,created_at timestamptz not null default now());
alter table proposals add constraint proposals_cover_image_fk foreign key(cover_image_id) references proposal_images(id) on delete set null;
create index if not exists proposals_estimate_idx on proposals(estimate_id);create index if not exists proposals_updated_idx on proposals(updated_at desc);create index if not exists proposal_sections_order_idx on proposal_sections(proposal_id,display_order);create index if not exists proposal_images_order_idx on proposal_images(proposal_id,display_order);create index if not exists proposal_documents_proposal_idx on proposal_documents(proposal_id,revision_number desc);
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('proposal-assets','proposal-assets',false,15728640,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
do $$ declare t text;begin foreach t in array array['proposals','proposal_sections','proposal_images','proposal_documents'] loop execute format('alter table %I enable row level security',t);execute format('create policy "internal proposals are service role only" on %I for all using(auth.role()=''service_role'') with check(auth.role()=''service_role'')',t);end loop;end$$;
create policy "proposal assets service role only" on storage.objects for all using(bucket_id='proposal-assets' and auth.role()='service_role') with check(bucket_id='proposal-assets' and auth.role()='service_role');
