alter table estimates drop constraint if exists estimates_scope_check;
alter table estimates add constraint estimates_scope_check check(scope in('roofing','soft_metals','combined'));
create table if not exists estimate_scopes(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,scope_type text not null check(scope_type in('eavestrough','downspouts','fascia','soffit')),enabled boolean not null default false,measurements jsonb not null default '{}',customer_summary jsonb not null default '{}',catalog_version_id uuid references pricing_catalog_versions(id) on delete restrict,production_ready boolean not null default false,warnings jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(estimate_id,scope_type));
create table if not exists estimate_scope_material_snapshots(id uuid primary key default gen_random_uuid(),estimate_scope_id uuid not null references estimate_scopes(id) on delete cascade,catalog_item_id uuid references pricing_catalog_items(id) on delete restrict,component_key text not null,snapshot jsonb not null,created_at timestamptz not null default now(),unique(estimate_scope_id,component_key));
create table if not exists estimate_scope_rate_snapshots(id uuid primary key default gen_random_uuid(),estimate_scope_id uuid not null references estimate_scopes(id) on delete cascade,rate_item_id uuid references pricing_rate_items(id) on delete restrict,rate_key text not null,snapshot jsonb not null,created_at timestamptz not null default now(),unique(estimate_scope_id,rate_key));
create table if not exists estimate_scope_results(id uuid primary key default gen_random_uuid(),estimate_scope_id uuid not null unique references estimate_scopes(id) on delete cascade,material_cost numeric not null default 0,labour_cost numeric not null default 0,disposal numeric not null default 0,delivery numeric not null default 0,overhead numeric not null default 0,total_cost numeric not null default 0,selling_price numeric not null default 0,profit numeric not null default 0,gross_margin_percent numeric not null default 0,pricing_strategy jsonb not null,calculated_at timestamptz not null default now());
create table if not exists estimate_scope_overrides(id uuid primary key default gen_random_uuid(),estimate_scope_id uuid not null references estimate_scopes(id) on delete cascade,field_name text not null,original_value numeric,new_value numeric not null,reason text not null check(length(trim(reason))>0),overridden_by text not null,created_at timestamptz not null default now());
create index if not exists estimate_scopes_estimate_idx on estimate_scopes(estimate_id);create index if not exists estimate_scope_overrides_scope_idx on estimate_scope_overrides(estimate_scope_id,created_at desc);
do $$declare t text;begin foreach t in array array['estimate_scopes','estimate_scope_material_snapshots','estimate_scope_rate_snapshots','estimate_scope_results','estimate_scope_overrides']loop execute format('alter table %I enable row level security',t);execute format('create policy "estimate scopes service role only" on %I for all using(auth.role()=''service_role'') with check(auth.role()=''service_role'')',t);end loop;end$$;
