-- Specification/tender mode reuses existing estimate scopes, pricing snapshots, proposals, documents and signing.
alter table estimates add column if not exists estimate_mode text not null default 'standard' check(estimate_mode in('standard','specification'));
create table if not exists estimate_tender_details(id uuid primary key default gen_random_uuid(),estimate_id uuid not null unique references estimates(id) on delete cascade,snapshot jsonb not null default '{}',updated_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(jsonb_typeof(snapshot)='object'));
create table if not exists tender_supporting_documents(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,proposal_id uuid references proposals(id) on delete set null,document_type text not null check(document_type in('specification','drawing_set','addendum','bid_form','insurance_scope','consultant_detail','product_requirement','supplier_quotation','supporting_image','other')),title text not null default '',original_filename text not null,mime_type text not null check(mime_type in('application/pdf','image/jpeg','image/png','image/webp')),file_size bigint not null check(file_size>0 and file_size<=26214400),storage_path text not null unique,include_in_proposal boolean not null default false,customer_label text not null default '',created_by text not null,created_at timestamptz not null default now());
create table if not exists specification_references(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,document_id uuid references tender_supporting_documents(id) on delete set null,reference_type text not null,label text not null,reference_data jsonb not null default '{}',display_order integer not null default 0,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists specification_compliance_items(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,category text not null default '',requirement text not null,status text check(status in('included','excluded','alternate','allowance','unit_rate','by_others','not_applicable','clarification_required','rfi_submitted','compliant','non_compliant','internal_only')),customer_response text not null default '',internal_note text not null default '',links jsonb not null default '{}',rfi jsonb not null default '{}',include_in_proposal boolean not null default true,display_order integer not null default 0,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists tender_alternates(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,snapshot jsonb not null,display_order integer not null default 0,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists tender_allowances(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,snapshot jsonb not null,display_order integer not null default 0,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists tender_unit_rates(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,rate_item_id uuid references pricing_rate_items(id) on delete restrict,snapshot jsonb not null,display_order integer not null default 0,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists tender_text_items(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,item_type text not null check(item_type in('exclusion','assumption','clarification')),snapshot jsonb not null,display_order integer not null default 0,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table proposals add column if not exists estimate_mode text not null default 'standard' check(estimate_mode in('standard','specification'));
alter table proposals add column if not exists specification_snapshot jsonb not null default '{}' check(jsonb_typeof(specification_snapshot)='object');
alter table proposal_acceptances add column if not exists tender_selection_snapshot jsonb not null default '{}' check(jsonb_typeof(tender_selection_snapshot)='object');
create index if not exists tender_documents_estimate_idx on tender_supporting_documents(estimate_id,created_at);create index if not exists specification_references_estimate_idx on specification_references(estimate_id,display_order);create index if not exists compliance_estimate_order_idx on specification_compliance_items(estimate_id,display_order);create index if not exists tender_alternates_estimate_idx on tender_alternates(estimate_id,display_order);create index if not exists tender_allowances_estimate_idx on tender_allowances(estimate_id,display_order);create index if not exists tender_unit_rates_estimate_idx on tender_unit_rates(estimate_id,display_order);create index if not exists tender_text_items_estimate_idx on tender_text_items(estimate_id,item_type,display_order);
do $$declare t text;begin foreach t in array array['estimate_tender_details','tender_supporting_documents','specification_references','specification_compliance_items','tender_alternates','tender_allowances','tender_unit_rates','tender_text_items']loop execute format('alter table %I enable row level security',t);execute format('create policy "tender records service role only" on %I for all using(auth.role()=''service_role'') with check(auth.role()=''service_role'')',t);end loop;end$$;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('tender-documents','tender-documents',false,26214400,array['application/pdf','image/jpeg','image/png','image/webp'])on conflict(id)do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "tender document objects service role only" on storage.objects for all using(bucket_id='tender-documents' and auth.role()='service_role') with check(bucket_id='tender-documents' and auth.role()='service_role');
