import { Facet, RoofEdge, summarize } from "./roof-geometry";
import { pctDiff, Raster } from "./roof-measurement-lab";

export const PRECISION_CONSTANTS = { internalCorridorMeters: 1.25, exteriorCorridorMeters: .75, highSupportScore: .70, mediumSupportScore: .50, maxTopologyCandidates: 50 } as const;
type Offset = { x: number; y: number };
type Context = { rgb: Raster; mask: Raster; dsm: Raster; cropOffset: Offset; facets: Facet[]; edges: RoofEdge[]; assignedRoofPercent: number; weightedRmsResidualM: number; preferredGoogleAreaM2: number; googleSegmentCount: number };

function now() { return performance.now() }
function clamp(value:number) { return Math.max(0, Math.min(1, value)) }
function localToWorld(context:Context, point:{x:number;y:number}) { return context.dsm.pixelToWorld(point.x/context.dsm.pixelWidthM+context.cropOffset.x, point.y/context.dsm.pixelHeightM+context.cropOffset.y) }
export function worldToRgbPixel(rgb:Raster, x:number, y:number) { return rgb.worldToPixel(x,y) }
export function rgbPixelToWorld(rgb:Raster, col:number, row:number) { return rgb.pixelToWorld(col,row) }

export function sobelRgb(rgb:Raster) {
  const size=rgb.width*rgb.height, gray=new Float32Array(size), edge=new Float32Array(size), bands=Math.min(3,rgb.bands);
  for(let i=0;i<size;i++){let value=0;for(let band=0;band<bands;band++)value+=Number(rgb.values[band]?.[i]||0)*(band===0?.299:band===1?.587:.114);gray[i]=value}
  let max=0;for(let y=1;y<rgb.height-1;y++)for(let x=1;x<rgb.width-1;x++){const i=y*rgb.width+x,gx=-gray[i-rgb.width-1]+gray[i-rgb.width+1]-2*gray[i-1]+2*gray[i+1]-gray[i+rgb.width-1]+gray[i+rgb.width+1],gy=-gray[i-rgb.width-1]-2*gray[i-rgb.width]-gray[i-rgb.width+1]+gray[i+rgb.width-1]+2*gray[i+rgb.width]+gray[i+rgb.width+1],m=Math.hypot(gx,gy);edge[i]=m;if(m>max)max=m}if(max)for(let i=0;i<size;i++)edge[i]/=max;return edge
}
function sampleLine(context:Context, edgeMap:Float32Array, points:{x:number;y:number}[]) {const [a,b]=points,length=Math.hypot(b.x-a.x,b.y-a.y),steps=Math.max(2,Math.ceil(length/.2));let strength=0,onMask=0,strong=0,valid=0;for(let i=0;i<=steps;i++){const t=i/steps,local={x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t},world=localToWorld(context,local),rp=context.rgb.worldToPixel(world.x,world.y),mp=context.mask.worldToPixel(world.x,world.y),rx=Math.round(rp.col),ry=Math.round(rp.row),mx=Math.round(mp.col),my=Math.round(mp.row);if(rx>=0&&ry>=0&&rx<context.rgb.width&&ry<context.rgb.height){const value=edgeMap[ry*context.rgb.width+rx];strength+=value;strong+=value>=.2?1:0;valid++}if(mx>=0&&my>=0&&mx<context.mask.width&&my<context.mask.height&&Number(context.mask.values[0][my*context.mask.width+mx])>0)onMask++}return{strength:strength/Math.max(valid,1),continuity:strong/Math.max(valid,1),mask:onMask/(steps+1)}}
function transformed(edge:RoofEdge, angleDegrees:number, offset:number){const a=edge.points[0],b=edge.points[edge.points.length-1],mx=(a.x+b.x)/2,my=(a.y+b.y)/2,angle=angleDegrees*Math.PI/180,c=Math.cos(angle),s=Math.sin(angle),dx=b.x-a.x,dy=b.y-a.y,length=Math.hypot(dx,dy)||1,nx=-dy/length,ny=dx/length,rotate=(p:{x:number;y:number;z:number})=>({x:mx+(p.x-mx)*c-(p.y-my)*s+nx*offset,y:my+(p.x-mx)*s+(p.y-my)*c+ny*offset,z:p.z});return[rotate(a),rotate(b)]}
function scoreInternal(orientation:number,proximity:number,strength:number,continuity:number,mask:number,length:number){return .30*orientation+.25*proximity+.20*strength+.10*continuity+.10*mask+.05*length}
function scoreExterior(strength:number,proximity:number,continuity:number,straightness:number,neighbor:number){return .35*strength+.25*proximity+.15*continuity+.15*straightness+.10*neighbor}
function refineEdge(context:Context,edgeMap:Float32Array,edge:RoofEdge){const exterior=!edge.facetB,corridor=exterior?PRECISION_CONSTANTS.exteriorCorridorMeters:PRECISION_CONSTANTS.internalCorridorMeters,angles=[-8,-4,0,4,8],step=.125;let best:any=null;for(const angle of angles)for(let offset=-corridor;offset<=corridor+.001;offset+=step){const candidate=transformed(edge,angle,offset),samples=sampleLine(context,edgeMap,candidate),orientation=clamp(1-Math.abs(angle)/15),proximity=clamp(1-Math.abs(offset)/corridor),score=exterior?scoreExterior(samples.strength,proximity,samples.continuity,orientation,1):scoreInternal(orientation,proximity,samples.strength,samples.continuity,samples.mask,1);if(!best||score>best.score)best={candidate,score,angle,offset,...samples}}const support=best.score>=PRECISION_CONSTANTS.highSupportScore?"RGB_SUPPORT_HIGH":best.score>=PRECISION_CONSTANTS.mediumSupportScore?"RGB_SUPPORT_MEDIUM":"RGB_SUPPORT_LOW",snapped=support==="RGB_SUPPORT_HIGH";return{edge:{...edge,points:snapped?best.candidate:edge.points,planLengthM:edge.planLengthM,lengthM:edge.lengthM,confidence:best.score},diagnostic:{edgeId:edge.id,type:edge.type,sourceFacets:[edge.facetA,edge.facetB].filter(Boolean),originalDsmCoordinates:edge.points,rgbCandidateCoordinates:best.candidate,snapDistanceMeters:snapped?Math.abs(best.offset):0,orientationDifferenceDegrees:Math.abs(best.angle),rgbScore:best.score,edgeStrength:best.strength,continuity:best.continuity,maskAgreement:best.mask,finalConfidence:support}}
}
function modelScore(context:Context,diagnostics:any[],variant:string){const dsm=clamp(context.assignedRoofPercent)*clamp(1-context.weightedRmsResidualM/.3),rgb=diagnostics.reduce((sum,item)=>sum+item.rgbScore,0)/Math.max(diagnostics.length,1),google=clamp(1-Math.abs(context.facets.length-context.googleSegmentCount)/Math.max(context.googleSegmentCount,1)),topology=clamp(1-diagnostics.filter(item=>item.finalConfidence==="RGB_SUPPORT_LOW").length/Math.max(diagnostics.length,1)),area=clamp(1-(pctDiff(context.facets.reduce((sum,facet)=>sum+facet.surfaceAreaM2,0),context.preferredGoogleAreaM2)||0)/10),architectural=diagnostics.reduce((sum,item)=>sum+clamp(1-item.orientationDifferenceDegrees/15),0)/Math.max(diagnostics.length,1),components={dsmPlaneFit:dsm,rgbLineAgreement:rgb,googleSegmentAgreement:google,topologyValidity:topology,areaConservation:area,architecturalRegularity:architectural},score=.30*dsm+.20*rgb+.15*google+.15*topology+.10*area+.10*architectural;return{name:variant,score,components}}
export function precisionAnalysis(context:Context){const started=now(),timings:Record<string,number>={},mark=(name:string,start:number)=>timings[name]=Math.round((now()-start)*100)/100;let at=now();const edgeMap=sobelRgb(context.rgb);mark("edgeMapGeneration",at);at=now();const refined=context.edges.map(edge=>refineEdge(context,edgeMap,edge));mark("candidateLineSearch",at);at=now();const snappedEdges=refined.map(item=>item.edge),diagnostics=refined.map(item=>item.diagnostic);mark("roofGraphGeneration",at);at=now();const candidates=[modelScore(context,diagnostics,"RGB_SNAPPED_DSM"),modelScore(context,diagnostics.map(item=>({...item,rgbScore:item.finalConfidence==="RGB_SUPPORT_HIGH"?item.rgbScore:item.rgbScore*.8})),"RGB_STRONG_ONLY"),modelScore(context,diagnostics.map(item=>({...item,rgbScore:item.rgbScore*.7})),"CURRENT_DSM_CONTROL")].slice(0,PRECISION_CONSTANTS.maxTopologyCandidates).sort((a,b)=>b.score-a.score);mark("candidateTopologyGeneration",at);at=now();const best=candidates[0],second=candidates[1],difference=best.score-second.score,confidence=best.score>=.90&&difference>=.08?"VERY HIGH":best.score>=.82&&difference>=.05?"HIGH":best.score>=.72?"MEDIUM":"LOW",summary=summarize(context.facets,snappedEdges),snapped=diagnostics.filter(item=>item.finalConfidence==="RGB_SUPPORT_HIGH"),dsmOnly=diagnostics.length-snapped.length;mark("topologyScoring",at);timings.totalPrecisionProcessing=Math.round((now()-started)*100)/100;return{mode:"PRECISION_RGB_DSM",...summary,facets:context.facets.map(facet=>({...facet,pixels:undefined})),edges:snappedEdges,lineDiagnostics:diagnostics,originalDsmLines:context.edges,topologyCandidates:candidates,bestScore:best.score,secondBestScore:second.score,scoreDifference:difference,confidence,rgbSupportedLineCount:snapped.length,dsmOnlyLineCount:dsmOnly,averageSnapDistanceMeters:snapped.reduce((sum,item)=>sum+item.snapDistanceMeters,0)/Math.max(snapped.length,1),maxSnapDistanceMeters:Math.max(0,...snapped.map(item=>item.snapDistanceMeters)),timings,rgbGeoReference:{width:context.rgb.width,height:context.rgb.height,transform:context.rgb.transform,bounds:context.rgb.bounds,pixelWidthM:context.rgb.pixelWidthM,pixelHeightM:context.rgb.pixelHeightM,crs:context.rgb.diagnostic.geoKeys}}}
