import { LAB_CONSTANTS, pctDiff, Raster, SQFT_PER_M2 } from "./roof-measurement-lab";
export type Point={x:number;y:number;z:number};export type Plane={a:number;b:number;c:number;rms:number;medianResidual:number;pixelCount:number};
export type Facet={id:string;structureId:number;pixels:number[];plane:Plane;groundAreaM2:number;surfaceAreaM2:number;triangulatedAreaM2:number;areaSqft:number;pitchDegrees:number;pitchX12:number;pitchBucket:number;azimuthDegrees:number;compass:string;centroid:{x:number;y:number};polygon:{x:number;y:number}[];fitStatus:string};
export type RoofEdge={id:string;type:"EAVE"|"RAKE"|"RIDGE"|"HIP"|"VALLEY"|"UNSPECIFIED";facetA:string;facetB:string|null;points:{x:number;y:number;z:number}[];planLengthM:number;lengthM:number;gradeDegrees:number;confidence:number};
const median=(a:number[])=>{const b=[...a].sort((x,y)=>x-y);return b.length?b[~~(b.length/2)]:NaN};
export function solve3(m:number[][],v:number[]){for(let i=0;i<3;i++){let p=i;for(let j=i+1;j<3;j++)if(Math.abs(m[j][i])>Math.abs(m[p][i]))p=j;[m[i],m[p]]=[m[p],m[i]];[v[i],v[p]]=[v[p],v[i]];const d=m[i][i];if(Math.abs(d)<1e-10)throw new Error("Degenerate plane points");for(let k=i;k<3;k++)m[i][k]/=d;v[i]/=d;for(let j=0;j<3;j++)if(j!==i){const q=m[j][i];for(let k=i;k<3;k++)m[j][k]-=q*m[i][k];v[j]-=q*v[i]}}return v}
function least(points:Point[]):Plane{let sx=0,sy=0,sz=0,sxx=0,syy=0,sxy=0,sxz=0,syz=0;for(const p of points){sx+=p.x;sy+=p.y;sz+=p.z;sxx+=p.x*p.x;syy+=p.y*p.y;sxy+=p.x*p.y;sxz+=p.x*p.z;syz+=p.y*p.z}const[a,b,c]=solve3([[sxx,sxy,sx],[sxy,syy,sy],[sx,sy,points.length]],[sxz,syz,sz]),res=points.map(p=>Math.abs(p.z-a*p.x-b*p.y-c));return{a,b,c,rms:Math.sqrt(res.reduce((s,x)=>s+x*x,0)/res.length),medianResidual:median(res),pixelCount:points.length}}
export function fitPlane(points:Point[]){if(points.length<3)throw new Error("Plane fit requires at least three points");let p=least(points);const residuals=points.map(x=>Math.abs(x.z-p.a*x.x-p.b*x.y-p.c)),mad=median(residuals),limit=Math.max(.05,mad*3),kept=points.filter((_,i)=>residuals[i]<=limit);if(kept.length>=3&&kept.length<points.length)p=least(kept);return p}
export function planeOrientation(p:Pick<Plane,"a"|"b">){const pitchDegrees=Math.atan(Math.hypot(p.a,p.b))*180/Math.PI,azimuthDegrees=(Math.atan2(-p.a,-p.b)*180/Math.PI+360)%360;return{pitchDegrees,pitchX12:12*Math.hypot(p.a,p.b),azimuthDegrees,compass:["N","NE","E","SE","S","SW","W","NW"][Math.round(azimuthDegrees/45)%8]}}
export const polygonArea=(p:{x:number;y:number}[])=>Math.abs(p.reduce((s,a,i)=>{const b=p[(i+1)%p.length];return s+a.x*b.y-b.x*a.y},0))/2;
export const planeSurfaceArea=(ground:number,p:Pick<Plane,"a"|"b">)=>ground*Math.sqrt(1+p.a*p.a+p.b*p.b);
export const edgeLength=(p:{x:number;y:number;z:number}[])=>p.slice(1).reduce((s,b,i)=>s+Math.hypot(b.x-p[i].x,b.y-p[i].y,b.z-p[i].z),0);
export function classifyExterior(edgeAngle:number,downslopeAzimuth:number){const d=Math.abs((((edgeAngle-downslopeAzimuth)%180)+180)%180),acute=Math.min(d,180-d),t=LAB_CONSTANTS.edgeClassificationAngularToleranceDegrees;return acute<=t?"RAKE":Math.abs(acute-90)<=t?"EAVE":"UNSPECIFIED"}
export function classifyInternal(convex:boolean,verticalChange:number,planLength:number){if(!convex)return"VALLEY";const grade=Math.atan2(Math.abs(verticalChange),planLength)*180/Math.PI;return Math.abs(verticalChange)<=LAB_CONSTANTS.ridgeVerticalToleranceMeters||grade<=LAB_CONSTANTS.ridgeGradeToleranceDegrees?"RIDGE":"HIP"}
export function intersectionConvex(a:Pick<Plane,"a"|"b">,b:Pick<Plane,"a"|"b">,fromAToB:{x:number;y:number}){const da=a.a*fromAToB.x+a.b*fromAToB.y,db=b.a*fromAToB.x+b.b*fromAToB.y;return da>db}
function smooth(values:number[],valid:Set<number>,w:number,h:number,r:number){const out=[...values];for(const i of valid){const x=i%w,y=~~(i/w),near=[];for(let yy=Math.max(0,y-r);yy<=Math.min(h-1,y+r);yy++)for(let xx=Math.max(0,x-r);xx<=Math.min(w-1,x+r);xx++){const j=yy*w+xx;if(valid.has(j)&&Number.isFinite(values[j])&&Math.abs(values[j]-values[i])<=LAB_CONSTANTS.spikeThresholdMeters)near.push(values[j])}if(near.length>=5)out[i]=median(near)}return out}
function trace(pixels:Set<number>,w:number,dx:number,dy:number){type S={a:{x:number;y:number};b:{x:number;y:number}};const seg:S[]=[];for(const i of pixels){const x=i%w,y=~~(i/w);if(!pixels.has(i-w))seg.push({a:{x:x*dx,y:y*dy},b:{x:(x+1)*dx,y:y*dy}});if(!pixels.has(i+1)||x===w-1)seg.push({a:{x:(x+1)*dx,y:y*dy},b:{x:(x+1)*dx,y:(y+1)*dy}});if(!pixels.has(i+w))seg.push({a:{x:(x+1)*dx,y:(y+1)*dy},b:{x:x*dx,y:(y+1)*dy}});if(!pixels.has(i-1)||x===0)seg.push({a:{x:x*dx,y:(y+1)*dy},b:{x:x*dx,y:y*dy}})}if(!seg.length)return[];const poly=[seg[0].a,seg[0].b];seg.splice(0,1);while(seg.length){const end=poly[poly.length-1],j=seg.findIndex(s=>Math.hypot(s.a.x-end.x,s.a.y-end.y)<1e-7);if(j<0)break;poly.push(seg[j].b);seg.splice(j,1)}return poly.filter((p,i,a)=>{if(i===0||i===a.length-1)return true;const x=a[i-1],z=a[i+1];return Math.abs((p.x-x.x)*(z.y-p.y)-(p.y-x.y)*(z.x-p.x))>.0001})}
export function reconstructRoof(dsm:Raster,componentPixels:number[],structureId=1){if(dsm.bands<1)throw new Error("DSM raster has no band");const valid=new Set(componentPixels.filter(i=>Number.isFinite(dsm.values[0][i])&&dsm.values[0][i]!==dsm.noData&&dsm.values[0][i]>-9000)),radius=Math.max(1,Math.round(LAB_CONSTANTS.dsmMedianWindowMeters/Math.max(dsm.pixelWidthM,dsm.pixelHeightM)/2)),z=smooth(dsm.values[0],valid,dsm.width,dsm.height,radius),normal=new Map<number,{a:number;b:number;pitch:number;az:number}>();
  for(const i of valid){const x=i%dsm.width,y=~~(i/dsm.width),r=Math.max(1,radius),l=i-r,rr=i+r,u=i-r*dsm.width,d=i+r*dsm.width;if(x>=r&&x+r<dsm.width&&y>=r&&y+r<dsm.height&&[l,rr,u,d].every(q=>valid.has(q))){const a=(z[rr]-z[l])/(2*r*dsm.pixelWidthM),b=(z[u]-z[d])/(2*r*dsm.pixelHeightM),o=planeOrientation({a,b});if(o.pitchDegrees<75)normal.set(i,{a,b,pitch:o.pitchDegrees,az:o.azimuthDegrees})}}
  const labels=new Int32Array(dsm.width*dsm.height).fill(-1),clusters:number[][]=[];for(const start of normal.keys()){if(labels[start]>=0)continue;const seed=normal.get(start)!,id=clusters.length,q=[start],px:number[]=[];labels[start]=id;for(let h=0;h<q.length;h++){const i=q[h],x=i%dsm.width;px.push(i);for(const n of[i-1,i+1,i-dsm.width,i+dsm.width]){const o=normal.get(n);if(o&&labels[n]<0&&Math.abs(n%dsm.width-x)<=1&&Math.abs(o.pitch-seed.pitch)<=LAB_CONSTANTS.pitchToleranceDegrees&&angleDiff(o.az,seed.az)<=LAB_CONSTANTS.azimuthToleranceDegrees){labels[n]=id;q.push(n)}}}clusters.push(px)}
  const facets:Facet[]=[];for(const px of clusters){if(px.length*dsm.pixelWidthM*dsm.pixelHeightM<LAB_CONSTANTS.minimumPlaneAreaM2)continue;const points=px.map(i=>({x:(i%dsm.width+.5)*dsm.pixelWidthM,y:(~~(i/dsm.width)+.5)*dsm.pixelHeightM,z:z[i]}));let plane:Plane;try{plane=fitPlane(points)}catch{continue}const o=planeOrientation(plane),set=new Set(px),polygon=trace(set,dsm.width,dsm.pixelWidthM,dsm.pixelHeightM),ground=px.length*dsm.pixelWidthM*dsm.pixelHeightM,surface=planeSurfaceArea(ground,plane);facets.push({id:`F${facets.length+1}`,structureId,pixels:px,plane,groundAreaM2:ground,surfaceAreaM2:surface,triangulatedAreaM2:triangulated(px,set,z,dsm),areaSqft:surface*SQFT_PER_M2,pitchDegrees:o.pitchDegrees,pitchX12:o.pitchX12,pitchBucket:Math.round(o.pitchX12),azimuthDegrees:o.azimuthDegrees,compass:o.compass,centroid:{x:points.reduce((s,p)=>s+p.x,0)/points.length,y:points.reduce((s,p)=>s+p.y,0)/points.length},polygon,fitStatus:plane.rms<=.25?"ACCEPTED":"POOR_FIT"})}
  const accepted=facets.filter(f=>f.fitStatus==="ACCEPTED"),label=new Int32Array(dsm.width*dsm.height).fill(-1);accepted.forEach((f,k)=>f.pixels.forEach(i=>label[i]=k));const edges=deriveEdges(accepted,label,z,dsm),assigned=accepted.reduce((s,f)=>s+f.pixels.length,0),rms=Math.sqrt(accepted.reduce((s,f)=>s+f.plane.rms*f.plane.rms*f.pixels.length,0)/Math.max(assigned,1));return{facets:accepted,edges,assignedRoofPercent:assigned/Math.max(valid.size,1),weightedRmsResidualM:rms,validPixels:valid.size}}
function angleDiff(a:number,b:number){const d=Math.abs(a-b)%360;return Math.min(d,360-d)}
function triangulated(px:number[],set:Set<number>,z:number[],r:Raster){let a=0;for(const i of px)if(set.has(i+1)&&set.has(i+r.width)&&set.has(i+r.width+1)){const dx=r.pixelWidthM,dy=r.pixelHeightM;a+=.5*Math.hypot(dx*dy,dy*(z[i+1]-z[i]),dx*(z[i+r.width]-z[i]))+.5*Math.hypot(dx*dy,dy*(z[i+r.width]-z[i+r.width+1]),dx*(z[i+1]-z[i+r.width+1]))}return a}
function deriveEdges(f:Facet[],label:Int32Array,z:number[],r:Raster){const out:RoofEdge[]=[];for(let y=0;y<r.height;y++)for(let x=0;x<r.width;x++){const i=y*r.width+x,a=label[i];if(a<0)continue;for(const [n,x1,y1,x2,y2] of [[i+1,(x+1)*r.pixelWidthM,y*r.pixelHeightM,(x+1)*r.pixelWidthM,(y+1)*r.pixelHeightM],[i+r.width,x*r.pixelWidthM,(y+1)*r.pixelHeightM,(x+1)*r.pixelWidthM,(y+1)*r.pixelHeightM]] as number[][]){const b=n<label.length?label[n]:-1;if(b===a)continue;const p1={x:x1,y:y1,z:f[a].plane.a*x1+f[a].plane.b*y1+f[a].plane.c},p2={x:x2,y:y2,z:f[a].plane.a*x2+f[a].plane.b*y2+f[a].plane.c},plan=Math.hypot(x2-x1,y2-y1),angle=(Math.atan2(x2-x1,-(y2-y1))*180/Math.PI+360)%360;let type:RoofEdge["type"];if(b>=0&&a<b){const dir={x:f[b].centroid.x-f[a].centroid.x,y:f[b].centroid.y-f[a].centroid.y};type=classifyInternal(intersectionConvex(f[a].plane,f[b].plane,dir),p2.z-p1.z,plan) as RoofEdge["type"]}else if(b<0)type=classifyExterior(angle,f[a].azimuthDegrees) as RoofEdge["type"];else continue;out.push({id:`E${out.length+1}`,type,facetA:f[a].id,facetB:b>=0?f[b].id:null,points:[p1,p2],planLengthM:plan,lengthM:edgeLength([p1,p2]),gradeDegrees:Math.atan2(Math.abs(p2.z-p1.z),plan)*180/Math.PI,confidence:type==="UNSPECIFIED"?.4:.8})}}return out}
export function mergeCompatibleFacets(a:Facet,b:Facet,heightDifference:number){return Math.abs(a.pitchDegrees-b.pitchDegrees)<=LAB_CONSTANTS.planeMergePitchDegrees&&angleDiff(a.azimuthDegrees,b.azimuthDegrees)<=LAB_CONSTANTS.planeMergeAzimuthDegrees&&Math.abs(heightDifference)<=LAB_CONSTANTS.planeMergeHeightMeters}
export function summarize(facets:Facet[],edges:RoofEdge[]){const surfaceAreaM2=facets.reduce((s,f)=>s+f.surfaceAreaM2,0),pitchDistribution=Object.values(facets.reduce((o:Record<string,{pitch:string;areaSqft:number}>,f)=>{const k=`${f.pitchBucket}/12`;o[k]??={pitch:k,areaSqft:0};o[k].areaSqft+=f.areaSqft;return o},{})),lengths={eave:0,rake:0,ridge:0,hip:0,valley:0,unspecified:0,wallFlashing:null,stepFlashing:null};for(const e of edges)(lengths[e.type.toLowerCase() as keyof typeof lengths] as number)+=e.lengthM;return{surfaceAreaM2,areaSqft:surfaceAreaM2*SQFT_PER_M2,facetCount:facets.length,pitchDistribution,predominantPitch:[...pitchDistribution].sort((a,b)=>b.areaSqft-a.areaSqft)[0]?.pitch||null,weightedPitchX12:facets.reduce((s,f)=>s+f.pitchX12*f.areaSqft,0)/Math.max(surfaceAreaM2*SQFT_PER_M2,1),lengths}}
