import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
const read=(path:string)=>fs.readFileSync(path,"utf8");
test("admin landing and rejected list routes lead to estimates",()=>{assert.match(read("app/admin/page.tsx"),/redirect\("\/admin\/estimates"\)/);assert.match(read("app/admin/jobs/page.tsx"),/permanentRedirect\("\/admin\/estimates"\)/);assert.match(read("app/admin/proposals/page.tsx"),/redirect\("\/admin\/estimates"\)/)});
test("primary navigation contains only estimator administration",()=>{const nav=read("app/admin/_components/AdminTabs.tsx");for(const label of["Estimates","Customers","Pricing Defaults","Settings"])assert.match(nav,new RegExp(`label: "${label}"`));for(const rejected of["Dashboard","Jobs","Proposals","System Status","Projects","Tender","Change Orders","More"])assert.doesNotMatch(nav,new RegExp(rejected))});
test("estimate list has required columns and direct actions",()=>{const page=read("app/admin/estimates/page.tsx");for(const text of["Roofing Estimates","New Estimate","Search estimates","Customer","Property","Status","Last modified","Final price","Open estimate"])assert.match(page,new RegExp(text));assert.doesNotMatch(page,/listJobs|admin\/jobs/)});
test("new estimator starts blank and saved estimator loads a snapshot",()=>{assert.match(read("app/admin/estimates/MegaEstimator.tsx"),/\[emptyStructure\(\)\]/);assert.match(read("app/admin/estimates/\[id\]/page.tsx"),/getMegaEstimate/);assert.match(read("app/admin/estimates/MegaEstimator.tsx"),/api\/mega/)});
test("admin shell suppresses marketing chrome",()=>{const css=read("app/admin/admin-app.css");assert.match(css,/\.site-header/);assert.match(css,/\.site-footer/)});
test("Mega estimate migration stores independent worksheet snapshots",()=>{const migration=read("supabase/migrations/0030_mega_estimates.sql");assert.match(migration,/create table if not exists mega_estimates/);assert.match(migration,/snapshot jsonb/)});
test("new estimate remains available before company-default migration is applied",()=>{const repository=read("lib/mega-estimator/repository.ts");assert.match(repository,/if\(error\)return fallback\(\)/);assert.match(repository,/catch\{return fallback\(\)\}/)});
