import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
const read=(path:string)=>fs.readFileSync(path,"utf8");
test("admin landing restores the GeoBoost dashboard while retired list routes lead to estimates",()=>{const dashboard=read("app/admin/page.tsx");for(const text of["GeoBoost Admin","Published geo-posts","Projects missing geo-posts","Instant quote leads","Project \\+ geo-post status"])assert.match(dashboard,new RegExp(text));assert.doesNotMatch(dashboard,/redirect\("\/admin\/estimates"\)/);assert.match(read("app/admin/jobs/page.tsx"),/permanentRedirect\("\/admin\/estimates"\)/);assert.match(read("app/admin/proposals/page.tsx"),/redirect\("\/admin\/estimates"\)/)});
test("primary navigation exposes both the dashboard and estimator administration",()=>{const nav=read("app/admin/_components/AdminTabs.tsx");for(const label of["Dashboard","Estimates","Customers","Pricing Defaults","Settings"])assert.match(nav,new RegExp(`label: "${label}"`));for(const rejected of["Jobs","Proposals","System Status","Projects","Tender","Change Orders","More"])assert.doesNotMatch(nav,new RegExp(rejected));assert.match(nav,/item\.href === "\/admin"/)});
test("admin brand returns to the dashboard",()=>{assert.match(read("app/admin/layout.tsx"),/<Link href="\/admin" className="admin-app__brand">/)});
test("estimate list has required columns and direct actions",()=>{const page=read("app/admin/estimates/page.tsx");for(const text of["Roofing Estimates","New Estimate","Search estimates","Customer","Property","Status","Last modified","Final price","Open estimate"])assert.match(page,new RegExp(text));assert.doesNotMatch(page,/listJobs|admin\/jobs/)});
test("new estimator starts blank and saved estimator loads a snapshot",()=>{assert.match(read("app/admin/estimates/MegaEstimator.tsx"),/\[emptyStructure\(\)\]/);assert.match(read("app/admin/estimates/\[id\]/page.tsx"),/getMegaEstimate/);assert.match(read("app/admin/estimates/MegaEstimator.tsx"),/api\/mega/)});
test("admin shell suppresses marketing chrome",()=>{const css=read("app/admin/admin-app.css");assert.match(css,/\.site-header/);assert.match(css,/\.site-footer/)});
test("Mega estimate migration stores independent worksheet snapshots",()=>{const migration=read("supabase/migrations/0030_mega_estimates.sql");assert.match(migration,/create table if not exists mega_estimates/);assert.match(migration,/snapshot jsonb/)});
test("new estimate remains available before company-default migration is applied",()=>{const repository=read("lib/mega-estimator/repository.ts");assert.match(repository,/if\(error\)return fallback\(\)/);assert.match(repository,/catch\{return fallback\(\)\}/)});

test("only table columns stick below admin header",()=>{const css=read("app/admin/estimates/mega-estimator.css");assert.match(css,/sticky-section-title\{position:static/);assert.match(css,/thead th\{position:sticky;top:58px/);assert.doesNotMatch(css,/table-wrap\{overflow-x:auto/) });
