import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";import{checkEnvironment,environmentBlockers}from"../lib/readiness/environment";import{evaluateProductionReadiness,type CliSnapshot}from"../lib/readiness/cli";import{findMissingMigrations,MIGRATION_REGISTRY,migrationChecksumMismatch,validateMigrationOrder}from"../lib/readiness/migration-registry";import{correlationId,redact,structuredLog}from"../lib/readiness/logging";import{temporaryStorageRoundTrip}from"../lib/readiness/storage-test";
const env={NEXT_PUBLIC_SUPABASE_URL:"https://abc.supabase.co",NEXT_PUBLIC_SUPABASE_ANON_KEY:"anon",SUPABASE_SERVICE_ROLE_KEY:"service",ADMIN_TOKEN:"admin",NEXT_PUBLIC_SITE_URL:"https://example.test",NEXT_PUBLIC_PROPOSAL_BASE_URL:"https://example.test",RESEND_API_KEY:"resend",RESEND_FROM_EMAIL:"Trusted <test@example.test>"}as Record<string,string|undefined>;const snapshot=():CliSnapshot=>({tables:[...new Set(MIGRATION_REGISTRY.flatMap(x=>x.tables))],functions:[...new Set(MIGRATION_REGISTRY.flatMap(x=>x.functions))],buckets:[...new Set(MIGRATION_REGISTRY.flatMap(x=>x.buckets))].map(id=>({id,public:false})),indexes:[...new Set(MIGRATION_REGISTRY.flatMap(x=>x.indexes??[]))],columns:Object.fromEntries([...new Set(MIGRATION_REGISTRY.flatMap(x=>Object.keys(x.columns)))].map(t=>[t,[...new Set(MIGRATION_REGISTRY.flatMap(x=>x.columns[t]??[]))]]))});
test("registry contains every repository migration in valid dependency order",()=>{assert.deepEqual(validateMigrationOrder(),[]);for(const x of MIGRATION_REGISTRY){assert.ok(x.number&&x.name&&x.file&&x.checksum);assert.ok(fs.existsSync(`supabase/migrations/${x.file}`),x.file)}});
test("checksum mismatch produces a warning condition",()=>{assert.equal(migrationChecksumMismatch("expected","different"),true);assert.equal(migrationChecksumMismatch("same","same"),false)});
test("missing migration and wrong order are identified",()=>{assert.equal(findMissingMigrations(MIGRATION_REGISTRY.slice(1).map(x=>x.number))[0].number,MIGRATION_REGISTRY[0].number);assert.match(validateMigrationOrder([MIGRATION_REGISTRY.find(x=>x.number==="0027")!,MIGRATION_REGISTRY.find(x=>x.number==="0026")!]).join(" "),/requires 0026/)});
test("missing tables columns functions and public buckets are blockers",()=>{const s=snapshot();s.tables=s.tables.filter(x=>x!=="projects");s.columns.estimates=s.columns.estimates.filter(x=>x!=="workflow_status");s.functions=s.functions.filter(x=>x!=="approve_change_order");s.buckets=s.buckets.map(x=>x.id==="project-documents"?{...x,public:true}:x);const r=evaluateProductionReadiness(env,s);assert.ok(r.blockers.some(x=>x.includes("missing table projects")));assert.ok(r.blockers.some(x=>x.includes("estimates.workflow_status")));assert.ok(r.blockers.some(x=>x.includes("approve_change_order")));assert.ok(r.blockers.some(x=>x.includes("project-documents is public")))});
test("valid production environment and schema are ready",()=>assert.deepEqual(evaluateProductionReadiness(env,snapshot()).blockers,[]));
test("environment detects missing malformed and mismatched configuration",()=>{assert.ok(environmentBlockers(checkEnvironment({})).length>0);assert.equal(checkEnvironment({...env,NEXT_PUBLIC_SITE_URL:"not-url"}).find(x=>x.name==="NEXT_PUBLIC_SITE_URL")?.status,"malformed");assert.equal(checkEnvironment({...env,SUPABASE_URL:"https://other.supabase.co"}).find(x=>x.name==="SUPABASE_PROJECT_REFERENCE")?.status,"inconsistent")});
test("structured logs redact secrets tokens signatures and customer data",()=>{const safe:any=redact({token:"raw-token",authorization:"Bearer abc",signatureData:"drawn",customerEmail:"person@example.test",message:"Bearer verysecretvalue12345678901234567890"});assert.equal(safe.token,"[REDACTED]");assert.equal(safe.signatureData,"[REDACTED]");assert.equal(safe.customerEmail,"[REDACTED]");assert.doesNotMatch(JSON.stringify(safe),/verysecret|raw-token|person@example/);const old=console.info;console.info=()=>{};const event:any=structuredLog("info",{operation:"test",route:"/admin/system-status",feature:"readiness",recoverable:true,correlationId:correlationId("invalid")});console.info=old;assert.match(event.correlationId,/^[a-f0-9-]{36}$/)});
test("temporary storage object is removed after success and read failure",async()=>{for(const fail of[false,true]){const objects=new Map<string,Buffer>(),removed:string[]=[];await assert.doesNotReject(async()=>{try{await temporaryStorageRoundTrip({upload:async(p,b)=>{objects.set(p,b)},download:async p=>{if(fail)throw new Error("read failed");return objects.get(p)!},remove:async p=>{removed.push(p);objects.delete(p)}},"temporary/test")}catch(e){if(!fail)throw e}});assert.deepEqual(removed,["temporary/test"]);assert.equal(objects.size,0)}});
test("deployment bundles embed actual ordered migration contents and no secrets",()=>{for(const[name,start]of[["trusted_estimator_0015_to_0028.sql",15],["trusted_estimator_0022_to_0028.sql",22]]as const){const sql=fs.readFileSync(`supabase/deploy/${name}`,"utf8");for(const x of MIGRATION_REGISTRY.filter(x=>Number.parseInt(x.number)>=start))assert.match(sql,new RegExp(x.file.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(sql,/begin;/);assert.match(sql,/app_readiness_snapshot/);assert.match(sql,/reload schema/);assert.doesNotMatch(sql,/service-role-key|eyJ[A-Za-z0-9_-]{20}/)}});
test("system status and active test routes remain admin protected",()=>{const middleware=fs.readFileSync("middleware.ts","utf8");assert.match(middleware,/pathname\.startsWith\("\/admin"\)/);assert.ok(fs.existsSync("app/admin/system-status/page.tsx"));assert.ok(fs.existsSync("app/admin/system-status/test/route.ts"));assert.ok(fs.existsSync("app/proposal/[token]/page.tsx"));assert.ok(fs.existsSync("app/change-order/[token]/page.tsx"))});
test("migration 0028 provides history errors delivery documents RLS and safe bootstrap",()=>{const sql=fs.readFileSync("supabase/migrations/0028_deployment_readiness_and_migration_history.sql","utf8");for(const x of["app_schema_migrations","application_operational_errors","application_delivery_attempts","application_document_generation","record_schema_migration_if_objects_exist","app_readiness_snapshot","enable row level security","service_role"])assert.match(sql,new RegExp(x))});
test("delivery retry reuses locked revisions and requires explicit admin action",()=>{const proposal=fs.readFileSync("lib/proposals/signing.ts","utf8").split("export async function retryProposalDelivery")[1],change=fs.readFileSync("lib/projects/repository.ts","utf8").split("export async function retryChangeOrderDelivery")[1];assert.doesNotMatch(proposal,/proposal_revisions"\)\.insert/);assert.doesNotMatch(change,/change_order_revisions"\)\.insert/);assert.match(fs.readFileSync("app/admin/proposals/api/[id]/retry-send/route.ts","utf8"),/recordDeliveryAttempt/);assert.match(fs.readFileSync("app/admin/change-orders/[revisionId]/retry-send/route.ts","utf8"),/recordDeliveryAttempt/)})
