import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";import path from"node:path";import{deflateSync}from"node:zlib";import{addAnnotation,DEFAULT_IMAGE_TRANSFORM,duplicateAnnotation,imageDimensions,PROJECT_IMAGE_MAX_BYTES,removeAnnotation,unresolvedImageSlots,updateAnnotation,validateImageUpload,type ImageAnnotation,type ProposalImageInstance}from"../lib/project-images/domain";import{customerFacingProposal,type ProposalDraft}from"../lib/proposals/domain";import{generateProposalPdfResult}from"../lib/proposals/pdf";
const annotation=(type:ImageAnnotation["type"],id=type):ImageAnnotation=>({id,type,x:.1,y:.1,width:.3,height:.2,rotation:0,stroke:"#dc2626",fill:"transparent",opacity:1,lineWidth:3,lineStyle:"solid",arrowhead:type==="arrow"?"end":"none",text:type==="text"?"Inspect flashing":undefined,legendNumber:type==="number"?1:undefined,points:type==="freehand"?[{x:.1,y:.1},{x:.2,y:.2}]:undefined,fontSize:16,layerOrder:1,visible:true});
const image=(id="img"):ProposalImageInstance=>({id,projectImageId:"source",versionId:"version",storagePath:"private/original.png",mimeType:"image/png",section:"plan",planType:"roof_plan",title:"Roof plan",caption:"Proposed work",comment:"Review numbered locations",include:true,displayOrder:0,layout:"image_legend",transform:{...structuredClone(DEFAULT_IMAGE_TRANSFORM),orientation:"landscape"},annotations:[annotation("arrow"),annotation("circle"),annotation("text"),annotation("number"),annotation("freehand")],legends:[{id:"l1",number:1,description:"Replace shingles",displayOrder:0,visible:true,customerFacing:true}],orientation:"landscape",customerFacing:true,allowPlaceholder:false});
const proposal=():ProposalDraft=>({id:"p",proposalNumber:"TR-IMG",estimateId:"e",estimateType:"roofing",revisionNumber:1,status:"sent",customer:{name:"A",email:"a@b.ca",phone:""},property:{address:"1 Main",city:"Calgary",province:"AB",postalCode:""},measurements:{roofAreaSqft:1,squares:1,pitch:"",complexity:"",stories:1},options:[],softMetalScopes:[],imageInstances:[image()],sections:[{type:"cover",title:"Proposal",enabled:true,displayOrder:0,content:""},{type:"plan",title:"Roof Plan",enabled:true,displayOrder:1,content:"",orientation:"landscape"}],subtotal:100,gst:5,total:105,expiryDate:"2027-01-01",proposalDate:"2026-01-01",estimatorName:"Admin",coverImage:{source:"none",attribution:"",caption:"",crop:{x:50,y:50},zoom:1,rotation:0},requiresPricingConfiguration:false});
function png(){const signature=Buffer.from("89504e470d0a1a0a","hex"),ihdr=Buffer.alloc(25);ihdr.writeUInt32BE(13,0);ihdr.write("IHDR",4);ihdr.writeUInt32BE(2,8);ihdr.writeUInt32BE(2,12);ihdr[16]=8;ihdr[17]=2;const raw=Buffer.from([0,255,0,0,0,255,0,0,0,0,255,255,255,255]),data=deflateSync(raw),chunk=Buffer.alloc(12+data.length);chunk.writeUInt32BE(data.length,0);chunk.write("IDAT",4);data.copy(chunk,8);return Buffer.concat([signature,ihdr,chunk])}
test("upload validation accepts JPEG PNG WEBP and rejects unsafe or oversized files",()=>{for(const type of["image/jpeg","image/png","image/webp"])assert.doesNotThrow(()=>validateImageUpload({type,size:10,name:"roof image.test"}));assert.throws(()=>validateImageUpload({type:"image/svg+xml",size:10,name:"x.svg"}));assert.throws(()=>validateImageUpload({type:"image/png",size:PROJECT_IMAGE_MAX_BYTES+1,name:"x.png"}))});
test("PNG dimensions and mismatched data are validated",()=>{assert.deepEqual(imageDimensions(png(),"image/png"),{width:2,height:2});assert.throws(()=>imageDimensions(Buffer.from("bad"),"image/png"))});
test("annotations remain normalized editable ordered and support undo-redo state",()=>{const before:ImageAnnotation[]=[],added=addAnnotation(before,annotation("rectangle")),changed=updateAnnotation(added,"rectangle",{x:.4}),duplicated=duplicateAnnotation(changed,"rectangle","copy"),undone=removeAnnotation(duplicated,"copy");assert.equal(changed[0].x,.4);assert.equal(duplicated.length,2);assert.deepEqual(undone,changed);assert.throws(()=>addAnnotation([], {...annotation("line"),x:2}))});
test("all required annotation tools use structured normalized data",()=>{for(const type of["arrow","line","rectangle","circle","ellipse","freehand","text","number","highlight"]as const)assert.equal(addAnnotation([],annotation(type))[0].type,type)});
test("customer snapshot excludes private paths and remains independent",()=>{const p=proposal(),safe:any=customerFacingProposal(p),snapshot=structuredClone(safe.imageInstances[0]);p.imageInstances![0].caption="Changed";assert.equal(snapshot.storagePath,undefined);assert.equal(snapshot.caption,"Proposed work");assert.equal(JSON.stringify(safe).includes("private/original"),false)});
test("one image and landscape plan render annotations and legend into PDF",()=>{const result=generateProposalPdfResult(proposal(),undefined,{images:{img:png()}}),text=result.buffer.toString("latin1"),lines=result.pages.flatMap(p=>p.lines.map(x=>x.text)).join(" ");assert.match(text,/\/XObject/);assert.match(text,/\/Pimg/);assert.match(text,/792 612/);assert.match(lines,/Replace shingles/);assert.ok(result.pages.some(p=>p.images.some(x=>x.annotations.length===5)))});

test("two-photo layout shares a page while hidden and internal images are excluded",()=>{const p=proposal(),first={...image("one"),section:"photos" as const,layout:"two" as const,orientation:"portrait" as const},second={...image("two"),section:"photos" as const,layout:"two" as const,orientation:"portrait" as const},hidden={...image("hidden"),include:false},internal={...image("internal"),customerFacing:false};p.imageInstances=[first,second,hidden,internal];p.sections=[p.sections[0],{type:"photos",title:"Photos",enabled:true,displayOrder:1,content:"",pageBreakBefore:true}];const safe=customerFacingProposal(p);assert.deepEqual(safe.imageInstances.map(x=>x.id),["one","two"]);const result=generateProposalPdfResult(p,undefined,{images:{one:png(),two:png()}});assert.ok(result.pages.some(page=>page.images.length===2),JSON.stringify(result.pages.map(x=>x.images.length)))});
test("empty slots warn while removal and reuse never delete the source",()=>{const slot={...image(),id:"empty",projectImageId:null,storagePath:null};assert.equal(unresolvedImageSlots([slot]).length,1);slot.allowPlaceholder=true;assert.equal(unresolvedImageSlots([slot]).length,0);const source=image(),instances=[source,{...source,id:"reuse"}];assert.equal(instances.filter(x=>x.id!==source.id)[0].projectImageId,"source")});
test("migration declares private storage RLS associations and immutable versions",()=>{const sql=fs.readFileSync(path.join(process.cwd(),"supabase/migrations/0022_project_image_library.sql"),"utf8");assert.match(sql,/customer_id/);assert.match(sql,/property_id/);assert.match(sql,/estimate_id/);assert.match(sql,/project_image_versions/);assert.match(sql,/service role only/);assert.match(sql,/false,15728640/)});
test("customer image route validates token and locked snapshot instance",()=>{const source=fs.readFileSync(path.join(process.cwd(),"app/proposal/[token]/image/[instanceId]/route.ts"),"utf8");assert.match(source,/loadCustomerAccess/);assert.match(source,/snapshot\.imageInstances/);assert.match(source,/instanceId/)});
