import test from"node:test";import assert from"node:assert/strict";import{calculateSystem,DEFAULT_ROOFING_SYSTEMS,type RoofingMeasurements}from"../lib/roofing-estimates/pricing";import type{EstimateDraft}from"../lib/roofing-estimates/repository";import{createProposalFromEstimate,customerFacingProposal,setRecommended,type ProposalDraft}from"../lib/proposals/domain";import{proposalPdfInput,generateProposalPdf}from"../lib/proposals/pdf";import{streetViewUrl}from"../lib/proposals/street-view";import fs from"node:fs";import path from"node:path";
const measurements:RoofingMeasurements={roofAreaSqft:2000,squares:20,pitch:"6/12",complexity:"moderate",existingLayers:1,eaves:100,rakes:50,valleys:10,hips:10,ridges:30,wallTransitions:0,plumbingVents:2,goosenecks:1,staticVents:4,stories:2,deckingAllowance:0,accessDifficulty:"standard",internalNotes:"private"};
function estimate():EstimateDraft{const systems=structuredClone(DEFAULT_ROOFING_SYSTEMS);const options=systems.map((s,i)=>({...calculateSystem(measurements,s),finalPrice:(i+1)*1050,calculatedPrice:(i+1)*1050}));return{id:"estimate-1",customer:{firstName:"Taylor",lastName:"Homeowner",email:"t@example.com",phone:""},property:{addressLine1:"1 Test Street",addressLine2:"",city:"Calgary",province:"AB",postalCode:""},measurements,systems,options}}
test("proposal creation snapshots customer, property, and roofing options",()=>{const e=estimate(),p=createProposalFromEstimate(e,{proposalNumber:"TR-1",actor:"Admin",today:"2026-01-01"});e.customer.firstName="Changed";e.property.addressLine1="Changed";e.systems[0].productName="Changed";assert.equal(p.customer.name,"Taylor Homeowner");assert.equal(p.property.address,"1 Test Street");assert.equal(p.options[0].productName,"GAF Timberline HDZ");assert.deepEqual(p.options.map(o=>o.tier),["good","better","best"])});
test("hidden options and recommendation behavior are customer safe",()=>{const p=createProposalFromEstimate(estimate(),{proposalNumber:"TR-1",actor:"Admin"});p.options[0].included=false;p.options=setRecommended(p.options,"best");const safe=customerFacingProposal(p);assert.deepEqual(safe.options.map(o=>o.tier),["better","best"]);assert.equal(safe.options.filter(o=>o.recommended).length,1)});
test("customer-facing and PDF input exclude internal estimate data",()=>{const p=createProposalFromEstimate(estimate(),{proposalNumber:"TR-1",actor:"Admin"}),safe=proposalPdfInput(p)as any;assert.equal("internalNotes"in safe.measurements,false);assert.equal("breakdown"in safe.options[0],false);assert.equal("markupPercent"in safe.options[0],false);assert.ok(generateProposalPdf(p).subarray(0,4).equals(Buffer.from("%PDF")))});
test("GST and totals remain consistent",()=>{const p=createProposalFromEstimate(estimate(),{proposalNumber:"TR-1",actor:"Admin"});assert.ok(Math.abs(p.subtotal+p.gst-p.total)<0.001)});
test("cover image gracefully falls back without API key",()=>{const old=process.env.GOOGLE_SECRET_KEY;delete process.env.GOOGLE_SECRET_KEY;assert.equal(streetViewUrl("1 Test Street"),null);process.env.GOOGLE_SECRET_KEY=old});
test("proposal draft survives persistence serialization",()=>{const p=createProposalFromEstimate(estimate(),{proposalNumber:"TR-2",actor:"Admin"});p.sections[1].content="Edited summary";const reopened=JSON.parse(JSON.stringify(p))as ProposalDraft;assert.equal(reopened.sections[1].content,"Edited summary");assert.equal(reopened.customer.name,p.customer.name)});
test("proposal migration enables RLS and a private bucket",()=>{const sql=fs.readFileSync(path.join(process.cwd(),"supabase/migrations/0016_internal_proposals.sql"),"utf8");assert.match(sql,/enable row level security/);assert.match(sql,/proposal-assets','proposal-assets',false/)});
