import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { buildProposalDocument, type SignedDocumentDetails } from "../lib/proposals/document";
import { generateProposalPdfResult, proposalDocumentInput, proposalPdfLayout } from "../lib/proposals/pdf";
import type { ProposalDraft } from "../lib/proposals/domain";

const words=(count:number,prefix="content")=>Array.from({length:count},(_,i)=>`${prefix}-${i}`).join(" ");
const base=():ProposalDraft=>({id:"p1",proposalNumber:"TR-PAGE",estimateId:"e1",estimateType:"combined",revisionNumber:3,status:"sent",customer:{name:"Alexandra Very Long Customer Name",email:"alex@example.com",phone:""},property:{address:"12345 A Particularly Long Residential Property Address",city:"Calgary",province:"AB",postalCode:"T1T 1T1"},measurements:{roofAreaSqft:2500,squares:25,pitch:"6/12",complexity:"complex",stories:2},options:[{tier:"good",tierLabel:"Good",productName:"GAF Timberline HDZ with a deliberately long system name",description:words(80,"option"),warranty:words(30,"warranty"),components:[words(20,"component")],price:15750,included:true,displayOrder:0,recommended:true,mostPopular:false}],softMetalScopes:[{id:"eaves",type:"eavestrough",title:"Six-inch Eavestrough",description:words(100,"eavestrough"),summary:{colour:"Black",linearFeet:180,size:"6-inch"},status:"optional",price:2625,displayOrder:0,colourSelection:{mode:"fixed",value:"Black"},productionReady:true,warnings:[]}],sections:[{type:"cover",title:"Exterior Proposal",enabled:true,displayOrder:0,content:""},{type:"summary",title:"Project Summary",enabled:true,displayOrder:1,content:words(70,"summary")},{type:"options",title:"Roofing Options",enabled:true,displayOrder:2,content:"Compare systems"},{type:"eavestrough",title:"Eavestrough",enabled:true,displayOrder:3,content:""},{type:"scope",title:"Detailed Roofing Scope",enabled:true,displayOrder:4,content:words(900,"scope")},{type:"terms",title:"Terms and Acceptance",enabled:true,displayOrder:5,content:words(700,"terms")},{type:"pricing",title:"Price Summary",enabled:true,displayOrder:6,content:""}],subtotal:17500,gst:875,total:18375,expiryDate:"2027-01-01",proposalDate:"2026-12-01",estimatorName:"Trusted Estimator",coverImage:{source:"upload",storagePath:"p1/private-cover.jpg",signedUrl:"expired-url",attribution:"Image attribution",caption:"Home",crop:{x:50,y:50},zoom:1,rotation:0},requiresPricingConfiguration:false});
const signed=():SignedDocumentDetails=>({selectedOption:{tier:"good"},selectedSoftScopes:[{id:"eaves",title:"Six-inch Eavestrough"}],declinedSoftScopes:[{id:"soffit",title:"Soffit"}],scopeColours:{eaves:"Black"},signerLegalName:"Alexandra Owner",signerEmail:"alex@example.com",signatureType:"typed",signatureData:"Alexandra Owner",acceptedAt:"2026-12-02T18:30:00Z",integrityHash:"a".repeat(64)});

test("short roofing proposal produces bounded numbered pages",()=>{const p=base();p.sections=p.sections.filter(s=>["cover","options","pricing","terms"].includes(s.type));p.sections.find(s=>s.type==="terms")!.content="Short terms";p.options[0].description="Short description";p.options[0].components=[];const result=generateProposalPdfResult(p);assert.ok(result.pageCount>=2);assert.equal(result.pages.length,result.pageCount);assert.match(result.buffer.toString("latin1"),new RegExp(`Page ${result.pageCount} of ${result.pageCount}`))});
test("multi-page combined proposal wraps without omitting long scope or terms",()=>{const p=base(),layout=proposalPdfLayout(p),all=layout.pages.flatMap(page=>page.lines.map(line=>line.text)).join(" ");assert.ok(layout.pages.length>=7,`pages=${layout.pages.length}`);assert.match(all,/scope-899/);assert.match(all,/terms-699/);assert.match(all,/eavestrough-99/);for(const page of layout.pages)for(const line of page.lines){assert.ok(line.y>=58,"line below footer");assert.ok(line.y<=740,"line above header")}});
test("headings stay with content and acceptance moves when space is insufficient",()=>{const p=base(),layout=proposalPdfLayout(p);for(const page of layout.pages){const last=page.lines.at(-1);assert.notEqual(last?.fontSize,15,"heading left alone at page bottom")}const acceptancePage=layout.pages.findIndex(page=>page.lines.some(line=>line.text==="Contract acceptance"));assert.ok(acceptancePage>0);assert.ok(layout.pages[acceptancePage].lines.some(line=>line.text.startsWith("Customer:")))});
test("signed document uses same engine and immutable acceptance data",()=>{const p=base(),details=signed(),result=generateProposalPdfResult(p,details),text=result.pages.flatMap(x=>x.lines.map(y=>y.text)).join(" ");p.total=1;details.signerLegalName="Changed";assert.match(text,/Accepted Proposal/);assert.match(text,/Alexandra Owner/);assert.match(text,/Six-inch Eavestrough/);assert.match(text,/Soffit/);assert.match(text,/Black/);assert.match(text,/18,375/);assert.match(text,/aaaaaaaaaaaaaaaa/)});
test("document model is sanitized and independent from expired cover URLs",()=>{const p:any=base();p.options[0].supplier="Internal";p.options[0].labourCost=4;p.options[0].profit=5;p.options[0].sourceReference="secret";const model:any=proposalDocumentInput(p);const serialized=JSON.stringify(model);assert.doesNotMatch(serialized,/Internal|labourCost|profit|sourceReference|expired-url/);assert.equal(model.cover.storagePath,"p1/private-cover.jpg")});
test("PDF generation is deterministic and reports page count, renderer and hash",()=>{const a=generateProposalPdfResult(base(),signed()),b=generateProposalPdfResult(base(),signed());assert.equal(a.documentHash,b.documentHash);assert.equal(a.pageCount,b.pageCount);assert.equal(a.rendererVersion,"trusted-paginated-v1");assert.ok(a.pageCount>=8,`pages=${a.pageCount}`);assert.ok(a.buffer.subarray(0,4).equals(Buffer.from("%PDF")))});
test("preview and PDF use the same normalized document model",()=>{const p=base();assert.deepEqual(buildProposalDocument(p),proposalDocumentInput(p))});
test("private cover loader uses storage path and customer download remains token validated",()=>{const pdfSource=fs.readFileSync(path.join(process.cwd(),"lib/proposals/pdf.ts"),"utf8"),download=fs.readFileSync(path.join(process.cwd(),"app/proposal/[token]/signed-pdf/route.ts"),"utf8");assert.match(pdfSource,/storage\.from[\s\S]*download\(p\.coverImage\.storagePath\)/);assert.doesNotMatch(pdfSource,/fetch\(p\.coverImage\.signedUrl/);assert.match(download,/loadCustomerAccess\(params\.token,false\)/)});
test("document migration adds idempotent metadata and failure events",()=>{const sql=fs.readFileSync(path.join(process.cwd(),"supabase/migrations/0021_paginated_proposal_documents.sql"),"utf8");assert.match(sql,/page_count/);assert.match(sql,/renderer_version/);assert.match(sql,/document_hash/);assert.match(sql,/unique index/);assert.match(sql,/pdf_generation_failed/);assert.match(sql,/signed_pdf_generation_failed/)});
