import assert from "node:assert/strict";
import test from "node:test";
import { confidence, haversine, pricing } from "../lib/roof-measurement-lab";
import { classifyExterior, classifyInternal, edgeLength, fitPlane, intersectionConvex, mergeCompatibleFacets, planeOrientation, planeSurfaceArea, polygonArea, reconstructRoof, annotateFacetPitches, edgeAccounting, splitFacetStructures, topologyConfidence } from "../lib/roof-geometry";

test("lab pricing follows the isolated calibrated formula",()=>{const p=pricing(1000,Array.from({length:7},()=>({areaSqft:1000/7,pitchX12:7})));assert.equal(p.basePrice,5800);assert.equal(p.facetAdjustment,.02);assert.equal(Math.round(p.totalPitchSurcharge),100);assert.equal(Math.round(p.center),6018);assert.equal(p.low,5650);assert.equal(p.high,6400)});
test("confidence weights total exactly 100 for excellent inputs",()=>{const c=confidence({quality:"HIGH",distance:1,coverage:.98,maskDiff:1,areaDiff:1,planeCoverage:.99,residual:.05});assert.equal(c.total,100);assert.equal(c.label,"VERY HIGH");assert.deepEqual(c.components,{imagery:15,location:15,googleCoverage:15,rasterAgreement:15,areaAgreement:20,planeQuality:20})});
test("building-center distance uses meters",()=>{assert.ok(haversine({latitude:51,longitude:-114},{latitude:51.00001,longitude:-114})>1)});

test("robust plane fitting rejects an elevation outlier",()=>{const points=[];for(let y=0;y<5;y++)for(let x=0;x<5;x++)points.push({x,y,z:2*x-.5*y+7});points.push({x:2,y:2,z:100});const p=fitPlane(points);assert.ok(Math.abs(p.a-2)<1e-8);assert.ok(Math.abs(p.b+.5)<1e-8);assert.ok(p.rms<1e-8)});
test("plane pitch and downslope azimuth are mathematical",()=>{const east=planeOrientation({a:-.5,b:0});assert.ok(Math.abs(east.pitchX12-6)<1e-9);assert.equal(east.azimuthDegrees,90);assert.equal(east.compass,"E")});
test("polygon, plane surface area and 3D edge length are exact",()=>{assert.equal(polygonArea([{x:0,y:0},{x:4,y:0},{x:4,y:3},{x:0,y:3}]),12);assert.equal(planeSurfaceArea(12,{a:.75,b:0}),15);assert.equal(edgeLength([{x:0,y:0,z:0},{x:3,y:4,z:12}]),13)});
test("concave, level convex, and sloped convex edges classify valley ridge hip",()=>{assert.equal(classifyInternal(false,0,5),"VALLEY");assert.equal(classifyInternal(true,.1,5),"RIDGE");assert.equal(classifyInternal(true,1,5),"HIP");assert.equal(intersectionConvex({a:1,b:0},{a:-1,b:0},{x:-1,y:0}),false)});
test("exterior geometry distinguishes eave rake and ambiguous",()=>{assert.equal(classifyExterior(90,0),"EAVE");assert.equal(classifyExterior(5,0),"RAKE");assert.equal(classifyExterior(45,0),"UNSPECIFIED")});
test("micro-facet merge tolerances preserve opposite slopes",()=>{const base:any={pitchDegrees:20,azimuthDegrees:90};assert.equal(mergeCompatibleFacets(base,{...base,pitchDegrees:21,azimuthDegrees:93},.1),true);assert.equal(mergeCompatibleFacets(base,{...base,azimuthDegrees:270},.1),false)});

function synthetic(kind:"gable"|"hip"|"valley"|"multiHip"){const width=40,height=40,values=[];for(let y=0;y<height;y++)for(let x=0;x<width;x++){if(kind==="gable")values.push(10-.5*Math.abs(x-20));else if(kind==="valley")values.push(5+.4*Math.abs(x-20));else if(kind==="hip")values.push(12-.35*Math.max(Math.abs(x-20),Math.abs(y-20)));else values.push(12-.3*Math.max(Math.abs(x-20),Math.abs(y-20))+.02*Math.min(x,y))}const diagnostic:any={compression:1,layout:"strips",predictor:1,bitsPerSample:[32],sampleFormat:[3],samplesPerPixel:1,photometricInterpretation:1,width,height,pixelScale:[.2,.2],noData:null};return{width,height,bands:1,values:[values],bounds:[0,0,8,8] as [number,number,number,number],pixelWidthM:.2,pixelHeightM:.2,noData:null,transform:[.2,0,0,0,-.2,8] as [number,number,number,number,number,number],pixelToWorld:(col:number,row:number)=>({x:col*.2,y:8-row*.2}),worldToPixel:(x:number,y:number)=>({col:x/.2,row:(8-y)/.2}),wgs84ToPixel:(longitude:number,latitude:number)=>({col:longitude/.2,row:(8-latitude)/.2}),diagnostic}}
for(const [kind,min] of [["gable",2],["hip",4],["valley",2],["multiHip",3]] as const)test(`synthetic ${kind} reconstructs independent planes`,()=>{const r=synthetic(kind),model=reconstructRoof(r,Array.from({length:r.width*r.height},(_,i)=>i));assert.ok(model.facets.length>=min,`${model.facets.length} facets`);assert.ok(model.assignedRoofPercent>.5);assert.ok(model.edges.length>0);for(const facet of model.facets)assert.ok(facet.boundaryAdjustedTriangulatedAreaM2+1e-9>=facet.groundAreaM2)});
test("clean simple gable has two facets, one ridge topology, and no valleys or hips",()=>{const r=synthetic("gable"),model=reconstructRoof(r,Array.from({length:r.width*r.height},(_,i)=>i));assert.equal(model.facets.length,2);assert.equal(model.edges.filter(e=>e.type==="RIDGE").length,1);assert.equal(model.edges.filter(e=>e.type==="VALLEY"||e.type==="HIP").length,0)});
test("clean valley topology requires both planes to drain toward their intersection",()=>{const r=synthetic("valley"),model=reconstructRoof(r,Array.from({length:r.width*r.height},(_,i)=>i));assert.equal(model.facets.length,2);assert.equal(model.edges.filter(e=>e.type==="VALLEY").length,1);assert.equal(model.edges.filter(e=>e.type==="RIDGE").length,0)});
test("elongated four-plane hip roof retains hips and a ridge without valleys",()=>{const r=synthetic("hip"),width=r.width;r.values[0]=r.values[0].map((_,i)=>12-.35*Math.max(Math.abs(Math.floor(i/width)-20),Math.max(0,Math.abs(i%width-20)-8)));const model=reconstructRoof(r,Array.from({length:r.width*r.height},(_,i)=>i));assert.equal(model.facets.length,4);assert.ok(model.edges.some(e=>e.type==="HIP"));assert.ok(model.edges.some(e=>e.type==="RIDGE"));assert.equal(model.edges.filter(e=>e.type==="VALLEY").length,0)});
test("narrow noisy strip and tiny false pitch region do not survive as pricing facets",()=>{const r=synthetic("gable"),width=r.width;for(let y=4;y<36;y++)for(let x=4;x<8;x++)r.values[0][y*width+x]+=.04;for(let y=10;y<15;y++)for(let x=28;x<33;x++)r.values[0][y*width+x]+=.08;const model=reconstructRoof(r,Array.from({length:r.width*r.height},(_,i)=>i));assert.equal(model.facets.length,2);assert.ok("rawTopology" in model&&model.rawTopology.facetCount>=model.cleanTopology.facetCount)});

function topologyFacet(id:string,x:number,z=5,pitchX12=6):any{return{id,structureId:1,pixels:[],plane:{a:-pitchX12/12,b:0,c:z,rms:.03,medianResidual:.02,pixelCount:100},groundAreaM2:10,surfaceAreaM2:10,triangulatedAreaM2:10,interiorTriangulatedAreaM2:10,boundaryAdjustedTriangulatedAreaM2:10,areaSqft:107.639,pitchDegrees:Math.atan(pitchX12/12)*180/Math.PI,pitchX12,pitchBucket:Math.round(pitchX12),azimuthDegrees:90,compass:"E",centroid:{x:x+.5,y:.5},polygon:[{x,y:0},{x:x+1,y:0},{x:x+1,y:1},{x,y:1}],fitStatus:"ACCEPTED"}}
function topologyEdge(a:string,b:string|null,type:any,lengthM=1):any{return{id:`${a}-${b}`,type,facetA:a,facetB:b,points:[{x:0,y:0,z:0},{x:lengthM,y:0,z:0}],planLengthM:lengthM,lengthM,gradeDegrees:0,confidence:.9,diagnostic:{reason:"synthetic"}}}
test("one noisy mask-pixel bridge does not join disconnected final facet groups",()=>{const facets=[topologyFacet("F1",0),topologyFacet("F2",3)];assert.equal(splitFacetStructures(facets,[]).length,2)});
test("two roof masses with a legitimate valley remain one structure",()=>{const facets=[topologyFacet("F1",0),topologyFacet("F2",1)];assert.equal(splitFacetStructures(facets,[topologyEdge("F1","F2","VALLEY")]).length,1)});
test("two roofs touching in plan but one metre apart vertically remain separate without a transition",()=>{const facets=[topologyFacet("F1",0,5),topologyFacet("F2",1,6)];const groups=splitFacetStructures(facets,[topologyEdge("F1","F2","RIDGE")]);assert.equal(groups.length,2);assert.ok((groups[0].minimum3dGapM||0)>=1)});
test("exterior measurement accounting conserves classified and unspecified perimeter",()=>{const edges=[topologyEdge("F1",null,"EAVE",4),topologyEdge("F1",null,"RAKE",3),topologyEdge("F1",null,"UNSPECIFIED",2)],accounting=edgeAccounting(edges);assert.equal(accounting.totalExteriorPerimeter,9);assert.equal(accounting.classifiedExteriorLength,7);assert.equal(accounting.unclassifiedExteriorLength,2);assert.equal(accounting.exteriorAccountingDifference,0)});
test("pitch outlier records a regularized or Google-backed pricing pitch without changing its fitted plane",()=>{const facets=[topologyFacet("F1",0,5,7),topologyFacet("F2",1,5,7.2),topologyFacet("F3",2,5,3)],raw=facets[2].pitchX12;facets[2].surfaceAreaM2=facets[2].groundAreaM2=facets[2].areaSqft=1;annotateFacetPitches(facets,[{x:2.5,y:.5,pitchX12:7}]);assert.equal(facets[2].pitchX12,raw);assert.equal(facets[2].pricingPitchX12,7);assert.notEqual(facets[2].pricingPitchSource,"RAW_DSM")});
test("main-only and main-plus-accessory pricing scopes use their own areas and final facets",()=>{const main=[topologyFacet("F1",0)],accessory=[topologyFacet("F2",3)],mainPrice=pricing(1000,main),allPrice=pricing(1200,[...main,...accessory]);assert.equal(mainPrice.roofSquares,10);assert.equal(allPrice.roofSquares,12);assert.ok(allPrice.center>mainPrice.center)});
test("topology confidence is independent from Roofr benchmark values",()=>{const facets=[topologyFacet("F1",0)],edges=[topologyEdge("F1",null,"EAVE",4)];annotateFacetPitches(facets,[{x:.5,y:.5,pitchX12:6}]);const structures=splitFacetStructures(facets,edges),score=topologyConfidence(structures,facets,edges,10);assert.equal(score.score,100)});
test("measurement outline remains separate from display simplification without changing facet area",()=>{const r=synthetic("gable"),model=reconstructRoof(r,Array.from({length:r.width*r.height},(_,i)=>i));for(const facet of model.facets){assert.ok(facet.measurementPolygon);assert.ok(facet.rawPolygon);assert.ok(facet.measurementPolygon!.length>=facet.polygon.length);assert.equal(facet.surfaceAreaM2,facet.groundAreaM2*Math.sqrt(1+facet.plane.a**2+facet.plane.b**2))}});
