import assert from "node:assert/strict";
import test from "node:test";
import { precisionAnalysis, rgbPixelToWorld, sobelRgb, worldToRgbPixel } from "../lib/roof-precision";

function raster(bands=1):any {const width=20,height=20,values=Array.from({length:bands},()=>Array(width*height).fill(0));return{width,height,bands,values,bounds:[0,0,20,20],pixelWidthM:1,pixelHeightM:1,noData:null,transform:[1,0,0,0,-1,20],pixelToWorld:(col:number,row:number)=>({x:col,y:20-row}),worldToPixel:(x:number,y:number)=>({col:x,row:20-y}),wgs84ToPixel:(x:number,y:number)=>({col:x,row:20-y}),diagnostic:{geoKeys:{ProjectedCSTypeGeoKey:32612}}}}
function facet():any{return{id:"F1",structureId:1,pixels:[],plane:{a:0,b:0,c:5,rms:.03,medianResidual:.02,pixelCount:100},groundAreaM2:100,surfaceAreaM2:100,triangulatedAreaM2:100,interiorTriangulatedAreaM2:100,boundaryAdjustedTriangulatedAreaM2:100,areaSqft:1076.39,pitchDegrees:0,pitchX12:0,pitchBucket:0,azimuthDegrees:0,compass:"N",centroid:{x:10,y:10},polygon:[{x:0,y:0},{x:20,y:0},{x:20,y:20},{x:0,y:20}],fitStatus:"ACCEPTED"}}
function edge():any{return{id:"E1",type:"RIDGE",facetA:"F1",facetB:"F2",points:[{x:10,y:2,z:5},{x:10,y:18,z:5}],planLengthM:16,lengthM:16,gradeDegrees:0,confidence:.9,diagnostic:{reason:"DSM"}}}
test("RGB georeference helpers round trip without assuming DSM dimensions",()=>{const rgb=raster(3),world=rgbPixelToWorld(rgb,7.25,4.5),pixel=worldToRgbPixel(rgb,world.x,world.y);assert.ok(Math.abs(pixel.col-7.25)<1e-10);assert.ok(Math.abs(pixel.row-4.5)<1e-10)});
test("Sobel RGB edge map detects a strong architectural boundary",()=>{const rgb=raster(3);for(let y=0;y<20;y++)for(let x=10;x<20;x++)for(let b=0;b<3;b++)rgb.values[b][y*20+x]=255;const map=sobelRgb(rgb);assert.ok(map.some((value:number)=>value>.9))});
test("precision analysis scores hypotheses, limits snaps, conserves area, and leaves DSM control immutable",()=>{const rgb=raster(3),mask=raster(),dsm=raster();mask.values[0].fill(1);for(let y=0;y<20;y++)for(let x=11;x<20;x++)for(let b=0;b<3;b++)rgb.values[b][y*20+x]=255;const original=edge(),originalJson=JSON.stringify(original),result=precisionAnalysis({rgb,mask,dsm,cropOffset:{x:0,y:0},facets:[facet()],edges:[original],assignedRoofPercent:.98,weightedRmsResidualM:.04,preferredGoogleAreaM2:100,googleSegmentCount:1});assert.equal(JSON.stringify(original),originalJson);assert.equal(result.surfaceAreaM2,100);assert.ok(result.topologyCandidates.length>=3);assert.ok(result.bestScore>=result.secondBestScore);assert.ok(result.maxSnapDistanceMeters<=1.25);assert.equal(result.lineDiagnostics.length,1);assert.equal(result.rgbGeoReference.width,20)});
