import assert from "node:assert/strict";
import test from "node:test";
import { confidence, haversine, pricing } from "../lib/roof-measurement-lab";
import { classifyExterior, classifyInternal, edgeLength, fitPlane, intersectionConvex, mergeCompatibleFacets, planeOrientation, planeSurfaceArea, polygonArea, reconstructRoof } from "../lib/roof-geometry";

test("lab pricing follows the isolated calibrated formula",()=>{const p=pricing(1000,Array.from({length:7},()=>({areaSqft:1000/7,pitchX12:7})));assert.equal(p.basePrice,5800);assert.equal(p.facetAdjustment,.02);assert.equal(Math.round(p.totalPitchSurcharge),100);assert.equal(Math.round(p.center),6018);assert.equal(p.low,5650);assert.equal(p.high,6400)});
test("confidence weights total exactly 100 for excellent inputs",()=>{const c=confidence({quality:"HIGH",distance:1,coverage:.98,maskDiff:1,areaDiff:1,planeCoverage:.99,residual:.05});assert.equal(c.total,100);assert.equal(c.label,"VERY HIGH");assert.deepEqual(c.components,{imagery:15,location:15,googleCoverage:15,rasterAgreement:15,areaAgreement:20,planeQuality:20})});
test("building-center distance uses meters",()=>{assert.ok(haversine({latitude:51,longitude:-114},{latitude:51.00001,longitude:-114})>1)});

test("robust plane fitting rejects an elevation outlier",()=>{const points=[];for(let y=0;y<5;y++)for(let x=0;x<5;x++)points.push({x,y,z:2*x-.5*y+7});points.push({x:2,y:2,z:100});const p=fitPlane(points);assert.ok(Math.abs(p.a-2)<1e-8);assert.ok(Math.abs(p.b+.5)<1e-8);assert.ok(p.rms<1e-8)});
test("plane pitch and downslope azimuth are mathematical",()=>{const east=planeOrientation({a:-.5,b:0});assert.ok(Math.abs(east.pitchX12-6)<1e-9);assert.equal(east.azimuthDegrees,90);assert.equal(east.compass,"E")});
test("polygon, plane surface area and 3D edge length are exact",()=>{assert.equal(polygonArea([{x:0,y:0},{x:4,y:0},{x:4,y:3},{x:0,y:3}]),12);assert.equal(planeSurfaceArea(12,{a:.75,b:0}),15);assert.equal(edgeLength([{x:0,y:0,z:0},{x:3,y:4,z:12}]),13)});
test("concave, level convex, and sloped convex edges classify valley ridge hip",()=>{assert.equal(classifyInternal(false,0,5),"VALLEY");assert.equal(classifyInternal(true,.1,5),"RIDGE");assert.equal(classifyInternal(true,1,5),"HIP");assert.equal(intersectionConvex({a:1,b:0},{a:-1,b:0},{x:-1,y:0}),false)});
test("exterior geometry distinguishes eave rake and ambiguous",()=>{assert.equal(classifyExterior(90,0),"EAVE");assert.equal(classifyExterior(5,0),"RAKE");assert.equal(classifyExterior(45,0),"UNSPECIFIED")});
test("micro-facet merge tolerances preserve opposite slopes",()=>{const base:any={pitchDegrees:20,azimuthDegrees:90};assert.equal(mergeCompatibleFacets(base,{...base,pitchDegrees:21,azimuthDegrees:93},.1),true);assert.equal(mergeCompatibleFacets(base,{...base,azimuthDegrees:270},.1),false)});

function synthetic(kind:"gable"|"hip"|"valley"|"multiHip"){const width=40,height=40,values=[];for(let y=0;y<height;y++)for(let x=0;x<width;x++){if(kind==="gable")values.push(10-.5*Math.abs(x-20));else if(kind==="valley")values.push(5+.4*Math.abs(x-20));else if(kind==="hip")values.push(12-.35*Math.max(Math.abs(x-20),Math.abs(y-20)));else values.push(12-.3*Math.max(Math.abs(x-20),Math.abs(y-20))+.02*Math.min(x,y))}const diagnostic:any={compression:1,layout:"strips",predictor:1,bitsPerSample:[32],sampleFormat:[3],samplesPerPixel:1,photometricInterpretation:1,width,height,pixelScale:[.2,.2],noData:null};return{width,height,bands:1,values:[values],bounds:[0,0,8,8] as [number,number,number,number],pixelWidthM:.2,pixelHeightM:.2,noData:null,transform:[.2,0,0,0,-.2,8] as [number,number,number,number,number,number],pixelToWorld:(col:number,row:number)=>({x:col*.2,y:8-row*.2}),worldToPixel:(x:number,y:number)=>({col:x/.2,row:(8-y)/.2}),wgs84ToPixel:(longitude:number,latitude:number)=>({col:longitude/.2,row:(8-latitude)/.2}),diagnostic}}
for(const [kind,min] of [["gable",2],["hip",4],["valley",2],["multiHip",3]] as const)test(`synthetic ${kind} reconstructs independent planes`,()=>{const r=synthetic(kind),model=reconstructRoof(r,Array.from({length:r.width*r.height},(_,i)=>i));assert.ok(model.facets.length>=min,`${model.facets.length} facets`);assert.ok(model.assignedRoofPercent>.5);assert.ok(model.edges.length>0)});
