import test from"node:test";import assert from"node:assert/strict";import{blankSoftMetalScopes,calculateSoftMetalScope,customerSoftMetalSummary,fasciaFeet,requirements,soffitArea,type SoftMetalScope}from"../lib/soft-metals/domain";import type{PricingCatalogItem,PricingCatalogVersion,PricingRateItem}from"../lib/pricing-catalog/types";
const version:PricingCatalogVersion={id:"v",name:"Approved",source_file:null,effective_date:"2026-01-01",status:"approved",created_at:""};let id=0;const item=(name:string,coverage=10,extra:Partial<PricingCatalogItem>={}):PricingCatalogItem=>({id:`i${++id}`,catalog_version_id:"v",category:"soft metals",subcategory:name,name, supplier:"Supplier",price:20,currency:"CAD",unit:"piece",coverage,coverage_unit:"linear feet per piece",quote_required:false,source_reference:"ref",notes:null,active:true,created_at:"",...extra});const rate:PricingRateItem={id:"r",catalog_version_id:"v",trade:"soft metals",rate_type:"installation",name:"Installation",rate:5,currency:"CAD",unit:"linear foot",source_reference:"rate",active:true,created_at:""};
function enabled(type:SoftMetalScope["type"]){const s=blankSoftMetalScopes().find(x=>x.type===type)!;s.enabled=true;return s}
test("five and six inch eavestrough selection preserves measured LF and accessories",()=>{for(const size of["5","6"]as const){const s=enabled("eavestrough");Object.assign(s.measurements,{linearFeet:21,size,insideMitres:2,outsideMitres:1,endCaps:4,outlets:3,hangers:20,leafProtection:true});s.products={primary:"main",insideMitres:"in",outsideMitres:"out",endCaps:"end",outlets:"outlet",hangers:"hanger",leafProtection:"leaf"};const req=requirements(s);assert.equal(req.primary,21);assert.equal(req.insideMitres,2);assert.equal(req.outlets,3);assert.equal(req.endCaps,4);assert.equal(req.leafProtection,21);assert.equal(customerSoftMetalSummary(s).size,`${size}-inch`)}});
test("eavestrough ten-foot pieces ceiling to three",()=>{const s=enabled("eavestrough");s.measurements.linearFeet=21;s.products.primary="main";const result=calculateSoftMetalScope(s,version,[{...item("eavestrough"),id:"main"}],[rate]);assert.equal(result.materialSnapshots[0].orderQuantity,3);assert.equal(result.rateSnapshots[0].appliedQuantity,21)});
test("downspout quantities and accessories remain explicit",()=>{const s=enabled("downspouts");Object.assign(s.measurements,{quantity:3,linearFeet:42,elbows:6,straps:9,upperLeaders:2,splashPads:3});assert.deepEqual(requirements(s),{primary:42,elbows:6,straps:9,outlets:0,upperLeaders:2,kickOuts:0,splashPads:3})});
test("partial and full fascia modes calculate distinct footage",()=>{const s=enabled("fascia");Object.assign(s.measurements,{mode:"partial",partialLinearFeet:21,eaveLinearFeet:100,gableLinearFeet:50});assert.equal(fasciaFeet(s.measurements),21);s.measurements.mode="full";assert.equal(fasciaFeet(s.measurements),150)});
test("fascia materials ceiling while labour stays measured",()=>{const s=enabled("fascia");Object.assign(s.measurements,{mode:"partial",partialLinearFeet:21});s.products.primary="f";const result=calculateSoftMetalScope(s,version,[{...item("fascia"),id:"f"}],[rate]);assert.equal(result.materialSnapshots[0].orderQuantity,3);assert.equal(result.rateSnapshots[0].appliedQuantity,21)});
test("soffit width times length and direct override auditing",()=>{const s=enabled("soffit");Object.assign(s.measurements,{type:"vented",widthFeet:2,eaveLengthFeet:50});assert.equal(soffitArea(s.measurements),100);s.measurements.directArea=120;assert.equal(soffitArea(s.measurements),120);s.products.primary="s";assert.equal(calculateSoftMetalScope(s,version,[{...item("soffit",100),id:"s"}],[rate]).productionReady,false);s.measurements.directAreaReason="Field measurement";const result=calculateSoftMetalScope(s,version,[{...item("soffit",100),id:"s"}],[rate]);assert.equal(result.materialSnapshots[0].orderQuantity,2)});
test("solid and vented soffit are sanitized without costs",()=>{for(const type of["solid","vented"]as const){const s=enabled("soffit");Object.assign(s.measurements,{type,directArea:100,directAreaReason:"Measured"});const summary:any=customerSoftMetalSummary(s);assert.equal(summary.soffitType,type);assert.equal("materialCost"in summary,false)}});
test("missing product, price, coverage, quote and labour block readiness",()=>{for(const product of[undefined,item("missing-price",10,{price:null}),item("missing-coverage",10,{coverage:null}),item("quote",10,{quote_required:true})]){const s=enabled("fascia");s.measurements.partialLinearFeet=20;if(product)s.products.primary=product.id;assert.equal(calculateSoftMetalScope(s,version,product?[product]:[],product===undefined?[]:[rate]).productionReady,false)}});
test("manual quote price can resolve quote-required material",()=>{const p=item("quote",10,{quote_required:true}),s=enabled("fascia");s.measurements.partialLinearFeet=20;s.products.primary=p.id;s.manualPrices={primary:25};assert.equal(calculateSoftMetalScope(s,version,[p],[rate]).productionReady,true)});
test("cost plus 100 and strategic selling price",()=>{const p=item("fascia"),s=enabled("fascia");s.measurements.partialLinearFeet=20;s.products.primary=p.id;let result=calculateSoftMetalScope(s,version,[p],[rate]);assert.equal(result.result.sellingPrice,result.result.totalCost+100);s.pricingStrategy={type:"strategic_price",value:50};result=calculateSoftMetalScope(s,version,[p],[rate]);assert.equal(result.result.sellingPrice,50)});
test("disabled scopes leave roofing-only estimates unaffected",()=>assert.equal(calculateSoftMetalScope(blankSoftMetalScopes()[0],version,[],[]).productionReady,true));
test("scope calculation snapshots are independent",()=>{const p=item("fascia"),s=enabled("fascia");s.measurements.partialLinearFeet=20;s.products.primary=p.id;const result=calculateSoftMetalScope(s,version,[p],[rate]);p.price=999;assert.equal(result.materialSnapshots[0].unitPrice,20)});
