import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { calculateProposalSelection, createProposalFromEstimate, customerFacingProposal, type ProposalDraft, type ProposalSoftMetalScope } from "../lib/proposals/domain";
import { validateAcceptance } from "../lib/proposals/acceptance";
import { proposalPdfInput } from "../lib/proposals/pdf";

const scope=(id:string,type:ProposalSoftMetalScope["type"],status:ProposalSoftMetalScope["status"],price=1050):ProposalSoftMetalScope=>({id,type,title:type,description:`Customer-safe ${type}`,summary:{colour:"Black",linearFeet:100},status,price,displayOrder:0,colourSelection:{mode:"fixed",value:"Black"},productionReady:true,warnings:[]});
const proposal=(soft:ProposalSoftMetalScope[],roofing=false):ProposalDraft=>({id:"p",proposalNumber:"TR-20",estimateId:"e",estimateType:roofing?"combined":"soft_metals",revisionNumber:1,status:"sent",customer:{name:"Alex",email:"a@example.com",phone:""},property:{address:"1 Main",city:"Calgary",province:"AB",postalCode:""},measurements:{roofAreaSqft:0,squares:0,pitch:"",complexity:"",stories:1},options:roofing?[{tier:"good",tierLabel:"Good",productName:"GAF",description:"Roof",warranty:"",components:[],price:10500,included:true,displayOrder:0,recommended:false,mostPopular:false}]:[],softMetalScopes:soft,sections:[],subtotal:0,gst:0,total:0,expiryDate:"2027-01-01",proposalDate:"2026-01-01",estimatorName:"Admin",coverImage:{source:"none",attribution:"",caption:"",crop:{x:50,y:50},zoom:1,rotation:0},requiresPricingConfiguration:false});
const acceptance={signerLegalName:"Alex",signerEmail:"a@example.com",signatureType:"typed" as const,signatureData:"Alex",authorityAccepted:true,termsAccepted:true};

test("soft-metals-only selection requires no roofing option and calculates GST",()=>{const p=proposal([scope("e","eavestrough","required",1050),scope("s","soffit","optional",525)]);const result=calculateProposalSelection(p,{selectedSoftScopeIds:["s"]});assert.deepEqual(result.selectedSoftScopes.map(x=>x.id),["e","s"]);assert.equal(result.subtotal,1500);assert.equal(result.gst,75);assert.equal(result.total,1575)});
test("optional scope can be declined while required scope cannot be removed",()=>{const result=calculateProposalSelection(proposal([scope("e","eavestrough","required"),scope("s","soffit","optional")]),{selectedSoftScopeIds:[]});assert.deepEqual(result.selectedSoftScopes.map(x=>x.id),["e"]);assert.deepEqual(result.declinedSoftScopes.map(x=>x.id),["s"])});
test("dependencies, hidden selections, alternatives and manipulated IDs are rejected",()=>{const e=scope("e","eavestrough","optional"),d={...scope("d","downspouts","optional"),dependency:{requires:"e"}};assert.throws(()=>calculateProposalSelection(proposal([e,d]),{selectedSoftScopeIds:["d"]}),/requires/);assert.doesNotThrow(()=>calculateProposalSelection(proposal([e,d]),{selectedSoftScopeIds:["e","d"]}));assert.throws(()=>calculateProposalSelection(proposal([scope("i","fascia","internal_only")]),{selectedSoftScopeIds:["i"]}),/unavailable/);assert.throws(()=>calculateProposalSelection(proposal([]),{selectedSoftScopeIds:["fake"]}),/unavailable/);const a={...scope("a","fascia","alternative"),dependency:{alternativeGroup:"fascia"}},b={...scope("b","fascia","alternative"),dependency:{alternativeGroup:"fascia"}};assert.throws(()=>calculateProposalSelection(proposal([a,b]),{selectedSoftScopeIds:["a","b"]}),/Only one/)});
test("combined proposal adds roofing and required soft-metal totals server-side",()=>{const result=calculateProposalSelection(proposal([scope("f","fascia","included",1050)],true),{selectedTier:"good",selectedSoftScopeIds:[]});assert.equal(result.total,11550);assert.equal(result.gst,550)});
test("acceptance snapshots selected and declined scopes",()=>{const p=proposal([scope("e","eavestrough","required"),scope("s","soffit","optional")]);const result=validateAcceptance(p,{...acceptance,selectedSoftScopeIds:[]});assert.equal(result.selectedSoftScopes[0].id,"e");assert.equal(result.declinedSoftScopes[0].id,"s")});
test("customer and PDF sanitization omit internal catalogue and costing data",()=>{const unsafe:any={...scope("e","eavestrough","included"),supplier:"Secret",materialCost:1,labourCost:2,sourceReference:"Workbook",warnings:["private"]};const safe:any=customerFacingProposal(proposal([unsafe])).softMetalScopes[0];assert.equal(safe.supplier,undefined);assert.equal(safe.materialCost,undefined);assert.equal(safe.warnings,undefined);assert.deepEqual(proposalPdfInput(proposal([unsafe])).softMetalScopes[0],safe)});
test("proposal creation supports soft-only and snapshots saved customer summary independently",()=>{const saved={colour:"White",linearFeet:80};const estimate:any={id:"e",scopeMode:"soft_metals",customer:{firstName:"A",lastName:"B",email:"a@b.ca",phone:""},property:{addressLine1:"1 Main",city:"Calgary",province:"AB",postalCode:""},measurements:{roofAreaSqft:0,squares:0,pitch:"",complexity:"",stories:1},systems:[],options:[],softMetalScopes:[{enabled:true,type:"eavestrough",customerSummary:saved,result:{sellingPrice:1000},productionReady:true,warnings:[]}]};const draft=createProposalFromEstimate(estimate,{proposalNumber:"TR",actor:"Admin",today:"2026-01-01"});saved.colour="Changed";assert.equal(draft.options.length,0);assert.equal(draft.softMetalScopes?.[0].summary.colour,"White");assert.ok(draft.sections.some(s=>s.type==="eavestrough"))});
test("migration stores immutable soft-metal acceptance selections with service-role RPC",()=>{const sql=fs.readFileSync(path.join(process.cwd(),"supabase/migrations/0020_soft_metal_proposals.sql"),"utf8");assert.match(sql,/selected_scope_snapshots/);assert.match(sql,/accept_proposal_revision_v2/);assert.match(sql,/consumed_at is null/);assert.match(sql,/grant execute.*service_role/i)});
