import test from "node:test";
import assert from "node:assert/strict";
import { calculateSystem, DEFAULT_ROOFING_SYSTEMS, normalizeRoofStructures, parsePitch, type RoofingMeasurements, type RoofingSystem } from "../lib/roofing-estimates/pricing";

const liveMeasurements: RoofingMeasurements = { roofAreaSqft: 2491, squares: 0, pitch: "4/12", complexity: "moderate", existingLayers: 1, eaves: 146, rakes: 159, valleys: 36, hips: 0, ridges: 112, wallTransitions: 2, plumbingVents: 1, goosenecks: 3, staticVents: 0, stories: 1, deckingAllowance: 0, accessDifficulty: "standard", internalNotes: "", structures: [
  { id: "main", label: " Main Home ", inclusionStatus: "included", displayOrder: 0, internalNotes: "", pitchAreas: [
    { id: "p1", pitch: parsePitch("4/12"), squareFootage: 2091, areaEntryType: "actual_roof_area", includeStatus: "included", displayOrder: 0 },
    { id: "p2", pitch: parsePitch("8/12"), squareFootage: 400, areaEntryType: "actual_roof_area", includeStatus: "included", displayOrder: 1 }
  ], measurements: { eaves: 146, rakes: 159, valleys: 36, hips: 0, ridges: 112, wallTransitions: 2, stepFlashing: 0, headwallFlashing: 2, sidewallFlashing: 0, chimneyPerimeter: 0, skylightPerimeter: 0, customFlashing: 0, existingLayers: 1, stories: 1, complexity: "moderate", accessDifficulty: "standard", deckingAllowance: 0, internalNotes: "" }, penetrations: { plumbingVents: 1, goosenecks: 3, bathroomExhausts: 0, dryerExhausts: 0, rangeExhausts: 0, skylights: 0, chimneys: 0, roofHatches: 0, solarPenetrations: 0, satelliteMounts: 0, customPenetrations: 0 }, ventilation: { atticFloorAreaSqft: 2491, ratio: 300, existingIntakeNfva: 0, existingExhaustNfva: 0, eligibleRidgeLength: 112, intakeNfvaPerUnit: 9, exhaustNfvaPerUnit: 50 } },
  { id: "garage", label: "Garage", inclusionStatus: "optional", displayOrder: 1, internalNotes: "", pitchAreas: [
    { id: "g1", pitch: parsePitch("5/12"), squareFootage: 200, areaEntryType: "actual_roof_area", includeStatus: "included", displayOrder: 0 },
    { id: "g2", pitch: parsePitch("5/12"), squareFootage: 200, areaEntryType: "actual_roof_area", includeStatus: "included", displayOrder: 1 }
  ], measurements: { eaves: 40, rakes: 30, valleys: 0, hips: 0, ridges: 25, wallTransitions: 0, stepFlashing: 0, headwallFlashing: 0, sidewallFlashing: 0, chimneyPerimeter: 0, skylightPerimeter: 0, customFlashing: 0, existingLayers: 1, stories: 1, complexity: "simple", accessDifficulty: "standard", deckingAllowance: 0, internalNotes: "" }, penetrations: { plumbingVents: 0, goosenecks: 0, bathroomExhausts: 0, dryerExhausts: 0, rangeExhausts: 0, skylights: 0, chimneys: 0, roofHatches: 0, solarPenetrations: 0, satelliteMounts: 0, customPenetrations: 0 } }
] };

function pricedSystem(index: number): RoofingSystem { const s = structuredClone(DEFAULT_ROOFING_SYSTEMS[index]); s.components.fieldShingles.rate = [120, 135, 155][index]; s.components.fieldShingles.coverage = 1; s.components.starterShingles.rate = 2; s.components.ridgeCaps.rate = 4; s.components.iceWater.rate = 1; s.components.underlayment.rate = 0.6; s.components.dripEdge.rate = 2; s.components.rakeEdge.rate = 2; s.components.valleyMetal.rate = 5; s.components.goosenecks.rate = 80; s.components.plumbingBoots.rate = 45; s.rateTraces = [
  { rateItemId: "r4", trade: "roofing", rateType: "labour", name: "4/12 pitch labour", rate: 130, unit: "square", sourceReference: null, appliedQuantity: 0, extension: 0 },
  { rateItemId: "r8", trade: "roofing", rateType: "labour", name: "8/12 pitch labour", rate: 150, unit: "square", sourceReference: null, appliedQuantity: 0, extension: 0 },
  { rateItemId: "r10", trade: "roofing", rateType: "labour", name: "10/12 pitch labour", rate: 250, unit: "square", sourceReference: null, appliedQuantity: 0, extension: 0 },
  { rateItemId: "wall", trade: "roofing", rateType: "labour", name: "wall flashing labour", rate: 12, unit: "linear foot", sourceReference: null, appliedQuantity: 0, extension: 0 },
  { rateItemId: "valley", trade: "roofing", rateType: "labour", name: "valley labour", rate: 8, unit: "linear foot", sourceReference: null, appliedQuantity: 0, extension: 0 },
  { rateItemId: "goose", trade: "roofing", rateType: "labour", name: "gooseneck labour", rate: 40, unit: "each", sourceReference: null, appliedQuantity: 0, extension: 0 },
  { rateItemId: "boot", trade: "roofing", rateType: "labour", name: "plumbing boot labour", rate: 35, unit: "each", sourceReference: null, appliedQuantity: 0, extension: 0 },
  { rateItemId: "layer", trade: "roofing", rateType: "labour", name: "additional layer labour", rate: 60, unit: "square", sourceReference: null, appliedQuantity: 0, extension: 0 },
  { rateItemId: "story", trade: "roofing", rateType: "labour", name: "additional storey surcharge", rate: 50, unit: "square", sourceReference: null, appliedQuantity: 0, extension: 0 },
  { rateItemId: "hotel", trade: "roofing", rateType: "travel", name: "hotel allowance", rate: 500, unit: "day", sourceReference: null, appliedQuantity: 0, extension: 0 }
]; return s; }

test("structure labels trim, blank labels default, and duplicate labels are allowed", () => { const copy = structuredClone(liveMeasurements); copy.structures![0].label = "   "; copy.structures!.push({ ...structuredClone(copy.structures![1]), id: "garage-2", label: "Garage" }); const structures = normalizeRoofStructures(copy); assert.equal(structures[0].label, "Main Structure"); assert.equal(structures.filter(s => s.label === "Garage").length, 2); });

test("pitch areas support repeated pitches, actual and plan area, and optional structures stay outside base total", () => { const result = calculateSystem(liveMeasurements, pricedSystem(0)); const main = result.structureTotals!.find(s => s.structureId === "main")!; const garage = result.structureTotals!.find(s => s.structureId === "garage")!; assert.equal(main.totalActualRoofArea, 2491); assert.equal(main.labourQuantityByPitch["4/12"], 20.91); assert.equal(main.labourQuantityByPitch["8/12"], 4); assert.equal(garage.totalActualRoofArea, 400); assert.equal(Math.ceil(result.system.components.fieldShingles.quantity), 28); });

test("rate engine does not apply all active rates or unit-based fallback quantities", () => { const result = calculateSystem(liveMeasurements, pricedSystem(0)); const names = result.system.rateTraces!.map(r => r.name); assert.deepEqual(names.sort(), ["4/12 pitch labour", "8/12 pitch labour", "gooseneck labour", "plumbing boot labour", "valley labour", "wall flashing labour"].sort()); assert.equal(result.system.rateTraces!.find(r => r.rateItemId === "r4")!.appliedQuantity, 20.91); assert.equal(result.system.rateTraces!.find(r => r.rateItemId === "r8")!.appliedQuantity, 4); assert.equal(result.system.rateTraces!.find(r => r.rateItemId === "wall")!.appliedQuantity, 2); assert.equal(result.system.rateTraces!.find(r => r.rateItemId === "valley")!.appliedQuantity, 36); assert.equal(result.system.rateTraces!.find(r => r.rateItemId === "goose")!.appliedQuantity, 3); assert.equal(result.system.rateTraces!.find(r => r.rateItemId === "boot")!.appliedQuantity, 1); assert.ok(result.pricingAudit!.preventedRates.includes("hotel allowance")); assert.ok(result.breakdown.total < 75000); });

test("Good Better Best traces are distinct and GST is applied once", () => { const totals = [0,1,2].map(i => calculateSystem(liveMeasurements, pricedSystem(i))); assert.notEqual(totals[0].breakdown.material, totals[1].breakdown.material); assert.notEqual(totals[1].breakdown.material, totals[2].breakdown.material); assert.equal(totals[0].breakdown.gst, Math.round((totals[0].breakdown.beforeTax * 0.05 + Number.EPSILON) * 100) / 100); });

test("automatic ventilation calculates required NFVA and warns on missing data", () => { const result = calculateSystem(liveMeasurements, pricedSystem(0)); const ventilation = result.structureTotals!.find(s => s.structureId === "main")!.ventilation!; assert.equal(ventilation.requiredTotalNfva, 1195.68); assert.ok(ventilation.exhaustQuantity! > 0); const missing = structuredClone(liveMeasurements); delete missing.structures![0].ventilation!.exhaustNfvaPerUnit; assert.ok(calculateSystem(missing, pricedSystem(0)).structureTotals![0].warnings.some(w => w.includes("Missing exhaust"))); });

test("vent type selected per Good Better Best changes automatic vent quantity", () => { const pro50 = pricedSystem(0); pro50.ventType = "pro50"; const pro75 = pricedSystem(1); pro75.ventType = "pro75"; const vmax303 = pricedSystem(2); vmax303.ventType = "vmax303"; const vmax301 = pricedSystem(0); vmax301.ventType = "vmax301"; assert.equal(calculateSystem(liveMeasurements, pro50).system.components.vents.quantity, 13); assert.equal(calculateSystem(liveMeasurements, pro75).system.components.vents.quantity, 9); assert.equal(calculateSystem(liveMeasurements, vmax303).system.components.vents.quantity, 4); assert.equal(calculateSystem(liveMeasurements, vmax301).system.components.vents.quantity, 3); const ridge = pricedSystem(0); ridge.ventType = "ridge"; assert.equal(calculateSystem(liveMeasurements, ridge).system.components.vents.quantity, 112); });

test("estimate editor does not expose shared legacy measurements or manual squares input", () => { const source = require("node:fs").readFileSync("app/admin/estimates/EstimateEditor.tsx", "utf8"); assert.doesNotMatch(source, /Shared legacy measurements/); assert.doesNotMatch(source, new RegExp("Squares<")); assert.match(source, /Measurements are captured per structure/); assert.match(source, /Auto quantity/); assert.match(source, /Material \/ component/); assert.doesNotMatch(source, /Labour \/ square/); assert.doesNotMatch(source, />Disposal</); assert.doesNotMatch(source, />Delivery</); });
