export const PROJECT_IMAGE_MIME_TYPES=["image/jpeg","image/png","image/webp"] as const;
export const PROJECT_IMAGE_MAX_BYTES=15*1024*1024;
export type ImageCategory="front_of_house"|"rear_of_house"|"roof_overview"|"roof_condition"|"roof_detail"|"roof_plan"|"siding_overview"|"siding_condition"|"siding_plan"|"elevation_plan"|"eavestrough"|"downspout"|"fascia"|"soffit"|"flashing"|"attic"|"consultant_drawing"|"specification_detail"|"other"|string;
export type ImageTransform={crop:{x:number;y:number;width:number;height:number};zoom:number;position:{x:number;y:number};rotation:number;fit:"fit"|"fill";orientation:"portrait"|"landscape"};
export type AnnotationType="arrow"|"line"|"rectangle"|"circle"|"ellipse"|"freehand"|"text"|"number"|"highlight";
export type ImageAnnotation={id:string;type:AnnotationType;x:number;y:number;width:number;height:number;start?:{x:number;y:number};end?:{x:number;y:number};rotation:number;points?:Array<{x:number;y:number}>;stroke:string;fill:string;opacity:number;lineWidth:number;lineStyle:"solid"|"dashed"|"dotted";arrowhead:"none"|"end"|"both";text?:string;fontSize:number;layerOrder:number;legendNumber?:number;linkedProposalItem?:string;visible:boolean};
export type ImageLegend={id:string;number:number;description:string;displayOrder:number;proposalStatus?:string;linkedProposalItem?:string;visible:boolean;customerFacing:boolean};
export type ProjectImageVersion={id:string;projectImageId:string;versionNumber:number;derivativeStoragePath?:string|null;transform:ImageTransform;annotations:ImageAnnotation[];legends:ImageLegend[];createdAt?:string};
export type ProposalImageInstance={id:string;projectImageId?:string|null;versionId?:string|null;storagePath?:string|null;mimeType?:string;section:"photos"|"plan";planType?:"roof_plan"|"elevation_plan"|"drainage_plan"|"fascia_soffit_plan"|"combined_exterior_plan"|"custom_plan"|"consultant_drawing"|"specification_detail";title:string;caption:string;comment:string;include:boolean;displayOrder:number;layout:"full"|"two"|"three"|"image_legend";transform:ImageTransform;annotations:ImageAnnotation[];legends:ImageLegend[];orientation:"portrait"|"landscape";customerFacing:boolean;allowPlaceholder:boolean;displayUrl?:string;warning?:string};
export const DEFAULT_IMAGE_TRANSFORM:ImageTransform={crop:{x:0,y:0,width:1,height:1},zoom:1,position:{x:.5,y:.5},rotation:0,fit:"fit",orientation:"portrait"};
export function normalize(value:number){if(!Number.isFinite(value)||value<0||value>1)throw new Error("Annotation coordinates must be normalized between 0 and 1.");return value}
export function validateAnnotation(a:ImageAnnotation){[a.x,a.y,a.width,a.height,...(a.points??[]).flatMap(p=>[p.x,p.y])].forEach(normalize);if(a.opacity<0||a.opacity>1||a.lineWidth<=0)throw new Error("Invalid annotation style.");return structuredClone(a)}
export function addAnnotation(state:ImageAnnotation[],annotation:ImageAnnotation){return[...state,validateAnnotation(annotation)].sort((a,b)=>a.layerOrder-b.layerOrder)}
export function updateAnnotation(state:ImageAnnotation[],id:string,patch:Partial<ImageAnnotation>){return state.map(a=>a.id===id?validateAnnotation({...a,...patch}):a)}
export function removeAnnotation(state:ImageAnnotation[],id:string){return state.filter(a=>a.id!==id)}
export function duplicateAnnotation(state:ImageAnnotation[],id:string,newId:string){const source=state.find(a=>a.id===id);return source?addAnnotation(state,{...structuredClone(source),id:newId,x:Math.min(1,source.x+.02),y:Math.min(1,source.y+.02),layerOrder:Math.max(0,...state.map(a=>a.layerOrder))+1}):state}
export function validateImageUpload(file:{type:string;size:number;name:string}){if(!PROJECT_IMAGE_MIME_TYPES.includes(file.type as any))throw new Error("Use a JPG, PNG, or WEBP image.");if(file.size<=0||file.size>PROJECT_IMAGE_MAX_BYTES)throw new Error("Images must be no larger than 15 MB.");return file.name.replace(/[^a-zA-Z0-9._-]/g,"_").slice(-120)||"project-image"}
export function imageDimensions(data:Buffer,type:string){if(type==="image/png"&&data.subarray(1,4).toString()==="PNG")return{width:data.readUInt32BE(16),height:data.readUInt32BE(20)};if(type==="image/webp"&&data.subarray(0,4).toString()==="RIFF"&&data.subarray(8,12).toString()==="WEBP"){const kind=data.subarray(12,16).toString();if(kind==="VP8X")return{width:1+data.readUIntLE(24,3),height:1+data.readUIntLE(27,3)};if(kind==="VP8 "&&data.subarray(23,26).toString("hex")==="9d012a")return{width:data.readUInt16LE(26)&0x3fff,height:data.readUInt16LE(28)&0x3fff};if(kind==="VP8L"&&data[20]===0x2f)return{width:1+(data[21]|(data[22]&0x3f)<<8),height:1+((data[22]>>6)|(data[23]<<2)|((data[24]&0xf)<<10))};throw new Error("Unsupported WEBP dimensions.")}if(type==="image/jpeg"&&data[0]===255&&data[1]===216){let i=2;while(i<data.length-9){if(data[i]!==255){i++;continue}const marker=data[i+1],length=data.readUInt16BE(i+2);if(marker>=192&&marker<=195)return{height:data.readUInt16BE(i+5),width:data.readUInt16BE(i+7)};i+=2+length}}throw new Error("Image contents do not match the selected MIME type.")}
export function customerImageSnapshot(instance:ProposalImageInstance){const{storagePath:_,warning:__,...safe}=structuredClone(instance);return safe}
export function unresolvedImageSlots(instances:ProposalImageInstance[]){return instances.filter(x=>x.include&&!x.projectImageId&&!x.allowPlaceholder)}
