"use client";
import {FormEvent,useMemo,useState} from "react";
const stages=["Resolving address","Fetching building insights","Fetching raster layers","Parsing DSM","Finding target building","Fitting roof planes","Tracing roof geometry","Classifying edges","Calculating measurements","Calculating price","Rendering report"];
const n=(v:any,d=1)=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{maximumFractionDigits:d}):"Unavailable";const sqft=(m:any)=>n(Number(m)*10.7639104167,0);const feet=(m:any)=>Number.isFinite(Number(m))?`${n(Number(m)*3.28084,1)} ft`:"Not confidently detectable";
export default function Lab(){const [address,setAddress]=useState(""),[lat,setLat]=useState(""),[lng,setLng]=useState(""),[busy,setBusy]=useState(false),[stage,setStage]=useState(0),[result,setResult]=useState<any>(),[error,setError]=useState("");const [roofr,setRoofr]=useState<Record<string,string>>({});
async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");setResult(null);let i=0;setStage(0);const timer=setInterval(()=>setStage(Math.min(++i,stages.length-2)),650);try{const r=await fetch("/api/admin/roof-measurement-lab",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({address,latitude:lat||undefined,longitude:lng||undefined})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Analysis failed");setStage(stages.length-1);setResult(data)}catch(x){setError(x instanceof Error?x.message:String(x))}finally{clearInterval(timer);setBusy(false)}}
const comparisons=useMemo(()=>{if(!result)return[];const ours:any={totalArea:result.areas.recommendedAreaM2*10.7639104167,mainArea:result.areas.rasterDerivedAreaM2*10.7639104167,facetCount:result.facets.length,eaves:result.lengths.eave,rakes:result.lengths.rake,ridges:result.lengths.ridge,hips:result.lengths.hip,valleys:result.lengths.valley,wallFlashing:result.lengths.wallFlashing,stepFlashing:result.lengths.stepFlashing};return Object.entries(roofr).filter(([,v])=>v!=="").map(([k,v])=>{const rv=Number(v),ov=ours[k],diff=ov==null?null:Math.abs(ov-rv),pct=diff==null||!rv?null:diff/rv*100;let status="UNAVAILABLE";if(pct!=null)status=k==="facetCount"?(diff===0?"PASS":diff===1?"REVIEW":"FAIL"):(pct<=((k==="totalArea"||k==="mainArea")?3:5)?"PASS":pct<=((k==="totalArea"||k==="mainArea")?5:10)?"REVIEW":"FAIL");return {k,ov,rv,diff,pct,status}})},[result,roofr]);
return <main className="lab"><header><p className="eyebrow">INTERNAL · EPHEMERAL · ZERO DATABASE WRITES</p><h1>Roof Measurement Lab</h1><p>Google Solar and raster research only. Results are diagnostics, not a customer quote or proof of Roofr equivalence.</p></header><form onSubmit={submit} className="controls"><label>Address<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="39 Chapala Drive SE, Calgary, AB"/></label><label>Latitude (optional)<input value={lat} onChange={e=>setLat(e.target.value)} inputMode="decimal"/></label><label>Longitude (optional)<input value={lng} onChange={e=>setLng(e.target.value)} inputMode="decimal"/></label><button disabled={busy}>{busy?"Analyzing…":"Analyze Roof"}</button></form>
{busy&&<section className="progress"><strong>{stages[stage]}</strong><ol>{stages.map((s,i)=><li className={i<stage?"done":i===stage?"active":""} key={s}>{s}</li>)}</ol></section>}{error&&<div className="error"><b>MEASUREMENT CONFIDENCE: LOW · PRICE NOT RELIABLE</b><br/>{error}</div>}
{result&&<><section className="hero"><p className="eyebrow">ROOF MEASUREMENT LAB RESULT</p><h2>{result.formattedAddress}</h2><div className="metrics"><Metric l="Recommended Main Roof Area" v={`${sqft(result.areas.recommendedAreaM2)} sqft · ${n(result.price.roofSquares)} squares`}/><Metric l="All Structures Ground Footprint" v={`${sqft(result.areas.allStructuresGroundAreaM2)} sqft`}/><Metric l="Derived facets" v={`${result.facets.length} (seed-based)`}/><Metric l="Predominant pitch" v={(result.pitchDistribution.sort((a:any,b:any)=>b.areaSqft-a.areaSqft)[0]?.pitch)||"Unavailable"}/><Metric l="Measurement confidence" v={`${result.confidence.label} · ${result.confidence.total}/100`}/><Metric l="Lab price range" v={result.confidence.label==="LOW"?"PRICE NOT RELIABLE":`$${n(result.price.low,0)} – $${n(result.price.high,0)}`}/></div></section>
<Section title="Area cross-check"><Table rows={[["Raw Google roof",`${sqft(result.areas.rawGoogleRoofAreaM2)} sqft`],["Corrected Google roof",`${sqft(result.areas.correctedGoogleRoofAreaM2)} sqft`],["Whole segmented ground",`${sqft(result.areas.rawGoogleGroundAreaM2)} sqft`],["Building ground",`${sqft(result.areas.buildingGroundAreaM2)} sqft`],["Coverage",`${n(result.areas.coverageRatio*100,2)}%`],["Correction factor",n(result.areas.correctionFactor,4)],["Sum of segments",`${sqft(result.areas.segmentRoofAreaM2)} sqft`],["Raster-derived (seed baseline)",`${sqft(result.areas.rasterDerivedAreaM2)} sqft`],["Corrected/raster variance",`${n(result.areas.agreementPercent,2)}%`]]}/></Section>
<Section title="Target building validation"><Table rows={[["Address coordinate",`${n(result.coordinates.geocoded.latitude,6)}, ${n(result.coordinates.geocoded.longitude,6)}`],["Solar building center",`${n(result.coordinates.buildingCenter.latitude,6)}, ${n(result.coordinates.buildingCenter.longitude,6)}`],["Distance",`${n(result.coordinates.distanceMeters,2)} m`],["Assessment",result.coordinates.match]]}/></Section>
<Section title="Confidence score"><Table rows={Object.entries(result.confidence.components).map(([k,v])=>[k,n(v,0)])}/><p>Plane quality combines valid fitted-mask coverage and residual: excellent ≥90% / ≤0.35m; good ≥80% / ≤0.60m; fair ≥65% / ≤1.0m. Seed-only facets score zero. Internal consistency does not prove Roofr equivalence.</p></Section>
<Section title="Structures">{result.raster.structures.map((s:any)=><article className="card" key={s.id}><b>Structure #{s.id}{s.isMain?" · MAIN":""}</b><p>Ground footprint {sqft(s.groundAreaM2)} sqft · {n(s.pixels,0)} pixels · {n(s.distanceFromCenterPixels,1)} px from building center</p><p>Roof plane and edge totals are only attributed to the main structure in this baseline.</p></article>)}</Section>
<Section title="Pitch / facet report"><table><thead><tr>{["Facet","Source","Area sqft","Squares","Pitch","Bucket","Azimuth","Fit residual"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{result.facets.map((f:any)=><tr key={f.id}><td>{f.id}</td><td>{f.source}</td><td>{n(f.areaSqft,0)}</td><td>{n(f.areaSqft/100,2)}</td><td>{n(f.pitchDegrees,1)}° · {n(f.pitchX12,2)}/12</td><td>{f.pitchBucket}/12</td><td>{n(f.azimuthDegrees,1)}°</td><td>{f.residualM??"Not fitted"}</td></tr>)}</tbody></table></Section>
<Section title="Length report"><p className="warning">{result.lengths.status}</p><Table rows={Object.entries(result.lengths).filter(([k])=>k!=="status").map(([k,v])=>[k,feet(v)])}/><p>No boundary is fabricated as flashing or another edge category.</p></Section>
<Section title="Lab-only pricing breakdown"><Table rows={[["Recommended area",`${sqft(result.areas.recommendedAreaM2)} sqft`],["Squares",n(result.price.roofSquares,2)],["Base installed rate","$580 / square"],["Base price",`$${n(result.price.basePrice,2)}`],["Facet count",n(result.price.facetCount,0)],["Facet adjustment",`${n(result.price.facetAdjustment*100,1)}%`],["Facet complexity dollars",`$${n(result.price.facetComplexityDollars,2)}`],["Total incremental pitch surcharge",`$${n(result.price.totalPitchSurcharge,2)}`],["Center",`$${n(result.price.center,2)}`],["Low / high (nearest $50)",`$${n(result.price.low,0)} / $${n(result.price.high,0)}`]]}/></Section>
<Section title="Compare to Roofr (browser memory only)"><div className="compareInputs">{["totalArea","mainArea","facetCount","eaves","rakes","ridges","hips","valleys","wallFlashing","stepFlashing"].map(k=><label key={k}>{k}<input type="number" value={roofr[k]||""} onChange={e=>setRoofr({...roofr,[k]:e.target.value})}/></label>)}</div><table><thead><tr><th>Metric</th><th>Our value</th><th>Roofr value</th><th>Difference</th><th>% error</th><th>Status</th></tr></thead><tbody>{comparisons.map((x:any)=><tr key={x.k}><td>{x.k}</td><td>{n(x.ov,2)}</td><td>{n(x.rv,2)}</td><td>{n(x.diff,2)}</td><td>{x.pct==null?"Unavailable":`${n(x.pct,2)}%`}</td><td>{x.status}</td></tr>)}</tbody></table></Section>
<details><summary>Raw Google Measurements</summary><pre>{JSON.stringify(result.raw,null,2)}</pre></details><details><summary>Raster metadata, endpoints & constants</summary><pre>{JSON.stringify({raster:result.raster,endpoints:result.endpoints,constants:result.constants},null,2)}</pre></details></>}
</main>}
function Metric({l,v}:{l:string,v:string}){return <div><span>{l}</span><strong>{v}</strong></div>}function Section({title,children}:{title:string,children:any}){return <section><h2>{title}</h2>{children}</section>}function Table({rows}:{rows:any[][]}){return <table><tbody>{rows.map(([a,b])=><tr key={a}><th>{a}</th><td>{b}</td></tr>)}</tbody></table>}
