import type { DocumentBlock, ProposalDocument } from "./document";
export const PAGE={portrait:{width:612,height:792},landscape:{width:792,height:612},margin:{top:72,bottom:58,left:48,right:48},headerHeight:24,footerHeight:24,font:{body:10,small:8,heading:15,title:25},lineHeight:{body:14,heading:20,title:31}} as const;
export type LayoutLine={text:string;x:number;y:number;fontSize:number;bold:boolean};
export type LayoutImage={id:string;x:number;y:number;width:number;height:number;transform:any;annotations:any[]};
export type LayoutPage={orientation:"portrait"|"landscape";cover:boolean;sectionTitle:string;lines:LayoutLine[];images:LayoutImage[]};
const textWidth=(text:string,size:number)=>text.length*size*.52;
export function wrapText(text:string,maxWidth:number,fontSize:number=PAGE.font.body){const words=String(text).split(/\s+/).filter(Boolean),out:string[]=[];let line="";for(const word of words){if(textWidth(word,fontSize)>maxWidth){if(line)out.push(line);let part="";for(const ch of word){if(textWidth(part+ch,fontSize)>maxWidth){out.push(part);part=ch}else part+=ch}line=part;continue}const next=line?`${line} ${word}`:word;if(textWidth(next,fontSize)>maxWidth){if(line)out.push(line);line=word}else line=next}if(line)out.push(line);return out.length?out:[""]}
function blockLines(block:DocumentBlock,width:number){const rows:Omit<LayoutLine,"x"|"y">[]=[];if(block.title)for(const line of wrapText(block.title,width,PAGE.font.heading))rows.push({text:line,fontSize:PAGE.font.heading,bold:true});if(block.badge)rows.push({text:block.badge,fontSize:PAGE.font.small,bold:true});for(const source of block.lines){if(block.kind==="price"&&source.includes("|")){const[a,b]=source.split("|");rows.push({text:`${a}${" ".repeat(Math.max(2,62-a.length-b.length))}${b}`,fontSize:source.startsWith("Total|")?12:PAGE.font.body,bold:source.startsWith("Total|")});continue}for(const line of wrapText(source,width,PAGE.font.body))rows.push({text:line,fontSize:PAGE.font.body,bold:false})}if(block.price!==undefined)rows.push({text:new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD"}).format(block.price),fontSize:12,bold:true});return rows}
export function paginateDocument(doc:ProposalDocument):LayoutPage[]{const pages:LayoutPage[]=[];let page:LayoutPage|undefined,y=0;const newPage=(title:string,orientation:"portrait"|"landscape"="portrait",cover=false)=>{page={orientation,cover,sectionTitle:title,lines:[],images:[]};pages.push(page);const dims=PAGE[orientation];y=dims.height-PAGE.margin.top-(cover?0:PAGE.headerHeight)};for(const section of doc.sections){const cover=section.type==="cover";if(!page||section.pageBreakBefore||cover||page.cover)newPage(section.title,section.orientation,cover);const dims=PAGE[section.orientation],width=dims.width-PAGE.margin.left-PAGE.margin.right,bottom=PAGE.margin.bottom+PAGE.footerHeight;for(const block of section.blocks){if(block.image){const image=block.image,orientation=image.orientation??section.orientation,max=image.section==="plan"||image.layout==="full"||image.layout==="image_legend"?1:image.layout==="two"?2:3;if(page!.cover||page!.orientation!==orientation||page!.images.length>=max)newPage(section.title,orientation,false);const index=page!.images.length,dims=PAGE[orientation],imageHeight=max===1?(orientation==="landscape"?330:430):max===2?220:150,imageY=max===1?PAGE.margin.bottom+PAGE.footerHeight+130:max===2?[410,150][index]:[500,310,120][index];page!.images.push({id:image.id,x:PAGE.margin.left,y:imageY,width:dims.width-PAGE.margin.left-PAGE.margin.right,height:imageHeight,transform:image.transform,annotations:image.annotations});y=imageY-8}const rows=blockLines(block,width),height=rows.reduce((n,r)=>n+(r.fontSize>=15?PAGE.lineHeight.heading:PAGE.lineHeight.body),0)+10;if((block.pageBreakBefore||block.keepTogether&&height<=y-bottom&&y-height<bottom)&&page!.lines.length)newPage(`${section.title} (continued)`,section.orientation,false);let first=true;for(const row of rows){const lineHeight=row.fontSize>=15?PAGE.lineHeight.heading:PAGE.lineHeight.body;if(y-lineHeight<bottom){newPage(`${section.title} (continued)`,section.orientation,false);if(first&&block.title){for(const h of wrapText(`${block.title} (continued)`,width,PAGE.font.heading)){page!.lines.push({text:h,x:PAGE.margin.left,y,fontSize:PAGE.font.heading,bold:true});y-=PAGE.lineHeight.heading}}}page!.lines.push({...row,x:PAGE.margin.left,y});y-=lineHeight;first=false}y-=10}}return pages}
