import { createHash } from "node:crypto";
import { inflateSync, deflateSync } from "node:zlib";
import { buildProposalDocument, type SignedDocumentDetails } from "./document";
import { PAGE, paginateDocument, type LayoutPage } from "./pagination";
import { customerFacingProposal, type ProposalDraft } from "./domain";

export type PdfAssets={cover?:Buffer;signature?:Buffer};
export const PDF_RENDERER_VERSION="trusted-paginated-v1";
const pdfText=(value:string)=>value.normalize("NFKD").replace(/[^\x20-\x7e]/g," ").replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)");
const short=(value:string,max=72)=>value.length<=max?value:`${value.slice(0,max-1)}…`;
export function proposalPdfInput(p:ProposalDraft){return customerFacingProposal(p)}
export function proposalDocumentInput(p:ProposalDraft,signed?:SignedDocumentDetails){return buildProposalDocument(p,signed)}
export function proposalPdfLayout(p:ProposalDraft,signed?:SignedDocumentDetails){const document=proposalDocumentInput(p,signed);return{document,pages:paginateDocument(document)}}

function pageCommands(page:LayoutPage,index:number,total:number,doc:ReturnType<typeof buildProposalDocument>,coverImage:{width:number;height:number}|null=null,signatureImage:{width:number;height:number}|null=null){const dims=PAGE[page.orientation],commands:string[]=[];if(page.cover){commands.push("0.08 0.16 0.34 rg",`48 ${dims.height-65} 516 34 re f`,`1 1 1 rg BT /F2 20 Tf 60 ${dims.height-55} Td (TRUSTED ROOFING & EXTERIORS) Tj ET`,"0.92 0.94 0.97 rg","90 280 432 245 re f","0.25 0.3 0.4 rg BT /F1 11 Tf 185 395 Td (Front-of-house image securely loaded when available) Tj ET");if(coverImage){const scale=Math.max(432/coverImage.width,245/coverImage.height)*Math.max(1,doc.cover.zoom),w=coverImage.width*scale,h=coverImage.height*scale,x=90+(432-w)*(doc.cover.crop.x/100),y=280+(245-h)*(1-doc.cover.crop.y/100);commands.push(`q 90 280 432 245 re W n ${w} 0 0 ${h} ${x} ${y} cm /Im1 Do Q`);}if(doc.cover.attribution)commands.push(`BT /F1 8 Tf 90 265 Td (${pdfText(doc.cover.attribution)}) Tj ET`)}else{commands.push("0.08 0.16 0.34 rg",`BT /F2 9 Tf 48 ${dims.height-42} Td (TRUSTED ROOFING & EXTERIORS) Tj ET`,`BT /F1 8 Tf 240 ${dims.height-42} Td (${pdfText(doc.proposalNumber)} | ${pdfText(short(doc.propertyAddress,52))}) Tj ET`)}for(const line of page.lines){commands.push(`0.10 0.12 0.18 rg BT /F${line.bold?2:1} ${line.fontSize} Tf ${line.x} ${line.y} Td (${pdfText(line.text)}) Tj ET`)}if(signatureImage){const scale=Math.min(220/signatureImage.width,70/signatureImage.height),w=signatureImage.width*scale,h=signatureImage.height*scale;commands.push(`q ${w} 0 0 ${h} 48 ${82+(70-h)/2} cm /Sig1 Do Q`);}const footer=page.cover?`trustedroofingcalgary.com | ${doc.proposalNumber}`:`Page ${index+1} of ${total} | trustedroofingcalgary.com | Revision ${doc.revisionNumber}${doc.kind==="accepted"?" | ACCEPTED COPY":" | Customer proposal"}`;commands.push(`0.3 0.34 0.4 rg BT /F1 8 Tf 48 30 Td (${pdfText(footer)}) Tj ET`);return commands.join("\n")}
function imageInfo(data:Buffer){if(data[0]===0xff&&data[1]===0xd8){let i=2;while(i<data.length-9){if(data[i]!==0xff){i++;continue}const marker=data[i+1],length=data.readUInt16BE(i+2);if(marker>=0xc0&&marker<=0xc3)return{height:data.readUInt16BE(i+5),width:data.readUInt16BE(i+7),data,filter:"/DCTDecode",decode:""};i+=2+length}}if(data.subarray(1,4).toString()==="PNG"){const width=data.readUInt32BE(16),height=data.readUInt32BE(20),depth=data[24],colour=data[25];if(depth!==8||![2,6].includes(colour))return null;let offset=8,idat:Buffer[]=[];while(offset<data.length){const length=data.readUInt32BE(offset),type=data.subarray(offset+4,offset+8).toString();if(type==="IDAT")idat.push(data.subarray(offset+8,offset+8+length));offset+=length+12}const bpp=colour===6?4:3,rowBytes=width*bpp,raw=inflateSync(Buffer.concat(idat)),rgb=Buffer.alloc((width*3+1)*height),previous=Buffer.alloc(rowBytes);let source=0,target=0;for(let y=0;y<height;y++){const filter=raw[source++],row=Buffer.from(raw.subarray(source,source+rowBytes));source+=rowBytes;for(let x=0;x<rowBytes;x++){const left=x>=bpp?row[x-bpp]:0,up=previous[x],upperLeft=x>=bpp?previous[x-bpp]:0;if(filter===1)row[x]=(row[x]+left)&255;else if(filter===2)row[x]=(row[x]+up)&255;else if(filter===3)row[x]=(row[x]+Math.floor((left+up)/2))&255;else if(filter===4){const p=left+up-upperLeft,pa=Math.abs(p-left),pb=Math.abs(p-up),pc=Math.abs(p-upperLeft);row[x]=(row[x]+(pa<=pb&&pa<=pc?left:pb<=pc?up:upperLeft))&255}}rgb[target++]=0;for(let x=0;x<width;x++){rgb[target++]=row[x*bpp];rgb[target++]=row[x*bpp+1];rgb[target++]=row[x*bpp+2]}row.copy(previous)}return{width,height,data:deflateSync(rgb),filter:"/FlateDecode",decode:`/DecodeParms << /Predictor 15 /Colors 3 /BitsPerComponent 8 /Columns ${width} >>`}}return null}
function writePdf(pages:LayoutPage[],doc:ReturnType<typeof buildProposalDocument>,assets?:PdfAssets){const image=assets?.cover?imageInfo(assets.cover):null,signature=assets?.signature?imageInfo(assets.signature):null;const objects:string[]=["<< /Type /Catalog /Pages 2 0 R >>","", "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"],pageRefs:number[]=[];for(let i=0;i<pages.length;i++){const pageNo=objects.length+1,contentNo=pageNo+1,page=pages[i],dims=PAGE[page.orientation],stream=pageCommands(page,i,pages.length,doc,image&&i===0?image:null,signature&&i===pages.length-1?signature:null);pageRefs.push(pageNo);objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${dims.width} ${dims.height}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >>${image&&i===0?` /XObject << /Im1 ${"IMAGE_REF"} 0 R >>`:signature&&i===pages.length-1?` /XObject << /Sig1 ${"SIGNATURE_REF"} 0 R >>`:""} >> /Contents ${contentNo} 0 R >>`,`<< /Length ${Buffer.byteLength(stream,"latin1")} >>\nstream\n${stream}\nendstream`)}if(image&&assets?.cover)objects.push(`<< /Type /XObject /Subtype /Image /Width ${image.width} /Height ${image.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter ${image.filter} ${image.decode} /Length ${image.data.length} >>\nstream\n${image.data.toString("binary")}\nendstream`);const imageRef=image?objects.length:0;if(signature&&assets?.signature)objects.push(`<< /Type /XObject /Subtype /Image /Width ${signature.width} /Height ${signature.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter ${signature.filter} ${signature.decode} /Length ${signature.data.length} >>\nstream\n${signature.data.toString("binary")}\nendstream`);const signatureRef=signature?objects.length:0;for(let i=0;i<objects.length;i++)objects[i]=objects[i].replace("IMAGE_REF",String(imageRef)).replace("SIGNATURE_REF",String(signatureRef));objects[1]=`<< /Type /Pages /Kids [${pageRefs.map(n=>`${n} 0 R`).join(" ")}] /Count ${pages.length} >>`;let pdf="%PDF-1.4\n%Trusted\n",offsets=[0];objects.forEach((object,index)=>{offsets.push(Buffer.byteLength(pdf,"latin1"));pdf+=`${index+1} 0 obj\n${object}\nendobj\n`});const xref=Buffer.byteLength(pdf,"latin1");pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>`${String(n).padStart(10,"0")} 00000 n `).join("\n")}\ntrailer << /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(pdf,"latin1")}
export function generateProposalPdfResult(p:ProposalDraft,signed?:SignedDocumentDetails,assets?:PdfAssets){const{document,pages}=proposalPdfLayout(p,signed);if(!pages.length)throw new Error("Proposal PDF contains no renderable pages.");const buffer=writePdf(pages,document,assets),documentHash=createHash("sha256").update(buffer).digest("hex");return{buffer,pageCount:pages.length,documentHash,rendererVersion:PDF_RENDERER_VERSION,document,pages}}
export function generateProposalPdf(p:ProposalDraft,signed?:SignedDocumentDetails,assets?:PdfAssets){return generateProposalPdfResult(p,signed,assets).buffer}
export async function loadPrivateCoverForPdf(p:ProposalDraft,db:any){if(p.coverImage?.source==="upload"&&p.coverImage.storagePath){const{data,error}=await db.storage.from(process.env.PROPOSAL_ASSETS_BUCKET||"proposal-assets").download(p.coverImage.storagePath);if(error)return null;return Buffer.from(await data.arrayBuffer())}if(p.coverImage?.source==="street_view"&&p.coverImage.streetViewUrl){const url=new URL(p.coverImage.streetViewUrl);if(url.protocol!=="https:"||url.hostname!=="maps.googleapis.com")return null;const response=await fetch(url,{cache:"no-store",redirect:"error"});if(!response.ok||!response.headers.get("content-type")?.startsWith("image/jpeg"))return null;const bytes=await response.arrayBuffer();if(bytes.byteLength>15_728_640)return null;return Buffer.from(bytes)}return null}
