import { getServiceClient } from "@/lib/db";
import { getEstimateDraft } from "@/lib/roofing-estimates/repository";
import { createProposalFromEstimate,type ProposalDraft } from "./domain";
import { calculateSystem } from "@/lib/roofing-estimates/pricing";
const mock=new Map<string,ProposalDraft>();
export async function listProposals():Promise<ProposalDraft[]>{const db=getServiceClient();if(!db)return[...mock.values()];const{data,error}=await db.from("proposals").select("*").order("updated_at",{ascending:false});if(error)throw error;return(data??[]).map(fromRow)}
export async function createProposal(estimateId:string,actor:string){const estimate=await getEstimateDraft(estimateId);if(!estimate)throw new Error("Estimate not found.");const db=getServiceClient();if(db){const{data,error}=await db.from("estimate_option_results").select("tier,calculated_price,final_price").eq("estimate_id",estimateId);if(error)throw error;estimate.options=estimate.systems.map(system=>{const base=calculateSystem(estimate.measurements,system),row=(data??[]).find(r=>r.tier===system.tier);return{...base,calculatedPrice:Number(row?.calculated_price??0),finalPrice:Number(row?.final_price??0)}})}let sequence=Date.now().toString().slice(-6);if(db){const{count}=await db.from("proposals").select("id",{count:"exact",head:true});sequence=String((count??0)+1).padStart(5,"0")}const draft=createProposalFromEstimate(estimate,{proposalNumber:`TR-${new Date().getUTCFullYear()}-${sequence}`,actor});if(!db){draft.id=crypto.randomUUID();draft.createdAt=draft.updatedAt=new Date().toISOString();mock.set(draft.id,draft);return draft}const{data,error}=await db.from("proposals").insert(toRow(draft,actor)).select("*").single();if(error)throw error;const saved=fromRow(data);await saveChildren(db,saved);return saved}
export async function getProposal(id:string):Promise<ProposalDraft|null>{const db=getServiceClient();if(!db)return mock.get(id)??null;const{data,error}=await db.from("proposals").select("*").eq("id",id).single();if(error){if(error.code==="PGRST116")return null;throw error}return fromRow(data)}
export async function saveProposal(draft:ProposalDraft,actor:string){if(!draft.id)throw new Error("Saved proposal ID required.");const id=draft.id;const clean=structuredClone(draft);clean.updatedAt=new Date().toISOString();const db=getServiceClient();if(!db){const current=mock.get(id);if(current&&current.status!=="draft")throw new Error("Sent and accepted revisions are immutable.");mock.set(id,clean);return clean}const{data:current,error:currentError}=await db.from("proposals").select("status").eq("id",id).single();if(currentError)throw currentError;if(current.status!=="draft")throw new Error("Sent and accepted revisions are immutable.");const{data,error}=await db.from("proposals").update(toRow(clean,actor)).eq("id",id).select("*").single();if(error)throw error;const saved=fromRow(data);await saveChildren(db,saved);return saved}
async function saveChildren(db:any,p:ProposalDraft){await db.from("proposal_sections").delete().eq("proposal_id",p.id);if(p.sections.length){const{error}=await db.from("proposal_sections").insert(p.sections.map(s=>({proposal_id:p.id,section_type:s.type,title:s.title,enabled:s.enabled,display_order:s.displayOrder,content:s.content})));if(error)throw error}}
function toRow(p:ProposalDraft,actor:string){return{id:p.id,proposal_number:p.proposalNumber,estimate_id:p.estimateId,estimate_type:p.estimateType,revision_number:p.revisionNumber,status:p.status,customer_snapshot:p.customer,property_snapshot:p.property,estimate_snapshot:p.measurements,roofing_options_snapshot:p.options,soft_metal_scopes_snapshot:p.softMetalScopes,sections_snapshot:p.sections,subtotal:p.subtotal,gst:p.gst,total:p.total,expiry_date:p.expiryDate,proposal_date:p.proposalDate,estimator_name:p.estimatorName,cover_image_snapshot:p.coverImage,requires_pricing_configuration:p.requiresPricingConfiguration,created_by:actor,updated_by:actor,updated_at:new Date().toISOString()}}
function fromRow(r:any):ProposalDraft{return{id:r.id,proposalNumber:r.proposal_number,estimateId:r.estimate_id,estimateType:r.estimate_type??"roofing",revisionNumber:r.revision_number,status:r.status,customer:r.customer_snapshot,property:r.property_snapshot,measurements:r.estimate_snapshot,options:r.roofing_options_snapshot??[],softMetalScopes:r.soft_metal_scopes_snapshot??[],sections:r.sections_snapshot??[],subtotal:Number(r.subtotal),gst:Number(r.gst),total:Number(r.total),expiryDate:r.expiry_date,proposalDate:r.proposal_date,estimatorName:r.estimator_name,coverImage:r.cover_image_snapshot,requiresPricingConfiguration:r.requires_pricing_configuration,createdAt:r.created_at,updatedAt:r.updated_at}}
