#!/usr/bin/env python3
"""Generate the estimator catalogue directly from Mega's R Data worksheet."""
from pathlib import Path
import json, re, sys, zipfile
import xml.etree.ElementTree as ET
ROOT=Path(__file__).resolve().parents[2]
WORKBOOK=ROOT/'Mega Roofing - blank spreadsheet.xlsm'
OUTPUT=ROOT/'trustedroofing-site/lib/mega-estimator/product-catalog.ts'
REPORT=ROOT/'trustedroofing-site/tests/fixtures/mega-dropdown-reconciliation.json'
NS={'m':'http://schemas.openxmlformats.org/spreadsheetml/2006/main','r':'http://schemas.openxmlformats.org/officeDocument/2006/relationships'}
RANGES={
  12:('roofing','F','G','H',2,79,'bundle'),13:('standard starter','K','L','M',2,39,'bundle'),
  15:('specialty eave','K','L','M',40,49,'bundle'),16:('specialty rake','K','L','M',50,59,'bundle'),
  17:('specialty valley','K','L','M',60,79,'bundle'),14:('hip / ridge','O','P','Q',2,39,'bundle'),
  20:('drip edge','O','P','Q',40,49,'piece'),21:('rake edge','O','P','Q',50,59,'piece'),
  22:('valley flashing','O','P','Q',60,69,'piece'),18:('ice & water','S','T','U',2,39,'roll'),
  19:('underlayment','S','T','U',40,79,'roll'),27:('roof ventilation','K','L','M',80,211,'each'),
  28:('roof ventilation','K','L','M',80,211,'each'),
}

def load_cells(z,path,shared):
 root=ET.fromstring(z.read(path));out={}
 for c in root.findall('.//m:c',NS):
  ref=c.attrib['r'];v=c.find('m:v',NS)
  if v is None:continue
  value=v.text
  if c.attrib.get('t')=='s':value=shared[int(value)]
  elif value is not None:
   try:value=float(value);value=int(value) if value.is_integer() else value
   except ValueError:pass
  out[ref]=value
 return out

def manufacturer(name):
 # Manufacturer is not a separate R Data field. Populate only unambiguous brands.
 brands=['GAF','IKO','Malarkey','Euroshield','CertainTeed','BP','OC','Resisto','RhinoRoof','TriBuilt','Titanium','Duraflo','VMAX','Lomanco']
 low=name.lower()
 return next((b for b in brands if low.startswith(b.lower())),None)

with zipfile.ZipFile(WORKBOOK) as z:
 shared=[]
 if 'xl/sharedStrings.xml' in z.namelist():
  root=ET.fromstring(z.read('xl/sharedStrings.xml'))
  for si in root.findall('m:si',NS):shared.append(''.join(t.text or '' for t in si.findall('.//m:t',NS)))
 cells=load_cells(z,'xl/worksheets/sheet1.xml',shared)
 estimate=load_cells(z,'xl/worksheets/sheet3.xml',shared)
 catalog={};audit=[]
 for row,(category,ncol,ccol,pcol,start,end,unit) in RANGES.items():
  products=[]
  for n in range(start,end+1):
   raw=cells.get(f'{ncol}{n}')
   if not isinstance(raw,str) or not raw.strip():continue
   name=raw.strip();coverage=cells.get(f'{ccol}{n}');price=cells.get(f'{pcol}{n}')
   coverage=coverage if isinstance(coverage,(int,float)) and coverage>0 else None
   price=price if isinstance(price,(int,float)) and price>=0 else None
   product={'name':name,'category':category,'manufacturer':manufacturer(name),'coverage':coverage,'coverageUnit':f'source / {unit}' if coverage else None,'price':price,'priceUnit':unit,'bundlesPerSquare':coverage if row==12 else None,'compatibleRow':row,'active':not name.lower().startswith('select material'),'quoteRequired':price is None,'sourceReference':f"R Data!{ncol}{n}:{pcol}{n}"}
   products.append(product)
  catalog[row]=products
  audit.append({'workbookRow':row,'materialType':category,'workbookRange':f'R Data!{ncol}{start}:{ncol}{end}','workbookDropdownCount':len(products),'trustedDropdownCount':len(products),'missingInTrusted':[],'extraInTrusted':[]})
 # Options A/B/C select cells in the blank B 1 template.
 preset_cols={'good':'C','better':'X','best':'AF'};presets={key:{} for key in preset_cols}
 for key,col in preset_cols.items():
  for row,products in catalog.items():
   selected=estimate.get(f'{col}{row}')
   match=next((p for p in products if p['name']==selected),None)
   if match:presets[key][row]=match
 # Empty preset cells inherit the mapped Good accessory, never the catalogue's first arbitrary entry.
 for key in ('better','best'):
  for row,product in presets['good'].items():presets[key].setdefault(row,product)

def ts(value):return json.dumps(value,ensure_ascii=False,separators=(',',':')).replace('null','null')
OUTPUT.write_text('// Generated by scripts/extract-mega-product-catalog.py from Mega Roofing - blank spreadsheet.xlsm.\n'
 'export type CatalogProduct={name:string;category:string;manufacturer:string|null;coverage:number|null;coverageUnit:string|null;price:number|null;priceUnit:string;bundlesPerSquare:number|null;compatibleRow:number;active:boolean;quoteRequired:boolean;sourceReference:string};\n'
 f'export const MATERIAL_PRODUCTS:Record<number,CatalogProduct[]>={ts(catalog)};\n'
 f'export const ASPHALT_PRESETS={ts(presets)} as const;\n')
REPORT.write_text(json.dumps({'workbook':WORKBOOK.name,'rows':audit},indent=2)+'\n')
print(f'Wrote {OUTPUT.relative_to(ROOT)} and {REPORT.relative_to(ROOT)}')
