import Link from "next/link";
import QuoteArchiveHashHandler from "@/components/QuoteArchiveHashHandler";
import QuoteCard from "@/components/QuoteCard";
import CtaBand from "@/components/ui/CtaBand";
import PageContainer from "@/components/ui/PageContainer";
import PageHero from "@/components/ui/PageHero";
import { buildMetadata, canonicalUrl } from "@/lib/seo";
import { getAllQuoteCards, getQuoteArchiveAggregates } from "@/lib/seo-engine";

export const metadata = buildMetadata({
  title: "Calgary quote archive",
  description: "Every recent instant quote signal published across Calgary neighborhoods, materials, and exterior project scopes.",
  path: "/quotes"
});

export const dynamic = "force-dynamic";

function buildArchiveSchema(cards: Awaited<ReturnType<typeof getAllQuoteCards>>) {
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: "Trusted Roofing Calgary Quote Archive",
    url: canonicalUrl("/quotes"),
    description:
      "A crawlable archive of recent roofing, siding, and eavestrough quote signals generated by the Trusted Roofing instant estimator.",
    mainEntity: {
      "@type": "ItemList",
      itemListOrder: "https://schema.org/ItemListOrderDescending",
      numberOfItems: cards.length,
      itemListElement: cards.slice(0, 100).map((card, index) => ({
        "@type": "ListItem",
        position: index + 1,
        url: `${canonicalUrl("/quotes")}#${card.slug}`,
        name: card.title
      }))
    }
  };
}

function renderAggregateSection(
  title: string,
  items: Array<{ key: string; title: string; quoteCount: number; averageLow: number | null; averageHigh: number | null }>
) {
  return (
    <div style={{ marginTop: 28 }}>
      <h2 className="homev3-title" style={{ fontSize: "2rem" }}>{title}</h2>
      <div className="quote-card-grid" style={{ marginTop: 18 }}>
        {items.map((item) => (
          <article key={item.key} className="ui-card quote-aggregate-card">
            <h3>{item.title}</h3>
            <p className="homev3-copy">
              {item.quoteCount.toLocaleString()} quote signal{item.quoteCount === 1 ? "" : "s"} · recent modeled range
            </p>
            <p className="quote-aggregate-card__range">
              {item.averageLow ? `$${item.averageLow.toLocaleString()}` : "N/A"} - {item.averageHigh ? `$${item.averageHigh.toLocaleString()}` : "N/A"}
            </p>
          </article>
        ))}
      </div>
    </div>
  );
}

export default async function QuotesArchivePage() {
  const [cards, aggregates] = await Promise.all([
    getAllQuoteCards(),
    getQuoteArchiveAggregates()
  ]);

  const schema = buildArchiveSchema(cards);
  const lastUpdated = cards[0]?.queriedAt
    ? new Date(cards[0].queriedAt).toLocaleDateString("en-CA", {
      year: "numeric",
      month: "long",
      day: "numeric"
    })
    : null;

  return (
    <>
      <QuoteArchiveHashHandler />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
      <PageHero
        eyebrow="Quote archive"
        title="Every recent quote signal in one place"
        description="A crawlable archive of roofing, siding, Hardie, and eavestrough estimate signals generated from live address-level modeled outputs."
      />

      <section className="ui-page-section">
        <PageContainer>
          <div className="quote-card-grid">
            <article className="ui-card">
              <h2>Total quote signals</h2>
              <p className="homev3-copy">{cards.length.toLocaleString()} recent address-level modeled estimate signals are available on this page.</p>
            </article>
            <article className="ui-card">
              <h2>Cities covered</h2>
              <p className="homev3-copy">{aggregates.cities.length.toLocaleString()} live city-level groupings are currently represented in the quote archive.</p>
            </article>
            <article className="ui-card">
              <h2>Latest update</h2>
              <p className="homev3-copy">{lastUpdated ?? "Live updates appear here as new quotes are generated."}</p>
            </article>
          </div>

          {renderAggregateSection("City level", aggregates.cities.slice(0, 12))}
          {renderAggregateSection("City + quadrant level", aggregates.cityQuadrants.slice(0, 12))}
          {renderAggregateSection("Neighborhood level", aggregates.neighborhoods.slice(0, 12))}

          <div style={{ marginTop: 28 }}>
            <h2 className="homev3-title" style={{ fontSize: "2rem" }}>All published quote cards</h2>
            <p className="homev3-copy" style={{ marginTop: 10 }}>
              This archive keeps every quote card in one crawlable location while the instant estimator continues to live at <Link href="/quote">/quote</Link>.
            </p>
            <div className="quote-card-grid" style={{ marginTop: 18 }}>
              {cards.map((card) => (
                <div key={card.slug} id={card.slug} className="quote-card-anchor">
                  <QuoteCard quote={card} href={null} variant="full" />
                </div>
              ))}
            </div>
          </div>
        </PageContainer>
      </section>

      <CtaBand
        title="Need your own instant price range?"
        body="Use the anonymous estimator to generate a new local quote, then browse the archive to compare nearby activity."
      />
    </>
  );
}
