import Link from "next/link";
import QuoteCard from "@/components/QuoteCard";
import CtaBand from "@/components/ui/CtaBand";
import PageContainer from "@/components/ui/PageContainer";
import PageHero from "@/components/ui/PageHero";
import { buildMetadata, canonicalUrl } from "@/lib/seo";
import { getAllQuoteCards, getAllQuoteNeighborhoods } from "@/lib/seo-engine";

export const metadata = buildMetadata({
  title: "Calgary quote archive",
  description: "Every recent instant quote signal published across Calgary neighborhoods, materials, and exterior project scopes.",
  path: "/quotes"
});

function buildArchiveSchema(cards: Awaited<ReturnType<typeof getAllQuoteCards>>) {
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: "Trusted Roofing Calgary Quote Archive",
    url: canonicalUrl("/quotes"),
    description:
      "A crawlable archive of recent Calgary roofing, siding, and eavestrough quote signals generated by the Trusted Roofing instant estimator.",
    mainEntity: {
      "@type": "ItemList",
      itemListOrder: "https://schema.org/ItemListOrderDescending",
      numberOfItems: cards.length,
      itemListElement: cards.slice(0, 100).map((card, index) => ({
        "@type": "ListItem",
        position: index + 1,
        url: `${canonicalUrl("/quotes")}#quote-${card.id}`,
        name: `${card.material} quote in ${card.neighborhood}, Calgary`
      }))
    }
  };
}

export default async function QuotesArchivePage() {
  const [areas, cards] = await Promise.all([
    getAllQuoteNeighborhoods(),
    getAllQuoteCards()
  ]);

  const schema = buildArchiveSchema(cards);
  const lastUpdated = cards[0]?.queriedAt
    ? new Date(cards[0].queriedAt).toLocaleDateString("en-CA", {
      year: "numeric",
      month: "long",
      day: "numeric"
    })
    : null;

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
      <PageHero
        eyebrow="Quote archive"
        title="Every recent Calgary quote signal in one place"
        description="A crawlable archive of roofing, siding, Hardie, and eavestrough estimate activity grouped by neighborhood and updated from the instant estimator feed."
      />

      <section className="ui-page-section">
        <PageContainer>
          <div className="quote-card-grid">
            <article className="ui-card">
              <h2>Total quote signals</h2>
              <p className="homev3-copy">{cards.length.toLocaleString()} recent quote records are available on this page.</p>
            </article>
            <article className="ui-card">
              <h2>Neighborhoods covered</h2>
              <p className="homev3-copy">{areas.length.toLocaleString()} Calgary neighborhoods currently have published quote activity.</p>
            </article>
            <article className="ui-card">
              <h2>Latest update</h2>
              <p className="homev3-copy">{lastUpdated ?? "Live updates available as new quotes are generated."}</p>
            </article>
          </div>

          <div style={{ marginTop: 28 }}>
            <h2 className="homev3-title" style={{ fontSize: "2rem" }}>Top quote neighborhoods</h2>
            <div className="quote-card-grid" style={{ marginTop: 18 }}>
              {areas.slice(0, 12).map((area) => (
                <article key={area.slug} className="ui-card">
                  <h3>{area.neighborhood}</h3>
                  <p className="homev3-copy">
                    {area.quoteCount.toLocaleString()} quotes · average range {area.averageLow ? `$${area.averageLow.toLocaleString()}` : "N/A"} - {area.averageHigh ? `$${area.averageHigh.toLocaleString()}` : "N/A"}
                  </p>
                </article>
              ))}
            </div>
          </div>

          <div style={{ marginTop: 28 }}>
            <h2 className="homev3-title" style={{ fontSize: "2rem" }}>All published quote cards</h2>
            <p className="homev3-copy" style={{ marginTop: 10 }}>
              This archive keeps every quote card in one crawlable location while the instant estimator continues to live at <Link href="/quote">/quote</Link>.
            </p>
            <div className="quote-card-grid" style={{ marginTop: 18 }}>
              {cards.map((card) => (
                <div key={card.id} id={`quote-${card.id}`}>
                  <QuoteCard
                    quote={card}
                    href={`/service-areas/${card.slug}`}
                    ctaLabel={`Explore ${card.neighborhood}`}
                  />
                </div>
              ))}
            </div>
          </div>
        </PageContainer>
      </section>

      <CtaBand
        title="Need your own instant price range?"
        body="Use the anonymous estimator to generate a new Calgary quote, then browse the archive to compare nearby activity."
      />
    </>
  );
}
