import Link from "next/link";
import QuoteArchiveHashHandler from "@/components/QuoteArchiveHashHandler";
import QuoteCard from "@/components/QuoteCard";
import CtaBand from "@/components/ui/CtaBand";
import PageContainer from "@/components/ui/PageContainer";
import PageHero from "@/components/ui/PageHero";
import { buildMetadata, canonicalUrl } from "@/lib/seo";
import { getQuoteArchiveByMaterial } from "@/lib/seo-engine";

export const metadata = buildMetadata({
  title: "Calgary quote archive",
  description: "Every recent instant quote signal published across Calgary neighborhoods, materials, and exterior project scopes.",
  path: "/quotes"
});

export const dynamic = "force-dynamic";

function buildArchiveSchema(cards: Awaited<ReturnType<typeof getQuoteArchiveByMaterial>>[number]["cards"]) {
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: "Trusted Roofing Calgary Quote Archive",
    url: canonicalUrl("/quotes"),
    description:
      "A crawlable archive of recent roofing, siding, and eavestrough quote signals generated by the Trusted Roofing instant estimator.",
    mainEntity: {
      "@type": "ItemList",
      itemListOrder: "https://schema.org/ItemListOrderDescending",
      numberOfItems: cards.length,
      itemListElement: cards.slice(0, 100).map((card, index) => ({
        "@type": "ListItem",
        position: index + 1,
        url: `${canonicalUrl("/quotes")}#${card.slug}`,
        name: card.title
      }))
    }
  };
}

function renderAggregateSection(
  title: string,
  items: Array<{ key: string; title: string; quoteCount: number; averageLow: number | null; averageHigh: number | null }>
) {
  if (items.length === 0) return null;

  return (
    <div style={{ marginTop: 22 }}>
      <h3 className="homev3-title" style={{ fontSize: "1.5rem" }}>{title}</h3>
      <div className="quote-card-grid" style={{ marginTop: 16 }}>
        {items.map((item) => (
          <article key={item.key} className="ui-card quote-aggregate-card">
            <h4>{item.title}</h4>
            <p className="homev3-copy">
              {item.quoteCount.toLocaleString()} quote signal{item.quoteCount === 1 ? "" : "s"} · recent modeled range
            </p>
            <p className="quote-aggregate-card__range">
              {item.averageLow ? `$${item.averageLow.toLocaleString()}` : "N/A"} - {item.averageHigh ? `$${item.averageHigh.toLocaleString()}` : "N/A"}
            </p>
          </article>
        ))}
      </div>
    </div>
  );
}

export default async function QuotesArchivePage() {
  const sections = await getQuoteArchiveByMaterial();
  const cards = sections.flatMap((section) => section.cards);
  const cityCount = new Set(cards.map((card) => card.city)).size;

  const schema = buildArchiveSchema(cards);
  const lastUpdated = cards[0]?.queriedAt
    ? new Date(cards[0].queriedAt).toLocaleDateString("en-CA", {
      year: "numeric",
      month: "long",
      day: "numeric"
    })
    : null;

  return (
    <>
      <QuoteArchiveHashHandler />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
      <PageHero
        eyebrow="Quote archive"
        title="Every recent quote signal in one place"
        description="A crawlable archive of roofing, siding, Hardie, and eavestrough estimate signals generated from live address-level modeled outputs."
      />

      <section className="ui-page-section">
        <PageContainer>
          <div className="quote-card-grid">
            <article className="ui-card">
              <h2>Total quote signals</h2>
              <p className="homev3-copy">{cards.length.toLocaleString()} recent address-level modeled estimate signals are available on this page.</p>
            </article>
            <article className="ui-card">
              <h2>Estimate types</h2>
              <p className="homev3-copy">{sections.length.toLocaleString()} estimate categories are separated on this page so roofing, vinyl, Hardie, and eavestrough pricing are not blended together.</p>
            </article>
            <article className="ui-card">
              <h2>Cities covered</h2>
              <p className="homev3-copy">{cityCount.toLocaleString()} live city-level groupings are currently represented in the quote archive.</p>
            </article>
            <article className="ui-card">
              <h2>Latest update</h2>
              <p className="homev3-copy">{lastUpdated ?? "Live updates appear here as new quotes are generated."}</p>
            </article>
          </div>

          {sections.map((section) => (
            <section key={section.material} style={{ marginTop: 32 }}>
              <h2 className="homev3-title" style={{ fontSize: "2rem" }}>{section.material} estimate signals</h2>
              <p className="homev3-copy" style={{ marginTop: 10 }}>
                {section.cards.length.toLocaleString()} published {section.material.toLowerCase()} quote signal{section.cards.length === 1 ? "" : "s"} are included in this archive section.
              </p>

              {renderAggregateSection("City level", section.aggregates.cities.slice(0, 12))}
              {renderAggregateSection("City + quadrant level", section.aggregates.cityQuadrants.slice(0, 12))}
              {renderAggregateSection("Neighborhood level", section.aggregates.neighborhoods.slice(0, 12))}

              <div style={{ marginTop: 24 }}>
                <h3 className="homev3-title" style={{ fontSize: "1.5rem" }}>Published {section.material.toLowerCase()} quote cards</h3>
                <div className="quote-card-grid" style={{ marginTop: 16 }}>
                  {section.cards.map((card) => (
                    <div key={card.slug} id={card.slug} className="quote-card-anchor">
                      <QuoteCard quote={card} href={null} variant="full" />
                    </div>
                  ))}
                </div>
              </div>
            </section>
          ))}

          <div style={{ marginTop: 28 }}>
            <p className="homev3-copy">
              This archive keeps every quote card in one crawlable location while the instant estimator continues to live at <Link href="/quote">/quote</Link>.
            </p>
          </div>
        </PageContainer>
      </section>

      <CtaBand
        title="Need your own instant price range?"
        body="Use the anonymous estimator to generate a new local quote, then browse the archive to compare nearby activity."
      />
    </>
  );
}
