-- Generated from repository migrations; do not edit sections manually.
-- Pricing catalogue seed/import is intentionally excluded.
begin;
do $$begin if to_regclass('public.pricing_catalog_versions') is null then raise exception 'Pricing catalogue schema must be deployed before estimator migrations';end if;end$$;

-- ===== 0015_internal_roofing_estimates.sql | sha256 5e35c96aaf014156e4909747f7849a24272fe38856facb2eccaf2b03852d6197 =====
-- Internal roofing estimate foundation. Admin requests reach these tables only through service-role server routes.
create table if not exists estimate_customers (
  id uuid primary key default gen_random_uuid(), first_name text not null, last_name text not null,
  email text, phone text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists estimate_properties (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references estimate_customers(id) on delete cascade,
  address_line1 text not null, address_line2 text, city text not null default 'Calgary', province text not null default 'AB',
  postal_code text, place_id text, latitude numeric, longitude numeric, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists estimates (
  id uuid primary key default gen_random_uuid(), customer_id uuid not null references estimate_customers(id),
  property_id uuid not null references estimate_properties(id), scope text not null default 'roofing' check (scope = 'roofing'),
  status text not null default 'draft' check (status in ('draft','archived')), created_by text not null, updated_by text not null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists roofing_measurements (
  estimate_id uuid primary key references estimates(id) on delete cascade, roof_area_sqft numeric not null default 0, squares numeric not null default 0,
  pitch text not null default '4/12', complexity text not null default 'moderate' check (complexity in ('simple','moderate','complex')),
  existing_layers integer not null default 1, eaves numeric not null default 0, rakes numeric not null default 0, valleys numeric not null default 0,
  hips numeric not null default 0, ridges numeric not null default 0, wall_transitions numeric not null default 0,
  plumbing_vents integer not null default 0, goosenecks integer not null default 0, static_vents integer not null default 0,
  stories integer not null default 1, decking_allowance numeric not null default 0,
  access_difficulty text not null default 'standard' check (access_difficulty in ('standard','restricted','difficult')),
  internal_notes text not null default '', updated_at timestamptz not null default now()
);
create table if not exists estimate_system_snapshots (
  id uuid primary key default gen_random_uuid(), estimate_id uuid not null references estimates(id) on delete cascade,
  tier text not null check (tier in ('good','better','best')), configuration jsonb not null, created_at timestamptz not null default now(),
  unique (estimate_id, tier)
);
create table if not exists estimate_option_results (
  id uuid primary key default gen_random_uuid(), estimate_id uuid not null references estimates(id) on delete cascade,
  system_snapshot_id uuid not null references estimate_system_snapshots(id) on delete cascade, tier text not null,
  breakdown jsonb not null, calculated_price numeric not null, final_price numeric not null, calculated_at timestamptz not null default now(),
  unique (estimate_id, tier)
);
create table if not exists estimate_manual_overrides (
  id uuid primary key default gen_random_uuid(), estimate_id uuid not null references estimates(id) on delete cascade,
  option_result_id uuid not null references estimate_option_results(id) on delete cascade, original_calculated_value numeric not null,
  new_value numeric not null, reason text not null check (length(trim(reason)) > 0), overridden_by text not null, created_at timestamptz not null default now()
);
create index if not exists estimates_updated_at_idx on estimates(updated_at desc);
create index if not exists estimate_properties_customer_idx on estimate_properties(customer_id);
create index if not exists estimate_overrides_estimate_idx on estimate_manual_overrides(estimate_id, created_at desc);

alter table estimate_customers enable row level security;
alter table estimate_properties enable row level security;
alter table estimates enable row level security;
alter table roofing_measurements enable row level security;
alter table estimate_system_snapshots enable row level security;
alter table estimate_option_results enable row level security;
alter table estimate_manual_overrides enable row level security;
do $$ declare t text; begin
  foreach t in array array['estimate_customers','estimate_properties','estimates','roofing_measurements','estimate_system_snapshots','estimate_option_results','estimate_manual_overrides'] loop
    execute format('drop policy if exists "internal estimates are service role only" on %I', t);
    execute format('create policy "internal estimates are service role only" on %I for all using (auth.role() = ''service_role'') with check (auth.role() = ''service_role'')', t);
  end loop;
end $$;

-- ===== 0016_internal_proposals.sql | sha256 622d9e1312fcd7616ee1c7fa0e040aa00a4f94aaac4d1cd2d4a2a2bfa4c78465 =====
create table if not exists proposals(id uuid primary key default gen_random_uuid(),proposal_number text not null unique,estimate_id uuid not null references estimates(id),revision_number integer not null default 1,status text not null default 'draft' check(status in('draft','archived')),customer_snapshot jsonb not null,property_snapshot jsonb not null,estimate_snapshot jsonb not null,roofing_options_snapshot jsonb not null,sections_snapshot jsonb not null default '[]',subtotal numeric not null default 0,gst numeric not null default 0,total numeric not null default 0,expiry_date date not null,proposal_date date not null default current_date,estimator_name text not null,cover_image_snapshot jsonb not null default '{"source":"none"}',cover_image_id uuid,requires_pricing_configuration boolean not null default false,created_by text not null,updated_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists proposal_sections(id uuid primary key default gen_random_uuid(),proposal_id uuid not null references proposals(id) on delete cascade,section_type text not null,title text not null,enabled boolean not null default true,display_order integer not null,content text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists proposal_images(id uuid primary key default gen_random_uuid(),proposal_id uuid not null references proposals(id) on delete cascade,estimate_id uuid not null references estimates(id),property_id uuid references estimate_properties(id),category text not null default 'cover',original_storage_path text,display_storage_path text,source text not null check(source in('street_view','upload')),attribution text,caption text,crop_data jsonb,zoom numeric not null default 1,position_data jsonb,rotation numeric not null default 0,width integer,height integer,display_order integer not null default 0,include_in_proposal boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists proposal_documents(id uuid primary key default gen_random_uuid(),proposal_id uuid not null references proposals(id) on delete cascade,revision_number integer not null,storage_path text not null,file_size integer,mime_type text not null default 'application/pdf',source_snapshot jsonb not null,created_by text not null,created_at timestamptz not null default now());
alter table proposals add constraint proposals_cover_image_fk foreign key(cover_image_id) references proposal_images(id) on delete set null;
create index if not exists proposals_estimate_idx on proposals(estimate_id);create index if not exists proposals_updated_idx on proposals(updated_at desc);create index if not exists proposal_sections_order_idx on proposal_sections(proposal_id,display_order);create index if not exists proposal_images_order_idx on proposal_images(proposal_id,display_order);create index if not exists proposal_documents_proposal_idx on proposal_documents(proposal_id,revision_number desc);
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('proposal-assets','proposal-assets',false,15728640,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
do $$ declare t text;begin foreach t in array array['proposals','proposal_sections','proposal_images','proposal_documents'] loop execute format('alter table %I enable row level security',t);execute format('create policy "internal proposals are service role only" on %I for all using(auth.role()=''service_role'') with check(auth.role()=''service_role'')',t);end loop;end$$;
create policy "proposal assets service role only" on storage.objects for all using(bucket_id='proposal-assets' and auth.role()='service_role') with check(bucket_id='proposal-assets' and auth.role()='service_role');

-- ===== 0017_customer_proposal_signing.sql | sha256 92126265d820a7cfb54dff9d5ddef1f038ec098e3d372d898a36397613f62747 =====
alter table proposals drop constraint if exists proposals_status_check;
alter table proposals add constraint proposals_status_check check(status in('draft','sent','accepted','archived'));
alter table proposals add column if not exists sent_at timestamptz,add column if not exists accepted_at timestamptz,add column if not exists locked_at timestamptz,add column if not exists active_revision_id uuid;
create table if not exists proposal_revisions(id uuid primary key default gen_random_uuid(),proposal_id uuid not null references proposals(id),revision_number integer not null,status text not null check(status in('sent','accepted')),snapshot jsonb not null,pdf_storage_path text,created_by text not null,created_at timestamptz not null default now(),locked_at timestamptz not null default now(),unique(proposal_id,revision_number));
alter table proposals add constraint proposals_active_revision_fk foreign key(active_revision_id) references proposal_revisions(id) on delete restrict;
create table if not exists proposal_access_tokens(id uuid primary key default gen_random_uuid(),proposal_id uuid not null references proposals(id),proposal_revision integer not null,revision_id uuid not null references proposal_revisions(id),token_hash text not null unique check(length(token_hash)=64),expires_at timestamptz not null,revoked_at timestamptz,consumed_at timestamptz,first_viewed_at timestamptz,last_viewed_at timestamptz,created_by text not null,created_at timestamptz not null default now());
create table if not exists proposal_acceptances(id uuid primary key default gen_random_uuid(),proposal_id uuid not null references proposals(id),proposal_revision integer not null,revision_id uuid not null references proposal_revisions(id),access_token_id uuid not null references proposal_access_tokens(id),signer_legal_name text not null,signer_email text not null,signature_type text not null check(signature_type in('typed','drawn')),signature_storage_path text,signature_data text not null,selected_option_id text not null,selected_option_snapshot jsonb not null,selected_product text not null,selected_colour text not null,subtotal numeric not null,gst numeric not null,total numeric not null,acknowledgement_data jsonb not null,accepted_at timestamptz not null,request_ip_hash text,user_agent text,integrity_hash text not null,signed_pdf_storage_path text,created_at timestamptz not null default now(),unique(proposal_id,proposal_revision),unique(access_token_id));
create table if not exists proposal_events(id uuid primary key default gen_random_uuid(),proposal_id uuid not null references proposals(id),proposal_revision integer,event_type text not null check(event_type in('sent','send_failed','opened','option_selected','signing_started','accepted','acceptance_failed','signed_pdf_generated','customer_confirmation_sent','internal_notification_sent','token_expired','token_revoked')),actor_type text not null check(actor_type in('admin','customer','system')),metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table if not exists proposal_deliveries(id uuid primary key default gen_random_uuid(),proposal_id uuid not null references proposals(id),proposal_revision integer not null,recipient text not null,cc_recipients text[] not null default '{}',sender text not null,subject text not null,message text not null,status text not null,provider_message_id text,error_message text,sent_at timestamptz,created_at timestamptz not null default now());
create index if not exists proposal_tokens_lookup_idx on proposal_access_tokens(token_hash);create index if not exists proposal_events_timeline_idx on proposal_events(proposal_id,created_at);create index if not exists proposal_revisions_lookup_idx on proposal_revisions(proposal_id,revision_number);
do $$declare t text;begin foreach t in array array['proposal_revisions','proposal_access_tokens','proposal_acceptances','proposal_events','proposal_deliveries']loop execute format('alter table %I enable row level security',t);execute format('create policy "proposal signing service role only" on %I for all using(auth.role()=''service_role'') with check(auth.role()=''service_role'')',t);end loop;end$$;
create or replace function accept_proposal_revision(p_token_id uuid,p_proposal_id uuid,p_revision_id uuid,p_revision integer,p_signer_name text,p_signer_email text,p_signature_type text,p_signature_data text,p_selected_id text,p_selected_snapshot jsonb,p_product text,p_colour text,p_subtotal numeric,p_gst numeric,p_total numeric,p_ack jsonb,p_accepted_at timestamptz,p_ip_hash text,p_user_agent text,p_integrity text) returns uuid language plpgsql security definer set search_path=public as $$declare v_id uuid;begin perform 1 from proposal_access_tokens where id=p_token_id and proposal_id=p_proposal_id and revision_id=p_revision_id and revoked_at is null and expires_at>now() for update;if not found then raise exception 'token unavailable';end if;perform 1 from proposals where id=p_proposal_id and status='sent' and active_revision_id=p_revision_id for update;if not found then raise exception 'proposal unavailable';end if;insert into proposal_acceptances(proposal_id,proposal_revision,revision_id,access_token_id,signer_legal_name,signer_email,signature_type,signature_data,selected_option_id,selected_option_snapshot,selected_product,selected_colour,subtotal,gst,total,acknowledgement_data,accepted_at,request_ip_hash,user_agent,integrity_hash)values(p_proposal_id,p_revision,p_revision_id,p_token_id,p_signer_name,p_signer_email,p_signature_type,p_signature_data,p_selected_id,p_selected_snapshot,p_product,p_colour,p_subtotal,p_gst,p_total,p_ack,p_accepted_at,p_ip_hash,p_user_agent,p_integrity)returning id into v_id;update proposal_access_tokens set consumed_at=now() where id=p_token_id;update proposal_revisions set status='accepted' where id=p_revision_id;update proposals set status='accepted',accepted_at=p_accepted_at,locked_at=now() where id=p_proposal_id;insert into proposal_events(proposal_id,proposal_revision,event_type,actor_type,metadata)values(p_proposal_id,p_revision,'accepted','customer',jsonb_build_object('acceptance_id',v_id));return v_id;end$$;
revoke all on function accept_proposal_revision(uuid,uuid,uuid,integer,text,text,text,text,text,jsonb,text,text,numeric,numeric,numeric,jsonb,timestamptz,text,text,text) from public,anon,authenticated;
grant execute on function accept_proposal_revision(uuid,uuid,uuid,integer,text,text,text,text,text,jsonb,text,text,numeric,numeric,numeric,jsonb,timestamptz,text,text,text) to service_role;

-- ===== 0018_roofing_system_configuration.sql | sha256 92b986a30b5764b1cb20cec2ae5333ee31c42777524464f279a8bacfe3dd982d =====
create table if not exists roofing_systems (
  id uuid primary key default gen_random_uuid(), system_key text not null unique, system_name text not null,
  tier text not null check (tier in ('good','better','best','custom')), manufacturer text not null,
  active boolean not null default true, active_version_id uuid, created_by text not null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists roofing_system_versions (
  id uuid primary key default gen_random_uuid(), roofing_system_id uuid not null references roofing_systems(id) on delete restrict,
  version_number integer not null, catalog_version_id uuid not null references pricing_catalog_versions(id) on delete restrict,
  field_shingle_item_id uuid not null references pricing_catalog_items(id) on delete restrict,
  starter_item_id uuid references pricing_catalog_items(id) on delete restrict, hip_ridge_item_id uuid references pricing_catalog_items(id) on delete restrict,
  ice_water_item_id uuid references pricing_catalog_items(id) on delete restrict, underlayment_item_id uuid references pricing_catalog_items(id) on delete restrict,
  drip_edge_item_id uuid references pricing_catalog_items(id) on delete restrict, rake_edge_item_id uuid references pricing_catalog_items(id) on delete restrict,
  valley_metal_item_id uuid references pricing_catalog_items(id) on delete restrict, attic_vent_item_id uuid references pricing_catalog_items(id) on delete restrict,
  gooseneck_item_id uuid references pricing_catalog_items(id) on delete restrict, plumbing_boot_item_id uuid references pricing_catalog_items(id) on delete restrict,
  waste_factors jsonb not null default '{}', customer_summary text not null, warranty_summary text not null,
  compatibility_confirmed boolean not null default false, compatibility_reason text, production_ready boolean not null default false,
  review_warnings jsonb not null default '[]', pricing_strategy jsonb not null default '{"type":"fixed_profit","value":100}',
  created_by text not null, created_at timestamptz not null default now(), unique(roofing_system_id,version_number)
);
alter table roofing_systems add constraint roofing_systems_active_version_fk foreign key(active_version_id) references roofing_system_versions(id) on delete restrict;
create index if not exists roofing_system_versions_system_idx on roofing_system_versions(roofing_system_id,version_number desc);
create index if not exists roofing_system_versions_catalog_idx on roofing_system_versions(catalog_version_id);
alter table roofing_systems enable row level security; alter table roofing_system_versions enable row level security;
create policy "roofing systems service role only" on roofing_systems for all using(auth.role()='service_role') with check(auth.role()='service_role');
create policy "roofing system versions service role only" on roofing_system_versions for all using(auth.role()='service_role') with check(auth.role()='service_role');
insert into roofing_systems(system_key,system_name,tier,manufacturer,created_by) values
('good','Trusted Good Roofing System','good','GAF','migration'),('better','Trusted Better Roofing System','better','Malarkey','migration'),('best','Trusted Best Roofing System','best','Malarkey','migration') on conflict(system_key) do nothing;

-- ===== 0019_soft_metals_estimates.sql | sha256 8326372a5aa6beb705fe849852fa02cffc111c11e1d2932bc56b0df59e7ebe50 =====
alter table estimates drop constraint if exists estimates_scope_check;
alter table estimates add constraint estimates_scope_check check(scope in('roofing','soft_metals','combined'));
create table if not exists estimate_scopes(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,scope_type text not null check(scope_type in('eavestrough','downspouts','fascia','soffit')),enabled boolean not null default false,measurements jsonb not null default '{}',customer_summary jsonb not null default '{}',catalog_version_id uuid references pricing_catalog_versions(id) on delete restrict,production_ready boolean not null default false,warnings jsonb not null default '[]',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(estimate_id,scope_type));
create table if not exists estimate_scope_material_snapshots(id uuid primary key default gen_random_uuid(),estimate_scope_id uuid not null references estimate_scopes(id) on delete cascade,catalog_item_id uuid references pricing_catalog_items(id) on delete restrict,component_key text not null,snapshot jsonb not null,created_at timestamptz not null default now(),unique(estimate_scope_id,component_key));
create table if not exists estimate_scope_rate_snapshots(id uuid primary key default gen_random_uuid(),estimate_scope_id uuid not null references estimate_scopes(id) on delete cascade,rate_item_id uuid references pricing_rate_items(id) on delete restrict,rate_key text not null,snapshot jsonb not null,created_at timestamptz not null default now(),unique(estimate_scope_id,rate_key));
create table if not exists estimate_scope_results(id uuid primary key default gen_random_uuid(),estimate_scope_id uuid not null unique references estimate_scopes(id) on delete cascade,material_cost numeric not null default 0,labour_cost numeric not null default 0,disposal numeric not null default 0,delivery numeric not null default 0,overhead numeric not null default 0,total_cost numeric not null default 0,selling_price numeric not null default 0,profit numeric not null default 0,gross_margin_percent numeric not null default 0,pricing_strategy jsonb not null,calculated_at timestamptz not null default now());
create table if not exists estimate_scope_overrides(id uuid primary key default gen_random_uuid(),estimate_scope_id uuid not null references estimate_scopes(id) on delete cascade,field_name text not null,original_value numeric,new_value numeric not null,reason text not null check(length(trim(reason))>0),overridden_by text not null,created_at timestamptz not null default now());
create index if not exists estimate_scopes_estimate_idx on estimate_scopes(estimate_id);create index if not exists estimate_scope_overrides_scope_idx on estimate_scope_overrides(estimate_scope_id,created_at desc);
do $$declare t text;begin foreach t in array array['estimate_scopes','estimate_scope_material_snapshots','estimate_scope_rate_snapshots','estimate_scope_results','estimate_scope_overrides']loop execute format('alter table %I enable row level security',t);execute format('create policy "estimate scopes service role only" on %I for all using(auth.role()=''service_role'') with check(auth.role()=''service_role'')',t);end loop;end$$;

-- ===== 0020_soft_metal_proposals.sql | sha256 4d28ece45f3e9b7de156825f7f6a4432e4d1254192f034c1d24f25559525bda4 =====
alter table proposals add column if not exists estimate_type text not null default 'roofing' check (estimate_type in ('roofing','soft_metals','combined')), add column if not exists soft_metal_scopes_snapshot jsonb not null default '[]'::jsonb;
alter table proposal_acceptances add column if not exists selected_scope_snapshots jsonb not null default '[]'::jsonb, add column if not exists declined_scope_snapshots jsonb not null default '[]'::jsonb, add column if not exists scope_colour_selections jsonb not null default '{}'::jsonb;
create or replace function accept_proposal_revision_v2(p_token_id uuid,p_proposal_id uuid,p_revision_id uuid,p_revision integer,p_signer_name text,p_signer_email text,p_signature_type text,p_signature_data text,p_selected_id text,p_selected_snapshot jsonb,p_product text,p_colour text,p_selected_scopes jsonb,p_declined_scopes jsonb,p_scope_colours jsonb,p_subtotal numeric,p_gst numeric,p_total numeric,p_ack jsonb,p_accepted_at timestamptz,p_ip_hash text,p_user_agent text,p_integrity text) returns uuid language plpgsql security definer set search_path=public as $$declare v_id uuid;begin perform 1 from proposal_access_tokens where id=p_token_id and proposal_id=p_proposal_id and revision_id=p_revision_id and revoked_at is null and consumed_at is null and expires_at>now() for update;if not found then raise exception 'token unavailable';end if;perform 1 from proposals where id=p_proposal_id and status='sent' and active_revision_id=p_revision_id for update;if not found then raise exception 'proposal unavailable';end if;insert into proposal_acceptances(proposal_id,proposal_revision,revision_id,access_token_id,signer_legal_name,signer_email,signature_type,signature_data,selected_option_id,selected_option_snapshot,selected_product,selected_colour,selected_scope_snapshots,declined_scope_snapshots,scope_colour_selections,subtotal,gst,total,acknowledgement_data,accepted_at,request_ip_hash,user_agent,integrity_hash)values(p_proposal_id,p_revision,p_revision_id,p_token_id,p_signer_name,p_signer_email,p_signature_type,p_signature_data,p_selected_id,p_selected_snapshot,p_product,p_colour,p_selected_scopes,p_declined_scopes,p_scope_colours,p_subtotal,p_gst,p_total,p_ack,p_accepted_at,p_ip_hash,p_user_agent,p_integrity)returning id into v_id;update proposal_access_tokens set consumed_at=now() where id=p_token_id;update proposal_revisions set status='accepted' where id=p_revision_id;update proposals set status='accepted',accepted_at=p_accepted_at,locked_at=now() where id=p_proposal_id;insert into proposal_events(proposal_id,proposal_revision,event_type,actor_type,metadata)values(p_proposal_id,p_revision,'accepted','customer',jsonb_build_object('acceptance_id',v_id));return v_id;end$$;
revoke all on function accept_proposal_revision_v2(uuid,uuid,uuid,integer,text,text,text,text,text,jsonb,text,text,jsonb,jsonb,jsonb,numeric,numeric,numeric,jsonb,timestamptz,text,text,text) from public,anon,authenticated;
grant execute on function accept_proposal_revision_v2(uuid,uuid,uuid,integer,text,text,text,text,text,jsonb,text,text,jsonb,jsonb,jsonb,numeric,numeric,numeric,jsonb,timestamptz,text,text,text) to service_role;
create index if not exists proposals_estimate_type_idx on proposals(estimate_type);

-- ===== 0021_paginated_proposal_documents.sql | sha256 8691ba398005b5117341568518a49793395e185b4b7b267479a90b2c815c08b7 =====
alter table proposal_documents
  add column if not exists document_type text not null default 'draft' check(document_type in('draft','sent','signed')),
  add column if not exists status text not null default 'completed' check(status in('started','completed','failed')),
  add column if not exists page_count integer,
  add column if not exists renderer_version text,
  add column if not exists document_hash text,
  add column if not exists generation_error text,
  add column if not exists generated_at timestamptz not null default now();
create unique index if not exists proposal_documents_revision_type_uidx on proposal_documents(proposal_id,revision_number,document_type);
alter table proposal_events drop constraint if exists proposal_events_event_type_check;
alter table proposal_events add constraint proposal_events_event_type_check check(event_type in('sent','send_failed','opened','option_selected','signing_started','accepted','acceptance_failed','signed_pdf_generated','customer_confirmation_sent','internal_notification_sent','token_expired','token_revoked','pdf_generation_started','pdf_generation_completed','pdf_generation_failed','signed_pdf_generation_started','signed_pdf_generation_completed','signed_pdf_generation_failed'));

-- ===== 0022_project_image_library.sql | sha256 8327e8ab1df9f757355a32ed10e0a5bff1625132a752155c399b9939435382b9 =====
create table if not exists project_images(id uuid primary key default gen_random_uuid(),customer_id uuid references estimate_customers(id),property_id uuid references estimate_properties(id),estimate_id uuid references estimates(id),proposal_id uuid references proposals(id),original_storage_path text not null unique,preview_storage_path text,source_type text not null default 'upload',original_filename text not null,mime_type text not null check(mime_type in('image/jpeg','image/png','image/webp')),width integer,height integer,file_size bigint not null check(file_size>0 and file_size<=15728640),category text not null default 'other',title text not null default '',caption text not null default '',customer_comment text not null default '',internal_note text not null default '',attribution text not null default '',created_by text not null,archived boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists project_image_versions(id uuid primary key default gen_random_uuid(),project_image_id uuid not null references project_images(id) on delete restrict,version_number integer not null,derivative_storage_path text,transform jsonb not null,annotations jsonb not null default '[]',legends jsonb not null default '[]',base_updated_at timestamptz,created_by text not null,created_at timestamptz not null default now(),unique(project_image_id,version_number));
create table if not exists proposal_image_instances(id uuid primary key default gen_random_uuid(),proposal_id uuid not null references proposals(id) on delete cascade,project_image_id uuid references project_images(id) on delete restrict,version_id uuid references project_image_versions(id) on delete restrict,section_type text not null check(section_type in('photos','plan')),plan_type text,title text not null default '',caption text not null default '',customer_comment text not null default '',include_in_proposal boolean not null default true,display_order integer not null default 0,layout text not null default 'full',transform jsonb not null,annotations_snapshot jsonb not null default '[]',legends_snapshot jsonb not null default '[]',orientation text not null default 'portrait' check(orientation in('portrait','landscape')),customer_facing boolean not null default true,allow_placeholder boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table proposals add column if not exists image_instances_snapshot jsonb not null default '[]'::jsonb;
create index if not exists project_images_project_idx on project_images(estimate_id,property_id,archived);create index if not exists proposal_image_instances_order_idx on proposal_image_instances(proposal_id,section_type,display_order);
do $$declare t text;begin foreach t in array array['project_images','project_image_versions','proposal_image_instances'] loop execute format('alter table %I enable row level security',t);execute format('create policy "project images service role only" on %I for all using(auth.role()=''service_role'') with check(auth.role()=''service_role'')',t);end loop;end$$;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('project-images','project-images',false,15728640,array['image/jpeg','image/png','image/webp']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "project image objects service role only" on storage.objects for all using(bucket_id='project-images' and auth.role()='service_role') with check(bucket_id='project-images' and auth.role()='service_role');

-- ===== 0023_vinyl_siding_estimates_and_proposals.sql | sha256 cbd0d86c7ab50eb6034918e5cd0dc8f75e7aa484ce96d3f8a807bd79e9475f6a =====
-- Additive, backward-compatible multi-trade and vinyl-siding snapshots.
alter table estimates add column if not exists selected_scopes text[] not null default '{}';
update estimates set selected_scopes=case scope when 'roofing' then array['roofing'] when 'soft_metals' then array['soft_metals'] when 'combined' then array['roofing','soft_metals'] else array[scope] end where cardinality(selected_scopes)=0;
alter table estimates drop constraint if exists estimates_scope_check;
alter table estimates add constraint estimates_scope_check check(scope in('roofing','soft_metals','vinyl_siding','combined','multi_trade'));
alter table estimates add constraint estimates_selected_scopes_check check(selected_scopes <@ array['roofing','soft_metals','vinyl_siding','hardie_siding','custom']::text[] and cardinality(selected_scopes)>0);
alter table estimate_scopes drop constraint if exists estimate_scopes_scope_type_check;
alter table estimate_scopes add constraint estimate_scopes_scope_type_check check(scope_type in('eavestrough','downspouts','fascia','soffit','vinyl_siding'));
alter table proposals add column if not exists selected_scopes text[] not null default '{}';
alter table proposals add column if not exists vinyl_scopes_snapshot jsonb not null default '[]' check(jsonb_typeof(vinyl_scopes_snapshot)='array');
alter table proposal_acceptances add column if not exists vinyl_selection_snapshot jsonb not null default '{}' check(jsonb_typeof(vinyl_selection_snapshot)='object');
create index if not exists estimates_selected_scopes_gin_idx on estimates using gin(selected_scopes);
create index if not exists estimate_scopes_vinyl_idx on estimate_scopes(estimate_id) where scope_type='vinyl_siding';
comment on column proposals.vinyl_scopes_snapshot is 'Immutable customer-safe vinyl scope data copied into each locked proposal revision.';

-- ===== 0024_hardie_siding_estimates_and_proposals.sql | sha256 1f324259ac70af5080e8df296c0b8d239f175876a1317404f5ce5b9fa8e55279 =====
-- Additive James Hardie scope support using the existing service-role-only generic scope tables.
alter table estimates drop constraint if exists estimates_scope_check;
alter table estimates add constraint estimates_scope_check check(scope in('roofing','soft_metals','vinyl_siding','hardie_siding','combined','multi_trade'));
alter table estimates drop constraint if exists estimates_selected_scopes_check;
alter table estimates add constraint estimates_selected_scopes_check check(selected_scopes <@ array['roofing','soft_metals','vinyl_siding','hardie_siding','custom']::text[] and cardinality(selected_scopes)>0);
alter table estimate_scopes drop constraint if exists estimate_scopes_scope_type_check;
alter table estimate_scopes add constraint estimate_scopes_scope_type_check check(scope_type in('eavestrough','downspouts','fascia','soffit','vinyl_siding','hardie_siding'));
alter table proposals add column if not exists hardie_scopes_snapshot jsonb not null default '[]' check(jsonb_typeof(hardie_scopes_snapshot)='array');
alter table proposal_acceptances add column if not exists hardie_selection_snapshot jsonb not null default '{}' check(jsonb_typeof(hardie_selection_snapshot)='object');
create index if not exists estimate_scopes_hardie_idx on estimate_scopes(estimate_id) where scope_type='hardie_siding';
comment on column proposals.hardie_scopes_snapshot is 'Immutable customer-safe James Hardie scope data copied into each locked proposal revision.';
comment on column proposal_acceptances.hardie_selection_snapshot is 'Accepted Hardie assembly, elevation, finish, colour, rainscreen and insulation selections.';
-- Existing RLS policies on estimates, estimate_scopes, proposals and acceptances remain service-role only.

-- ===== 0025_specification_tender_estimates_and_proposals.sql | sha256 320013f442ef419b1b13f6fb4447cffa2b1c045825512aa5aa3b1a95dcd67301 =====
-- Specification/tender mode reuses existing estimate scopes, pricing snapshots, proposals, documents and signing.
alter table estimates add column if not exists estimate_mode text not null default 'standard' check(estimate_mode in('standard','specification'));
create table if not exists estimate_tender_details(id uuid primary key default gen_random_uuid(),estimate_id uuid not null unique references estimates(id) on delete cascade,snapshot jsonb not null default '{}',updated_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(jsonb_typeof(snapshot)='object'));
create table if not exists tender_supporting_documents(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,proposal_id uuid references proposals(id) on delete set null,document_type text not null check(document_type in('specification','drawing_set','addendum','bid_form','insurance_scope','consultant_detail','product_requirement','supplier_quotation','supporting_image','other')),title text not null default '',original_filename text not null,mime_type text not null check(mime_type in('application/pdf','image/jpeg','image/png','image/webp')),file_size bigint not null check(file_size>0 and file_size<=26214400),storage_path text not null unique,include_in_proposal boolean not null default false,customer_label text not null default '',created_by text not null,created_at timestamptz not null default now());
create table if not exists specification_references(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,document_id uuid references tender_supporting_documents(id) on delete set null,reference_type text not null,label text not null,reference_data jsonb not null default '{}',display_order integer not null default 0,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists specification_compliance_items(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,category text not null default '',requirement text not null,status text check(status in('included','excluded','alternate','allowance','unit_rate','by_others','not_applicable','clarification_required','rfi_submitted','compliant','non_compliant','internal_only')),customer_response text not null default '',internal_note text not null default '',links jsonb not null default '{}',rfi jsonb not null default '{}',include_in_proposal boolean not null default true,display_order integer not null default 0,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists tender_alternates(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,snapshot jsonb not null,display_order integer not null default 0,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists tender_allowances(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,snapshot jsonb not null,display_order integer not null default 0,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists tender_unit_rates(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,rate_item_id uuid references pricing_rate_items(id) on delete restrict,snapshot jsonb not null,display_order integer not null default 0,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists tender_text_items(id uuid primary key default gen_random_uuid(),estimate_id uuid not null references estimates(id) on delete cascade,item_type text not null check(item_type in('exclusion','assumption','clarification')),snapshot jsonb not null,display_order integer not null default 0,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table proposals add column if not exists estimate_mode text not null default 'standard' check(estimate_mode in('standard','specification'));
alter table proposals add column if not exists specification_snapshot jsonb not null default '{}' check(jsonb_typeof(specification_snapshot)='object');
alter table proposal_acceptances add column if not exists tender_selection_snapshot jsonb not null default '{}' check(jsonb_typeof(tender_selection_snapshot)='object');
create index if not exists tender_documents_estimate_idx on tender_supporting_documents(estimate_id,created_at);create index if not exists specification_references_estimate_idx on specification_references(estimate_id,display_order);create index if not exists compliance_estimate_order_idx on specification_compliance_items(estimate_id,display_order);create index if not exists tender_alternates_estimate_idx on tender_alternates(estimate_id,display_order);create index if not exists tender_allowances_estimate_idx on tender_allowances(estimate_id,display_order);create index if not exists tender_unit_rates_estimate_idx on tender_unit_rates(estimate_id,display_order);create index if not exists tender_text_items_estimate_idx on tender_text_items(estimate_id,item_type,display_order);
do $$declare t text;begin foreach t in array array['estimate_tender_details','tender_supporting_documents','specification_references','specification_compliance_items','tender_alternates','tender_allowances','tender_unit_rates','tender_text_items']loop execute format('alter table %I enable row level security',t);execute format('create policy "tender records service role only" on %I for all using(auth.role()=''service_role'') with check(auth.role()=''service_role'')',t);end loop;end$$;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('tender-documents','tender-documents',false,26214400,array['application/pdf','image/jpeg','image/png','image/webp'])on conflict(id)do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "tender document objects service role only" on storage.objects for all using(bucket_id='tender-documents' and auth.role()='service_role') with check(bucket_id='tender-documents' and auth.role()='service_role');

-- ===== 0026_job_workflow_metadata.sql | sha256 a718ee581ad2025a7a8ee0841d935624306f4d23bf2e021f8c75a3a5eaa1b316 =====
-- Estimator-led workflow metadata. Estimates remain the job aggregate root.
alter table public.estimates add column if not exists assigned_estimator text;
alter table public.estimates add column if not exists workflow_status text not null default 'draft' check (workflow_status in ('draft','needs_pricing','ready_for_proposal','proposal_draft','sent','viewed','accepted','expired','archived'));
alter table public.estimates add column if not exists archived boolean not null default false;
alter table public.estimates add column if not exists preferred_proposal_id uuid references public.proposals(id) on delete set null;
alter table public.estimates add column if not exists ui_completion_state jsonb not null default '{}'::jsonb check (jsonb_typeof(ui_completion_state)='object');
create index if not exists estimates_workflow_status_updated_idx on public.estimates(workflow_status,updated_at desc) where archived=false;
create index if not exists estimates_assigned_estimator_idx on public.estimates(assigned_estimator) where archived=false;

-- ===== 0027_projects_and_change_orders.sql | sha256 46ccbfaf67026e30466ff89a48a4050e8fb1c31ddad31e0a38aa678c4167351e =====
create table if not exists projects(id uuid primary key default gen_random_uuid(),project_number text not null unique,estimate_id uuid not null references estimates(id),proposal_id uuid not null references proposals(id),accepted_revision_id uuid not null references proposal_revisions(id),acceptance_id uuid not null references proposal_acceptances(id),customer_id uuid not null references estimate_customers(id),property_id uuid not null references estimate_properties(id),signed_document_id uuid references proposal_documents(id),accepted_integrity_hash text not null,project_title text not null,accepted_contract_number text not null,accepted_revision_number integer not null,original_subtotal numeric not null,original_gst numeric not null,original_total numeric not null,current_subtotal numeric not null,current_gst numeric not null,current_total numeric not null,status text not null default 'accepted' check(status in('accepted','pre_production','awaiting_measurements','awaiting_product_selection','awaiting_colour_confirmation','awaiting_material_order','materials_ordered','scheduled','in_progress','substantially_complete','deficiency','complete','on_hold','cancelled','archived')),assigned_project_manager text,assigned_estimator text,target_start_date date,scheduled_start_date date,target_completion_date date,actual_completion_date date,crew text,subcontractor text,supplier text,permit_status text,material_order_status text,colour_confirmation_status text,customer_contact_status text,internal_notes text,production_notes text,change_order_sequence integer not null default 0,created_by text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),archived_at timestamptz,unique(acceptance_id));
create table if not exists project_status_history(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),previous_status text,new_status text not null,changed_by text not null,changed_at timestamptz not null default now(),note text);
create table if not exists project_operational_details(project_id uuid primary key references projects(id),confirmed_products jsonb not null default '[]',material_quantities jsonb not null default '[]',supplier_quote_number text,purchase_order_reference text,order_date date,expected_delivery date,actual_delivery date,delivery_location text,site_contact text,access_instructions text,safety_notes text,permit_information text,warranty_registration_status text,cleanup_requirements text,disposal_requirements text,special_instructions text,updated_by text,updated_at timestamptz not null default now());
create table if not exists project_colour_confirmations(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),scope text not null,product text not null,accepted_colour text,confirmed_colour text,status text not null check(status in('accepted_in_proposal','customer_confirmation_required','confirmed','changed_by_approved_change_order','supplier_confirmation_required','unavailable','substitute_proposed')),confirmation_source text,confirmed_by text,confirmed_at timestamptz,note text,no_cost_customer_confirmation jsonb,approved_change_order_revision_id uuid,created_at timestamptz not null default now(),check(coalesce(confirmed_colour,'')=coalesce(accepted_colour,'') or approved_change_order_revision_id is not null or no_cost_customer_confirmation is not null));
create table if not exists project_documents(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),document_type text not null,filename text not null,mime_type text not null,file_size bigint not null check(file_size>0 and file_size<=26214400),storage_path text not null unique,customer_shared boolean not null default false,uploaded_by text not null,created_at timestamptz not null default now());
create table if not exists project_image_associations(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),project_image_id uuid not null references project_images(id),category text not null check(category in('estimate','existing_condition','approved_scope','production','progress','deficiency','completion','warranty','change_order')),created_at timestamptz not null default now(),unique(project_id,project_image_id,category));
create table if not exists change_orders(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),accepted_proposal_id uuid not null references proposals(id),accepted_revision_id uuid not null references proposal_revisions(id),customer_id uuid not null references estimate_customers(id),property_id uuid not null references estimate_properties(id),sequence_number integer not null,change_order_number text not null,current_revision integer not null default 1,created_by text not null,created_at timestamptz not null default now(),unique(project_id,sequence_number),unique(project_id,change_order_number));
create table if not exists change_order_revisions(id uuid primary key default gen_random_uuid(),change_order_id uuid not null references change_orders(id),revision_number integer not null,status text not null default 'draft' check(status in('draft','internal_review','ready_to_send','sent','viewed','approved','declined','expired','voided','superseded')),title text not null,reason text not null,requested_by text,requested_date date,affected_scope text,existing_scope text,proposed_change text,change_type text not null,product_changes jsonb not null default '[]',colour_changes jsonb not null default '[]',schedule_impact jsonb not null default '{}',warranty_impact text,exclusions jsonb not null default '[]',assumptions jsonb not null default '[]',customer_notes text,internal_notes text,subtotal numeric not null default 0,gst numeric not null default 0,total numeric not null default 0,expiry_date date,allow_decline boolean not null default true,snapshot jsonb not null default '{}',pdf_storage_path text,signed_pdf_storage_path text,integrity_hash text,created_by text not null,created_at timestamptz not null default now(),locked_at timestamptz,unique(change_order_id,revision_number));
create table if not exists change_order_line_items(id uuid primary key default gen_random_uuid(),revision_id uuid not null references change_order_revisions(id),title text not null,description text,quantity numeric not null check(quantity>=0),unit text not null,unit_price numeric not null check(unit_price>=0),extension numeric not null,line_type text not null check(line_type in('addition','deduction','no_cost','allowance_reconciliation','unit_rate','tax_adjustment','custom')),linked_scope text,catalogue_item_id uuid,rate_item_id uuid,accepted_unit_rate numeric,customer_visible boolean not null default true,display_order integer not null,material_cost numeric,labour_cost numeric,overhead numeric,pricing_strategy jsonb,calculation_trace jsonb,check(line_type<>'unit_rate' or accepted_unit_rate is null or unit_price=accepted_unit_rate));
create table if not exists change_order_access_tokens(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),change_order_id uuid not null references change_orders(id),revision_id uuid not null references change_order_revisions(id),token_hash text not null unique check(length(token_hash)=64),expires_at timestamptz not null,revoked_at timestamptz,consumed_at timestamptz,first_viewed_at timestamptz,last_viewed_at timestamptz,created_by text not null,created_at timestamptz not null default now());
create table if not exists change_order_acceptances(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),change_order_id uuid not null references change_orders(id),revision_id uuid not null references change_order_revisions(id),token_id uuid not null references change_order_access_tokens(id),decision text not null check(decision in('approved','declined')),signer_name text not null,signer_title text,signer_email text not null,signature_type text check(signature_type in('typed','drawn')),signature_data text,customer_note text,subtotal numeric not null,gst numeric not null,total numeric not null,accepted_at timestamptz not null,request_ip_hash text,user_agent text,integrity_hash text not null,signed_pdf_storage_path text,created_at timestamptz not null default now(),unique(revision_id),unique(token_id));
create table if not exists change_order_documents(id uuid primary key default gen_random_uuid(),revision_id uuid not null references change_order_revisions(id),filename text not null,mime_type text not null,file_size bigint not null check(file_size>0 and file_size<=26214400),storage_path text not null unique,customer_visible boolean not null default false,created_by text not null,created_at timestamptz not null default now());
create table if not exists change_order_events(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),change_order_id uuid,revised_id uuid,event_type text not null,actor_type text not null check(actor_type in('admin','customer','system')),metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table if not exists project_total_snapshots(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),original_subtotal numeric not null,approved_change_order_subtotal numeric not null,current_subtotal numeric not null,current_gst numeric not null,current_total numeric not null,reason text not null,created_at timestamptz not null default now());
create index if not exists projects_estimate_idx on projects(estimate_id);create index if not exists projects_status_idx on projects(status,updated_at desc);create index if not exists change_orders_project_idx on change_orders(project_id,sequence_number);create index if not exists change_order_revisions_status_idx on change_order_revisions(status,created_at);create index if not exists change_order_tokens_hash_idx on change_order_access_tokens(token_hash);create index if not exists project_history_idx on project_status_history(project_id,changed_at);
create or replace function create_project_from_acceptance(p_acceptance uuid,p_actor text)returns uuid language plpgsql security definer set search_path=public as $$declare a proposal_acceptances%rowtype;p proposals%rowtype;e estimates%rowtype;v uuid;doc uuid;begin select * into a from proposal_acceptances where id=p_acceptance;select * into p from proposals where id=a.proposal_id and status='accepted';select * into e from estimates where id=p.estimate_id;if not found then raise exception 'accepted proposal unavailable';end if;select id into v from projects where acceptance_id=a.id;if v is not null then return v;end if;select id into doc from proposal_documents where proposal_id=p.id and revision_number=a.proposal_revision and document_type='signed' and status='completed' order by generated_at desc limit 1;insert into projects(project_number,estimate_id,proposal_id,accepted_revision_id,acceptance_id,customer_id,property_id,signed_document_id,accepted_integrity_hash,project_title,accepted_contract_number,accepted_revision_number,original_subtotal,original_gst,original_total,current_subtotal,current_gst,current_total,created_by)select 'PRJ-'||to_char(now(),'YYYY')||'-'||lpad(nextval('projects_project_number_seq')::text,5,'0'),p.estimate_id,p.id,a.revision_id,a.id,e.customer_id,e.property_id,doc,a.integrity_hash,p.proposal_number,p.proposal_number,a.proposal_revision,a.subtotal,a.gst,a.total,a.subtotal,a.gst,a.total,p_actor returning id into v;insert into project_status_history(project_id,new_status,changed_by,note)values(v,'accepted',p_actor,'Created from accepted proposal');insert into project_total_snapshots(project_id,original_subtotal,approved_change_order_subtotal,current_subtotal,current_gst,current_total,reason)values(v,a.subtotal,0,a.subtotal,a.gst,a.total,'project_created');return v;exception when unique_violation then select id into v from projects where acceptance_id=p_acceptance;return v;end$$;
create sequence if not exists projects_project_number_seq;
create or replace function next_change_order_number(p_project uuid,p_actor text)returns table(change_order_id uuid,change_order_number text)language plpgsql security definer set search_path=public as $$declare n integer;pr projects%rowtype;begin select * into pr from projects where id=p_project for update;if not found then raise exception 'project unavailable';end if;n:=pr.change_order_sequence+1;update projects set change_order_sequence=n,updated_at=now() where id=p_project;return query insert into change_orders(project_id,accepted_proposal_id,accepted_revision_id,customer_id,property_id,sequence_number,change_order_number,created_by)values(pr.id,pr.proposal_id,pr.accepted_revision_id,pr.customer_id,pr.property_id,n,'CO-'||lpad(n::text,3,'0'),p_actor)returning id,change_orders.change_order_number;end$$;
create or replace function refresh_project_totals(p_project uuid,p_reason text)returns void language plpgsql security definer set search_path=public as $$declare p projects%rowtype;delta numeric;begin select * into p from projects where id=p_project for update;select coalesce(sum(r.subtotal),0) into delta from change_order_revisions r join change_orders c on c.id=r.change_order_id where c.project_id=p_project and r.status='approved';update projects set current_subtotal=p.original_subtotal+delta,current_gst=round((p.original_subtotal+delta)*.05,2),current_total=round((p.original_subtotal+delta)*1.05,2),updated_at=now() where id=p_project;insert into project_total_snapshots(project_id,original_subtotal,approved_change_order_subtotal,current_subtotal,current_gst,current_total,reason)values(p_project,p.original_subtotal,delta,p.original_subtotal+delta,round((p.original_subtotal+delta)*.05,2),round((p.original_subtotal+delta)*1.05,2),p_reason);end$$;
create or replace function approve_change_order(p_token uuid,p_revision uuid,p_decision text,p_signer text,p_title text,p_email text,p_signature_type text,p_signature_data text,p_note text,p_subtotal numeric,p_gst numeric,p_total numeric,p_at timestamptz,p_ip_hash text,p_user_agent text,p_integrity text)returns uuid language plpgsql security definer set search_path=public as $$declare t change_order_access_tokens%rowtype;r change_order_revisions%rowtype;c change_orders%rowtype;v uuid;begin select * into t from change_order_access_tokens where id=p_token and revision_id=p_revision and revoked_at is null and consumed_at is null and expires_at>now() for update;if not found then raise exception 'token unavailable';end if;select * into r from change_order_revisions where id=p_revision and status in('sent','viewed') for update;select * into c from change_orders where id=r.change_order_id;if r.subtotal<>p_subtotal or r.gst<>p_gst or r.total<>p_total then raise exception 'totals changed';end if;if p_decision='declined' and not r.allow_decline then raise exception 'decline unavailable';end if;insert into change_order_acceptances(project_id,change_order_id,revision_id,token_id,decision,signer_name,signer_title,signer_email,signature_type,signature_data,customer_note,subtotal,gst,total,accepted_at,request_ip_hash,user_agent,integrity_hash)values(c.project_id,c.id,r.id,t.id,p_decision,p_signer,p_title,p_email,p_signature_type,p_signature_data,p_note,p_subtotal,p_gst,p_total,p_at,p_ip_hash,p_user_agent,p_integrity)returning id into v;update change_order_access_tokens set consumed_at=now() where id=t.id;update change_order_revisions set status=case when p_decision='approved'then'approved'else'declined'end,integrity_hash=p_integrity,locked_at=now() where id=r.id;if p_decision='approved'then perform refresh_project_totals(c.project_id,'change_order_approved');end if;insert into change_order_events(project_id,change_order_id,revised_id,event_type,actor_type,metadata)values(c.project_id,c.id,r.id,p_decision,'customer',jsonb_build_object('acceptance_id',v));return v;end$$;
create or replace function prevent_locked_change_order_update()returns trigger language plpgsql as $$begin if tg_op='DELETE'and old.status not in('draft','internal_review')then raise exception 'locked change-order revision is immutable';end if;if tg_op='UPDATE'and old.status not in('draft','internal_review')and (to_jsonb(new)-array['status','signed_pdf_storage_path','integrity_hash'])<>(to_jsonb(old)-array['status','signed_pdf_storage_path','integrity_hash'])then raise exception 'locked change-order revision is immutable';end if;return coalesce(new,old);end$$;drop trigger if exists immutable_change_order_revision on change_order_revisions;create trigger immutable_change_order_revision before update or delete on change_order_revisions for each row execute function prevent_locked_change_order_update();
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('project-documents','project-documents',false,26214400,array['application/pdf','image/jpeg','image/png','image/webp','text/plain','application/vnd.openxmlformats-officedocument.wordprocessingml.document'])on conflict(id)do nothing;
do $$declare t text;begin foreach t in array array['projects','project_status_history','project_operational_details','project_colour_confirmations','project_documents','project_image_associations','change_orders','change_order_revisions','change_order_line_items','change_order_access_tokens','change_order_acceptances','change_order_documents','change_order_events','project_total_snapshots']loop execute format('alter table %I enable row level security',t);execute format('create policy "project service role only" on %I for all using(auth.role()=''service_role'') with check(auth.role()=''service_role'')',t);end loop;end$$;
create policy "project document objects service only" on storage.objects for all using(bucket_id='project-documents' and auth.role()='service_role')with check(bucket_id='project-documents' and auth.role()='service_role');revoke all on function create_project_from_acceptance(uuid,text),next_change_order_number(uuid,text),approve_change_order(uuid,uuid,text,text,text,text,text,text,text,numeric,numeric,numeric,timestamptz,text,text,text)from public,anon,authenticated;grant execute on function create_project_from_acceptance(uuid,text),next_change_order_number(uuid,text),approve_change_order(uuid,uuid,text,text,text,text,text,text,text,numeric,numeric,numeric,timestamptz,text,text,text)to service_role;
alter table project_colour_confirmations add constraint project_colour_approved_change_fk foreign key(approved_change_order_revision_id) references change_order_revisions(id) on delete restrict;

-- ===== 0028_deployment_readiness_and_migration_history.sql | sha256 dd20be3f9586b6a9715de1b4d1a9867537ab96be7f06170e1964b3825c0e4fe6 =====
create table if not exists app_schema_migrations(migration_number text primary key,migration_name text not null,checksum text not null,applied_at timestamptz not null default now(),applied_by text not null,environment text not null,notes text);
create table if not exists application_operational_errors(id uuid primary key default gen_random_uuid(),occurred_at timestamptz not null default now(),environment text not null,severity text not null check(severity in('warning','error','critical')),feature text not null,operation text not null,safe_code text not null,correlation_id text not null,recoverable boolean not null,safe_message text not null,resolved_at timestamptz,resolution_note text,check(length(safe_message)<=500),check(length(correlation_id)<=80));
create table if not exists application_delivery_attempts(id uuid primary key default gen_random_uuid(),record_type text not null check(record_type in('proposal','change_order','test')),record_id uuid,revision_id uuid,attempt_number integer not null default 1,recipient_domain text,provider text not null default 'resend',status text not null check(status in('pending','sent','failed')),provider_message_id text,correlation_id text not null,last_error_safe_code text,sent_at timestamptz,created_at timestamptz not null default now(),unique(record_type,record_id,revision_id,attempt_number));
create table if not exists application_document_generation(id uuid primary key default gen_random_uuid(),record_type text not null check(record_type in('proposal','signed_proposal','change_order','signed_change_order','synthetic')),record_id uuid,revision_id uuid,document_path text,status text not null check(status in('pending','generating','ready','failed')),generation_version text not null,document_hash text,safe_error_code text,correlation_id text not null,attempt_number integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(record_type,record_id,revision_id,attempt_number));
create index if not exists operational_errors_recent_idx on application_operational_errors(occurred_at desc)where resolved_at is null;create index if not exists delivery_attempts_record_idx on application_delivery_attempts(record_type,record_id,created_at desc);create index if not exists document_generation_record_idx on application_document_generation(record_type,record_id,created_at desc);
create or replace function app_readiness_snapshot()returns jsonb language sql security definer stable set search_path=public as $$select jsonb_build_object('tables',(select coalesce(jsonb_agg(tablename order by tablename),'[]')from pg_tables where schemaname='public'),'columns',(select coalesce(jsonb_object_agg(table_name,cols),'{}')from(select table_name,jsonb_agg(column_name order by ordinal_position)cols from information_schema.columns where table_schema='public'group by table_name)x),'functions',(select coalesce(jsonb_agg(proname order by proname),'[]')from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'),'indexes',(select coalesce(jsonb_agg(indexname order by indexname),'[]')from pg_indexes where schemaname='public'),'buckets',(select coalesce(jsonb_agg(jsonb_build_object('id',id,'public',public)order by id),'[]')from storage.buckets),'migrations',(select coalesce(jsonb_agg(jsonb_build_object('migration_number',migration_number,'migration_name',migration_name,'checksum',checksum,'applied_at',applied_at)order by migration_number),'[]')from app_schema_migrations))$$;
create or replace function record_schema_migration_if_objects_exist(p_number text,p_name text,p_checksum text,p_tables text[],p_functions text[],p_applied_by text,p_environment text,p_notes text default null)returns boolean language plpgsql security definer set search_path=public as $$declare x text;begin foreach x in array coalesce(p_tables,'{}')loop if to_regclass('public.'||x)is null then return false;end if;end loop;foreach x in array coalesce(p_functions,'{}')loop if not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public'and p.proname=x)then return false;end if;end loop;insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes)values(p_number,p_name,p_checksum,p_applied_by,p_environment,p_notes)on conflict(migration_number)do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;return true;end$$;
do $$declare t text;begin foreach t in array array['app_schema_migrations','application_operational_errors','application_delivery_attempts','application_document_generation']loop execute format('alter table %I enable row level security',t);execute format('create policy "deployment diagnostics service role only" on %I for all using(auth.role()=''service_role'')with check(auth.role()=''service_role'')',t);end loop;end$$;
revoke all on function app_readiness_snapshot(),record_schema_migration_if_objects_exist(text,text,text,text[],text[],text,text,text)from public,anon,authenticated;grant execute on function app_readiness_snapshot(),record_schema_migration_if_objects_exist(text,text,text,text[],text[],text,text,text)to service_role;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes)values('0028','deployment_readiness_and_migration_history','self-recorded-v1','migration','deployment','Readiness schema installed; earlier migrations are recorded only by verified bootstrap.')on conflict(migration_number)do nothing;
notify pgrst,'reload schema';

-- Record only migrations whose SQL completed successfully in this transaction.
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0015','internal_roofing_estimates','5e35c96aaf014156e4909747f7849a24272fe38856facb2eccaf2b03852d6197','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0016','internal_proposals','622d9e1312fcd7616ee1c7fa0e040aa00a4f94aaac4d1cd2d4a2a2bfa4c78465','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0017','customer_proposal_signing','92126265d820a7cfb54dff9d5ddef1f038ec098e3d372d898a36397613f62747','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0018','roofing_system_configuration','92b986a30b5764b1cb20cec2ae5333ee31c42777524464f279a8bacfe3dd982d','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0019','soft_metals_estimates','8326372a5aa6beb705fe849852fa02cffc111c11e1d2932bc56b0df59e7ebe50','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0020','soft_metal_proposals','4d28ece45f3e9b7de156825f7f6a4432e4d1254192f034c1d24f25559525bda4','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0021','paginated_proposal_documents','8691ba398005b5117341568518a49793395e185b4b7b267479a90b2c815c08b7','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0022','project_image_library','8327e8ab1df9f757355a32ed10e0a5bff1625132a752155c399b9939435382b9','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0023','vinyl_siding_estimates_and_proposals','cbd0d86c7ab50eb6034918e5cd0dc8f75e7aa484ce96d3f8a807bd79e9475f6a','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0024','hardie_siding_estimates_and_proposals','1f324259ac70af5080e8df296c0b8d239f175876a1317404f5ce5b9fa8e55279','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0025','specification_tender_estimates_and_proposals','320013f442ef419b1b13f6fb4447cffa2b1c045825512aa5aa3b1a95dcd67301','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0026','job_workflow_metadata','a718ee581ad2025a7a8ee0841d935624306f4d23bf2e021f8c75a3a5eaa1b316','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0027','projects_and_change_orders','46ccbfaf67026e30466ff89a48a4050e8fb1c31ddad31e0a38aa678c4167351e','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
insert into app_schema_migrations(migration_number,migration_name,checksum,applied_by,environment,notes) values('0028','deployment_readiness_and_migration_history','dd20be3f9586b6a9715de1b4d1a9867537ab96be7f06170e1964b3825c0e4fe6','deployment-sql','deployment','Combined deployment completed') on conflict(migration_number) do update set migration_name=excluded.migration_name,checksum=excluded.checksum,notes=excluded.notes;
notify pgrst,'reload schema';
commit;
-- Verification (read-only)
select app_readiness_snapshot();
select migration_number,migration_name,checksum,applied_at from app_schema_migrations order by migration_number;

-- ============================================================
-- 0029_structured_roofing_estimates.sql
-- ============================================================
-- Structured roofing estimates: labelled structures, repeatable pitch areas, explicit rate applicability and audit traces.
create table if not exists public.estimate_roof_structures (
  id uuid primary key default gen_random_uuid(),
  estimate_id uuid not null references public.estimates(id) on delete cascade,
  label text not null default 'Main Structure',
  normalized_label text generated always as (coalesce(nullif(btrim(label), ''), 'Main Structure')) stored,
  inclusion_status text not null default 'included' check (inclusion_status in ('included','optional','alternative','excluded','by_others','internal_only')),
  display_order integer not null default 0,
  measurements jsonb not null default '{}'::jsonb,
  penetrations jsonb not null default '{}'::jsonb,
  ventilation jsonb not null default '{}'::jsonb,
  internal_notes text,
  version integer not null default 1,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists estimate_roof_structures_estimate_idx on public.estimate_roof_structures(estimate_id, display_order);

create table if not exists public.estimate_roof_pitch_areas (
  id uuid primary key default gen_random_uuid(),
  structure_id uuid not null references public.estimate_roof_structures(id) on delete cascade,
  pitch jsonb not null,
  square_footage numeric not null default 0,
  area_entry_type text not null default 'actual_roof_area' check (area_entry_type in ('actual_roof_area','horizontal_plan_area')),
  waste_override numeric,
  note text,
  include_status text not null default 'included' check (include_status in ('included','excluded')),
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists estimate_roof_pitch_areas_structure_idx on public.estimate_roof_pitch_areas(structure_id, display_order);

create table if not exists public.estimate_roof_structure_options (
  id uuid primary key default gen_random_uuid(),
  structure_id uuid not null references public.estimate_roof_structures(id) on delete cascade,
  tier text not null check (tier in ('good','better','best')),
  option_snapshot jsonb not null default '{}'::jsonb,
  calculation_trace jsonb not null default '{}'::jsonb,
  production_ready boolean not null default false,
  warnings jsonb not null default '[]'::jsonb,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(structure_id, tier)
);

create table if not exists public.estimate_roof_rate_applications (
  id uuid primary key default gen_random_uuid(),
  estimate_id uuid not null references public.estimates(id) on delete cascade,
  structure_id uuid references public.estimate_roof_structures(id) on delete cascade,
  tier text not null check (tier in ('good','better','best')),
  rate_item_id uuid,
  rate_classification text not null,
  quantity_source text not null,
  applicability_reason text not null,
  selected_by_estimator boolean not null default false,
  condition_metadata jsonb not null default '{}'::jsonb,
  applied_quantity numeric,
  extension numeric,
  warnings jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists estimate_roof_rate_applications_estimate_idx on public.estimate_roof_rate_applications(estimate_id, tier);

alter table public.estimate_roof_structures enable row level security;
alter table public.estimate_roof_pitch_areas enable row level security;
alter table public.estimate_roof_structure_options enable row level security;
alter table public.estimate_roof_rate_applications enable row level security;

create policy "Service role manages roof structures" on public.estimate_roof_structures for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role manages roof pitch areas" on public.estimate_roof_pitch_areas for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role manages roof structure options" on public.estimate_roof_structure_options for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role manages roof rate applications" on public.estimate_roof_rate_applications for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

insert into public.app_schema_migrations(migration_number, migration_name, checksum, applied_by, environment, notes)
values ('0029', 'structured_roofing_estimates', 'manual-check-required', 'deployment', current_setting('app.environment', true), 'Adds labelled roof structures, pitch areas, option traces and explicit rate applications.')
on conflict (migration_number) do nothing;
notify pgrst, 'reload schema';
