export type Category = "materials" | "labour" | "general_requirements";
export type Measurements = { pitches: Record<number, number>; totalArea:number; ridgesHips:number; valleys:number; rakes:number; eaves:number; transition:number; goosenecks:number; vents:number; oatey:number; bVents:number; stepFlashing:number; wallFlashing:number; chimneyBackpan:number };
export type Switches = Record<"chimney"|"groundDrop"|"extraIce"|"cutInVents"|"ridgeVent"|"highDefCap"|"travel"|"hotel"|"perDiem",boolean>;
export type Rule = { row:number; category:Category; item:string; source:string; quantity:(m:Measurements,s:Switches)=>number; active:(m:Measurements,s:Switches)=>boolean; coverage:number; multiplier:number; fixtureRaw?:number; fixtureExtension?:number; purchasable?:boolean };
export type Override = Partial<{product:string;coverage:number;multiplier:number;quantity:number;rate:number;included:boolean}>;
export type CalculatedRow = Rule & {sourceQuantity:number;requiredQuantity:number;rawOrderQuantity:number;roundedOrderQuantity:number;effectiveQuantity:number;rate:number;extension:number;included:boolean;override:Override};

export const signalHill: Measurements = {totalArea:3287.000001,pitches:{1:0,2:4,3:0,4:0,5:94,6:0,7:3156,8:0,9:33,10:0,11:0,12:0,13:0,14:0,15:0,16:0,17:0},ridgesHips:320,valleys:153,rakes:47,eaves:259,transition:1,goosenecks:3,vents:3287.000001,oatey:1,bVents:3,stepFlashing:53,wallFlashing:30,chimneyBackpan:1};
export const blankMeasurements:Measurements={totalArea:0,pitches:Object.fromEntries(Array.from({length:17},(_,i)=>[i+1,0])),ridgesHips:0,valleys:0,rakes:0,eaves:0,transition:0,goosenecks:0,vents:0,oatey:0,bVents:0,stepFlashing:0,wallFlashing:0,chimneyBackpan:0};
export const defaultSwitches:Switches={chimney:true,groundDrop:false,extraIce:false,cutInVents:false,ridgeVent:false,highDefCap:false,travel:false,hotel:false,perDiem:false};
const on=(q:(m:Measurements,s:Switches)=>number)=>(m:Measurements,s:Switches)=>q(m,s)>0;
const materialData:[number,string,string,(m:Measurements,s:Switches)=>number,number,number,number,number][]=[
 [12,"GAF Timberline HDZ","Total roof area",m=>m.totalArea,3,1.08,106.4988000324,4287],[13,"GAF Weatherblocker Starter Strip","Rakes + eaves",m=>m.rakes+m.eaves,100,1.1,3.366,176],[14,"GAF Seal-A-Ridge","Ridges / hips",m=>m.ridgesHips,25,1.1,14.08,735],[15,"Specialty Starter Eave","Eaves",m=>m.eaves,1,1.1,284.9,0],[16,"Specialty Starter Rake","Rakes",m=>m.rakes,1,1.1,51.7,0],[17,"Specialty Starter Valley","Valleys × 2",m=>m.valleys*2,1,1.1,336.6,0],[18,'Resisto LB1236 36"',"Valleys + eaves + transition",m=>m.valleys+m.eaves+m.transition,65,1.02,6.480923076923077,428],[19,"TriBuilt Synthetic","Area less ice & water",m=>m.totalArea-(m.valleys+m.eaves+m.transition),1000,1.1,3.1614000011,229],[20,'Drip Edge - 26ga - 1.5"',"Eaves",m=>m.eaves,10,1.15,29.785,262],[21,'Rake Edge - 26ga - 1"',"Rakes",m=>m.rakes,10,1.15,5.405,40],[22,'W Valley Flashing - 26ga',"Valleys",m=>m.valleys,10,1.15,17.595,682],[23,"Transition Flashing","Transitions",m=>m.transition,10,1.15,.115,3],[24,"Step Flashing - 30ga","Step flashing",m=>m.stepFlashing,.5,1.1,116.6,78],[25,"Wall Flashing - 30ga","Wall flashing",m=>m.wallFlashing,10,1,3,38],[26,"Primex Gooseneck","Goosenecks",m=>m.goosenecks,1,1,3,57],[27,"WeatherPRO50","Roof area",m=>m.vents,200,1,16.435000005,205],[28,"Optional vent product","Cut-in vents",(_m,s)=>s.cutInVents?1:0,1,1,0,0],[29,'4" Oatey',"Oatey penetrations",m=>m.oatey,1,1,1,8],[30,"B Vent - Rain Cap","B vents",m=>m.bVents,1,1,3,66],[31,"B Vent - Flange","B vents",m=>m.bVents,1,1,3,39],[32,"B Vent - Collar Flange","B vents",m=>m.bVents,1,1,3,39],[33,"Omniseal 410 Base","Pitch 1–3 area",m=>(m.pitches[1]||0)+(m.pitches[2]||0)+(m.pitches[3]||0),2.6,1.3,2,282],[34,"Omniseal 420 Base","Low slope assembly",m=>(m.pitches[1]||0)+(m.pitches[2]||0),2.6,1.3,2,326],[35,"Omniseal 430 Cap Sheet","Low slope assembly",m=>(m.pitches[1]||0)+(m.pitches[2]||0),5.2,1.3,1,182],[36,"Caulking","Valley flashing units",m=>m.valleys,10,1.15,17.595,174],[37,"Screws","Roof area",m=>m.totalArea,5922.949369913263,1,.55496000008,43],[38,"Chimney Backpan","Chimney backpans",m=>m.chimneyBackpan,1,1,1,57],[39,"Sheathing / Hot Roof / Skylights","Manual",()=>0,1,1,0,0]
];
export const rules:Rule[]=[...materialData.map(([row,item,source,quantity,coverage,multiplier,fixtureRaw,fixtureExtension])=>({row,item,source,quantity,coverage,multiplier,fixtureRaw,fixtureExtension,purchasable:true,category:"materials" as const,active:on(quantity)})),
 ...Array.from({length:17},(_,i)=>{const pitch=i+1,row=42+pitch,q=(m:Measurements)=>m.pitches[pitch]||0;return {row,category:"labour" as const,item:pitch===17?"XX:12":`${pitch}/12 pitch labour`,source:`Pitch ${pitch} area`,quantity:q,active:on(q),coverage:1,multiplier:1};}),
 ...[[60,"Chimney Work","chimney"],[61,"Ground Drop","groundDrop"],[62,"Extra Ice & Water","extraIce"],[63,"Vents Install (Cut in)","cutInVents"],[64,"Wall Flashing","wallFlashing"],[65,"Step Flashing","stepFlashing"],[66,"Ridge Vent","ridgeVent"],[67,"High Definition Cap","highDefCap"],[68,"Oatey Renovation","oatey"],[69,"Sheathing / Hot Roof / Skylights","manual"]].map(([row,item,key])=>{const q=(m:Measurements,s:Switches)=>key==="wallFlashing"?m.wallFlashing:key==="stepFlashing"?m.stepFlashing:key==="oatey"?(s.cutInVents?m.oatey:0):key==="manual"?0:(s[key as keyof Switches]?1:0);return {row:row as number,item:item as string,source:`Explicit ${key} rule`,quantity:q,active:on(q),coverage:1,multiplier:1,category:"labour" as const}}),
 ...[[72,"Mobilization / Demobilization",1],[73,"Safety - Traffic control",0],[74,"Safety - Scaffolding OHP",0],[75,"Safety - Scaffolding",1],[76,"Site Control (ground)",1],[77,"Site Control (fence)",1],[78,"Site Control (booms)",0],[79,"Disposal",32.87],[80,"Delivery surcharge",1],[81,"Delivery hoisting",1],[82,"Project Manager",1],[83,"Park access",0],[84,"Permits",0],[85,"Tools & Equipment",0]].map(([row,item,value])=>{const q=()=>value as number;return {row:row as number,item:item as string,source:"Explicit workbook driver",quantity:q,active:on(q),coverage:1,multiplier:1,category:"general_requirements" as const}}),
 ...[[86,"Travel time","travel"],[87,"Hotel","hotel"],[88,"Per diem","perDiem"]].map(([row,item,key])=>{const q=(_m:Measurements,s:Switches)=>s[key as keyof Switches]?1:0;return {row:row as number,item:item as string,source:`${item} toggle`,quantity:q,active:on(q),coverage:1,multiplier:1,category:"general_requirements" as const}})
];

export function calculate(m:Measurements,s:Switches,overrides:Record<number,Override>={},rounding:"ceiling"|"workbook"="ceiling"):CalculatedRow[]{return rules.map(rule=>{const o=overrides[rule.row]||{},sourceQuantity=rule.quantity(m,s),requiredQuantity=sourceQuantity,coverage=o.coverage??rule.coverage,multiplier=o.multiplier??rule.multiplier,rawOrderQuantity=requiredQuantity<=0?0:(requiredQuantity/coverage)*multiplier,roundedOrderQuantity=rounding==="ceiling"&&rule.purchasable?Math.ceil(rawOrderQuantity):rawOrderQuantity,effectiveQuantity=o.quantity??roundedOrderQuantity,fixtureRate=rule.fixtureRaw&&rule.fixtureExtension!==undefined?rule.fixtureExtension/rule.fixtureRaw:0,rate=o.rate??fixtureRate,included=o.included??rule.active(m,s);return {...rule,item:o.product??rule.item,sourceQuantity,requiredQuantity,coverage,multiplier,rawOrderQuantity,roundedOrderQuantity,effectiveQuantity,rate,extension:included?effectiveQuantity*rate:0,included,override:o};});}
export function workbookFixtureTotal(kind:"asphalt"|"euroshield"){return kind==="asphalt"?28778.02304:53513.47300000001;}
export const mappedRows=[...Array.from({length:28},(_,i)=>i+12),...Array.from({length:29},(_,i)=>i+41),...Array.from({length:19},(_,i)=>i+72),92,93,94];
export const intentionallyExcluded=[{row:40,reason:"Section heading; no calculation."},{row:41,reason:"Labour section spacer/header."},{row:42,reason:"Labour column heading; no calculation."},{row:70,reason:"Blank separator."},{row:71,reason:"General Requirements heading."},{row:89,reason:"Blank separator."},{row:91,reason:"Blank separator."}];

export const implementedRows=[...rules.map(r=>r.row),90,92,93,94];
