import {calculate,defaultSwitches,type Measurements,type Override,type Switches} from "./engine";
import {ASPHALT_PRESETS,MATERIAL_PRODUCTS,type CatalogProduct} from "./product-catalog";

export type StructureStatus="included"|"optional"|"excluded";
export type PitchRow={id:string;pitch:number;areaSqFt:number};
export type RoofStructure={id:string;name:string;status:StructureStatus;selected:boolean;pitches:PitchRow[];measurements:Omit<Measurements,"pitches"|"totalArea"|"vents">&{layers:number;storeys:number}};
export type Product=CatalogProduct;
export type OptionKey="good"|"better"|"best"|"custom";
export type OptionSettings={key:OptionKey;label:string;products:Record<number,Product>;overrides:Record<number,Override>;contingencyPercent:number;markupPercent:number;manualFinalPrice:number|null;selectedStructureIds:string[]};
export type WorksheetDefaults={labourRates:Record<number,number>;otherLabourRates:Record<number,number>;contingencyPercent:number;markupPercent:number};

export const emptyStructure=(name="Main House"):RoofStructure=>({id:crypto.randomUUID(),name,status:"included",selected:true,pitches:[{id:crypto.randomUUID(),pitch:4,areaSqFt:0}],measurements:{ridgesHips:0,valleys:0,rakes:0,eaves:0,transition:0,goosenecks:0,oatey:0,bVents:0,stepFlashing:0,wallFlashing:0,chimneyBackpan:0,layers:1,storeys:1}});
export const defaultRates:WorksheetDefaults={labourRates:{1:525,2:175,3:175,4:175,5:175,6:175,7:205,8:195,9:315,10:215,11:225,12:235,13:245,14:255,15:265,16:275,17:275},otherLabourRates:{60:150,61:0,62:0,63:0,64:2.5,65:3,66:0,67:0,68:0,69:0},contingencyPercent:4,markupPercent:30};
export const compatibleProducts=(row:number)=>MATERIAL_PRODUCTS[row]??[];
const clonePreset=(key:"good"|"better"|"best")=>structuredClone(ASPHALT_PRESETS[key]) as unknown as Record<number,Product>;
export function createOptions():Record<OptionKey,OptionSettings>{const make=(key:OptionKey,label:string,products:Record<number,Product>):OptionSettings=>({key,label,products,overrides:{},contingencyPercent:4,markupPercent:30,manualFinalPrice:null,selectedStructureIds:[]});return{good:make("good","Good",clonePreset("good")),better:make("better","Better",clonePreset("better")),best:make("best","Best",clonePreset("best")),custom:make("custom","Custom",clonePreset("good"))}}
export const requiresSpecialtyStarters=(fieldProduct:string)=>/euroshield.*(?:beaumont|vermont)/i.test(fieldProduct);
const euroProduct=(row:number,pattern:RegExp)=>compatibleProducts(row).find(product=>pattern.test(product.name));
export function selectFieldProduct(option:OptionSettings,product:Product):OptionSettings{const products:Record<number,Product>={...option.products,12:structuredClone(product)};const euro=/euroshield/i.test(product.name),specialty=requiresSpecialtyStarters(product.name);if(euro){const regular=/ranch/i.test(product.name)?euroProduct(13,/ranch.*starter/i):/rundle/i.test(product.name)?euroProduct(13,/rundle.*starter/i):euroProduct(13,/euroshield starter/i);if(regular)products[13]=structuredClone(regular);const cap=/ranch/i.test(product.name)?euroProduct(14,/ridge ranch/i):/rundle/i.test(product.name)?euroProduct(14,/ridge rundle/i):euroProduct(14,/ridge beaumont/i);if(cap)products[14]=structuredClone(cap);if(specialty){const eave=euroProduct(15,/eave/i),rake=euroProduct(16,/rake/i),valley=euroProduct(17,/valley/i);if(eave)products[15]=structuredClone(eave);if(rake)products[16]=structuredClone(rake);if(valley)products[17]=structuredClone(valley)}}return{...option,products}}
export function aggregateStructures(structures:RoofStructure[],selectedIds?:string[]):Measurements{const allowed=new Set(selectedIds?.length?selectedIds:structures.filter(s=>s.status==="included"&&s.selected).map(s=>s.id));const selected=structures.filter(s=>allowed.has(s.id)&&s.status!=="excluded");const pitches=Object.fromEntries(Array.from({length:17},(_,i)=>[i+1,0]));const result:Measurements={totalArea:0,pitches,ridgesHips:0,valleys:0,rakes:0,eaves:0,transition:0,goosenecks:0,vents:0,oatey:0,bVents:0,stepFlashing:0,wallFlashing:0,chimneyBackpan:0};for(const s of selected){for(const p of s.pitches){result.pitches[p.pitch]=(result.pitches[p.pitch]??0)+p.areaSqFt;result.totalArea+=p.areaSqFt}for(const k of ["ridgesHips","valleys","rakes","eaves","transition","goosenecks","oatey","bVents","stepFlashing","wallFlashing","chimneyBackpan"] as const)result[k]+=s.measurements[k]}result.vents=result.totalArea;return result}
export const cents=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;
export function workbookSquares(rows:{row:number;effectiveQuantity:number}[],products:Record<number,Product>){const qty=(row:number)=>rows.find(r=>r.row===row)?.effectiveQuantity??0;return qty(12)/(products[12]?.bundlesPerSquare||1)+qty(13)/3+qty(14)/3}
export function calculateOption(structures:RoofStructure[],settings:OptionSettings,defaults:WorksheetDefaults,switches:Switches=defaultSwitches,rounding:"ceiling"|"workbook"="ceiling"){const measurements=aggregateStructures(structures,settings.selectedStructureIds);const overrides={...settings.overrides},specialty=requiresSpecialtyStarters(settings.products[12]?.name??"");for(const row of Object.keys(settings.products).map(Number)){const p=settings.products[row],existing=overrides[row];overrides[row]={...existing,product:p.name,coverage:row===12?100/(p.bundlesPerSquare||1):p.coverage,rate:existing?.rate??p.price,...([15,16,17].includes(row)?{included:existing?.included??specialty}: {})}}
 const rows=calculate(measurements,switches,overrides,rounding).map(r=>({...r,priceUnit:r.category==="labour"?"sq":r.row===79?"sq":settings.products[r.row]?.priceUnit??(r.purchasable?"each":"unit"),coverageUnit:settings.products[r.row]?.coverageUnit??"per unit"}));
 const squareRows=rows.map(r=>r.row>=43&&r.row<=59?{...r,rawOrderQuantity:measurements.totalArea?measurements.pitches[r.row-42]/measurements.totalArea*workbookSquares(rows,settings.products):0,roundedOrderQuantity:measurements.totalArea?measurements.pitches[r.row-42]/measurements.totalArea*workbookSquares(rows,settings.products):0,effectiveQuantity:measurements.totalArea?measurements.pitches[r.row-42]/measurements.totalArea*workbookSquares(rows,settings.products):0,rate:defaults.labourRates[r.row-42]??0,extension:cents((measurements.totalArea?measurements.pitches[r.row-42]/measurements.totalArea*workbookSquares(rows,settings.products):0)*(defaults.labourRates[r.row-42]??0))}:r.row===79?{...r,sourceQuantity:measurements.totalArea,requiredQuantity:measurements.totalArea,rawOrderQuantity:measurements.totalArea/100,roundedOrderQuantity:measurements.totalArea/100,effectiveQuantity:measurements.totalArea/100,rate:35,priceUnit:"sq",extension:cents(measurements.totalArea/100*35)}:{...r,extension:cents(r.extension)});
 const lineCost=cents(squareRows.reduce((n,r)=>n+r.extension,0)),contingency=cents(lineCost*settings.contingencyPercent/100),subtotalCost=cents(lineCost+contingency),markup=cents(subtotalCost*settings.markupPercent/100),suggested=cents(subtotalCost+markup),finalPrice=settings.manualFinalPrice??suggested,gst=cents(finalPrice*.05),customerTotal=cents(finalPrice+gst);return{measurements,rows:squareRows,workbookSquares:workbookSquares(squareRows,settings.products),lineCost,contingency,subtotalCost,markup,suggested,finalPrice,gst,customerTotal}}
