import {calculate,defaultSwitches,type Measurements,type Override,type Switches} from "./engine";
import {ASPHALT_PRESETS,MATERIAL_PRODUCTS,type CatalogProduct} from "./product-catalog";

export type StructureStatus="included"|"optional"|"excluded";
export type PitchRow={id:string;pitch:number;areaSqFt:number};
export type RoofStructure={id:string;name:string;status:StructureStatus;selected:boolean;pitches:PitchRow[];measurements:Omit<Measurements,"pitches"|"totalArea"|"vents">&{layers:number;storeys:number}};
export type Product=CatalogProduct;
export type OptionKey="good"|"better"|"best"|"custom";
export type OptionSettings={key:OptionKey;label:string;products:Record<number,Product>;overrides:Record<number,Override>;contingencyPercent:number;markupPercent:number;manualFinalPrice:number|null;selectedStructureIds:string[]};
export type WorksheetDefaults={labourRates:Record<number,number>;otherLabourRates:Record<number,number>;contingencyPercent:number;markupPercent:number};

export const emptyStructure=(name="Main House"):RoofStructure=>({id:crypto.randomUUID(),name,status:"included",selected:true,pitches:[{id:crypto.randomUUID(),pitch:4,areaSqFt:0}],measurements:{ridgesHips:0,valleys:0,rakes:0,eaves:0,transition:0,goosenecks:0,oatey:0,bVents:0,stepFlashing:0,wallFlashing:0,chimneyBackpan:0,layers:1,storeys:1}});
export const defaultRates:WorksheetDefaults={labourRates:{1:390,2:130,3:130,4:130,5:130,6:130,7:140,8:150,9:160,10:170,11:180,12:190,13:200,14:210,15:220,16:230,17:230},otherLabourRates:{60:150,61:10,62:25,63:10,64:2.5,65:3,66:10,67:5,68:20,69:0,72:50,73:0,74:500,75:0,76:35,77:0,78:0,79:25,80:500,81:2.25,82:125,83:20,84:20,85:20,86:40,87:200,88:70},contingencyPercent:4,markupPercent:30};
export const compatibleProducts=(row:number)=>MATERIAL_PRODUCTS[row]??[];
const clonePreset=(key:"good"|"better"|"best")=>structuredClone(ASPHALT_PRESETS[key]) as unknown as Record<number,Product>;
export function createOptions():Record<OptionKey,OptionSettings>{const make=(key:OptionKey,label:string,products:Record<number,Product>):OptionSettings=>({key,label,products,overrides:{},contingencyPercent:4,markupPercent:30,manualFinalPrice:null,selectedStructureIds:[]});return{good:make("good","Good",clonePreset("good")),better:make("better","Better",clonePreset("better")),best:make("best","Best",clonePreset("best")),custom:make("custom","Custom",clonePreset("good"))}}
export const requiresSpecialtyStarters=(fieldProduct:string)=>/euroshield.*(?:beaumont|vermont)/i.test(fieldProduct);
export function selectFieldProduct(option:OptionSettings,product:Product,catalog:Record<number,Product[]>=MATERIAL_PRODUCTS):OptionSettings{const find=(row:number,pattern:RegExp)=>catalog[row]?.find(candidate=>candidate.active&&pattern.test(candidate.name));const products:Record<number,Product>={...option.products,12:structuredClone(product)};const euro=/euroshield/i.test(product.name),specialty=requiresSpecialtyStarters(product.name);if(euro){const regular=/ranch/i.test(product.name)?find(13,/ranch.*starter/i):/rundle/i.test(product.name)?find(13,/rundle.*starter/i):find(13,/euroshield starter/i);if(regular)products[13]=structuredClone(regular);const cap=/ranch/i.test(product.name)?find(14,/ridge ranch/i):/rundle/i.test(product.name)?find(14,/ridge rundle/i):find(14,/ridge beaumont/i);if(cap)products[14]=structuredClone(cap);if(specialty){const eave=find(15,/eave/i),rake=find(16,/rake/i),valley=find(17,/valley/i);if(eave)products[15]=structuredClone(eave);if(rake)products[16]=structuredClone(rake);if(valley)products[17]=structuredClone(valley)}}return{...option,products}}
export function aggregateStructures(structures:RoofStructure[],selectedIds?:string[]):Measurements{const allowed=new Set(selectedIds?.length?selectedIds:structures.filter(s=>s.status==="included"&&s.selected).map(s=>s.id));const selected=structures.filter(s=>allowed.has(s.id)&&s.status!=="excluded");const pitches=Object.fromEntries(Array.from({length:17},(_,i)=>[i+1,0]));const result:Measurements={totalArea:0,pitches,ridgesHips:0,valleys:0,rakes:0,eaves:0,transition:0,goosenecks:0,vents:0,oatey:0,bVents:0,stepFlashing:0,wallFlashing:0,chimneyBackpan:0};for(const s of selected){for(const p of s.pitches){result.pitches[p.pitch]=(result.pitches[p.pitch]??0)+p.areaSqFt;result.totalArea+=p.areaSqFt}for(const k of ["ridgesHips","valleys","rakes","eaves","transition","goosenecks","oatey","bVents","stepFlashing","wallFlashing","chimneyBackpan"] as const)result[k]+=s.measurements[k]}result.vents=result.totalArea;return result}
export const cents=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;
export function workbookSquares(rows:{row:number;effectiveQuantity:number}[],products:Record<number,Product>){const qty=(row:number)=>rows.find(r=>r.row===row)?.effectiveQuantity??0;return qty(12)/(products[12]?.bundlesPerSquare||1)+qty(13)/3+qty(14)/3}
const RATE_UNITS:Record<number,string>={60:"each",61:"sq",62:"roll",63:"each",64:"LF",65:"each",66:"LF",67:"bundle",68:"each",69:"each",72:"hr",73:"LS",74:"month",75:"month",76:"hr",77:"LS",78:"LS",79:"sq",80:"trip",81:"unit",82:"hr",83:"unit",84:"unit",85:"unit",86:"hr",87:"day",88:"day"};
export function calculateOption(structures:RoofStructure[],settings:OptionSettings,defaults:WorksheetDefaults,switches:Switches=defaultSwitches,rounding:"ceiling"|"workbook"="ceiling"){const measurements=aggregateStructures(structures,settings.selectedStructureIds);const overrides={...settings.overrides},specialty=requiresSpecialtyStarters(settings.products[12]?.name??"");for(const row of Object.keys(settings.products).map(Number)){const p=settings.products[row],existing=overrides[row],coverage=p.coverage??0,rate=p.price??0;overrides[row]={...existing,product:p.name,coverage:row===12?100/(p.bundlesPerSquare||1):coverage,rate:existing?.rate??rate,...([15,16,17].includes(row)?{included:existing?.included??specialty}: {})}}
 const rows=calculate(measurements,switches,overrides,rounding).map(r=>({...r,priceUnit:r.row>=43&&r.row<=59?"sq":RATE_UNITS[r.row]??settings.products[r.row]?.priceUnit??(r.purchasable?"each":"unit"),coverageUnit:settings.products[r.row]?.coverageUnit??"per unit"}));const squares=workbookSquares(rows,settings.products);
 const pitchRows=rows.map(r=>{if(r.row<43||r.row>59)return r;const calculated=measurements.totalArea?measurements.pitches[r.row-42]/measurements.totalArea*squares:0,quantity=settings.overrides[r.row]?.quantity??calculated,rate=settings.overrides[r.row]?.rate??defaults.labourRates[r.row-42]??0;return{...r,rawOrderQuantity:calculated,roundedOrderQuantity:calculated,effectiveQuantity:quantity,rate,extension:r.included?cents(quantity*rate):0}});const byRow=new Map(pitchRows.map(row=>[row.row,row]));const days=squares/20,formulaQuantity:Record<number,number>={61:Array.from({length:16},(_,i)=>byRow.get(44+i)?.effectiveQuantity??0).reduce((a,b)=>a+b,0),62:byRow.get(18)?.effectiveQuantity??0,63:byRow.get(27)?.effectiveQuantity??0,64:measurements.wallFlashing,65:(byRow.get(24)?.requiredQuantity??0)/(byRow.get(24)?.coverage||1),66:measurements.ridgesHips,67:byRow.get(14)?.effectiveQuantity??0,68:measurements.oatey,72:days*4,73:1,74:0,75:1,76:days,77:1,78:0,79:measurements.totalArea/100,80:Math.ceil(((byRow.get(12)?.effectiveQuantity??0)+(byRow.get(13)?.effectiveQuantity??0)+(byRow.get(14)?.effectiveQuantity??0)+(byRow.get(18)?.effectiveQuantity??0)+(byRow.get(19)?.effectiveQuantity??0))/300),81:(byRow.get(12)?.effectiveQuantity??0)+(byRow.get(13)?.effectiveQuantity??0)+(byRow.get(14)?.effectiveQuantity??0)+(byRow.get(18)?.effectiveQuantity??0)+(byRow.get(19)?.effectiveQuantity??0),82:days*3,83:0,84:0,85:0,86:switches.travel?1:0,87:switches.hotel?1:0,88:switches.perDiem?1:0};
 const squareRows=pitchRows.map(r=>{if(!(r.row in defaults.otherLabourRates))return{...r,extension:cents(r.extension)};const calculated=formulaQuantity[r.row]??r.effectiveQuantity,quantity=settings.overrides[r.row]?.quantity??calculated,rate=settings.overrides[r.row]?.rate??defaults.otherLabourRates[r.row]??r.rate;return{...r,sourceQuantity:calculated,requiredQuantity:calculated,rawOrderQuantity:calculated,roundedOrderQuantity:calculated,effectiveQuantity:quantity,rate,extension:r.included?cents(quantity*rate):0}});
 const lineCost=cents(squareRows.reduce((n,r)=>n+r.extension,0)),contingency=cents(lineCost*settings.contingencyPercent/100),subtotalCost=cents(lineCost+contingency),markup=cents(subtotalCost*settings.markupPercent/100),suggested=cents(subtotalCost+markup),finalPrice=settings.manualFinalPrice??suggested,gst=cents(finalPrice*.05),customerTotal=cents(finalPrice+gst);return{measurements,rows:squareRows,workbookSquares:workbookSquares(squareRows,settings.products),lineCost,contingency,subtotalCost,markup,suggested,finalPrice,gst,customerTotal}}
