import {calculate,defaultSwitches,type Measurements,type Override,type Switches} from "./engine";

export type StructureStatus="included"|"optional"|"excluded";
export type PitchRow={id:string;pitch:number;areaSqFt:number};
export type RoofStructure={id:string;name:string;status:StructureStatus;selected:boolean;pitches:PitchRow[];measurements:Omit<Measurements,"pitches"|"totalArea"|"vents">&{layers:number;storeys:number}};
export type Product={name:string;coverage:number;coverageUnit:string;price:number;priceUnit:string;bundlesPerSquare?:number};
export type OptionKey="good"|"better"|"best"|"custom";
export type OptionSettings={key:OptionKey;label:string;products:Record<number,Product>;overrides:Record<number,Override>;contingencyPercent:number;markupPercent:number;manualFinalPrice:number|null;selectedStructureIds:string[]};
export type WorksheetDefaults={labourRates:Record<number,number>;otherLabourRates:Record<number,number>;contingencyPercent:number;markupPercent:number};

export const emptyStructure=(name="Main House"):RoofStructure=>({id:crypto.randomUUID(),name,status:"included",selected:true,pitches:[{id:crypto.randomUUID(),pitch:4,areaSqFt:0}],measurements:{ridgesHips:0,valleys:0,rakes:0,eaves:0,transition:0,goosenecks:0,oatey:0,bVents:0,stepFlashing:0,wallFlashing:0,chimneyBackpan:0,layers:1,storeys:1}});
export const defaultRates:WorksheetDefaults={labourRates:{1:525,2:175,3:175,4:175,5:175,6:175,7:205,8:195,9:315,10:215,11:225,12:235,13:245,14:255,15:265,16:275,17:275},otherLabourRates:{60:150,61:0,62:0,63:0,64:2.5,65:3,66:0,67:0,68:0,69:0},contingencyPercent:4,markupPercent:30};
const shingleProducts:Product[]=[{name:"GAF Timberline HDZ",coverage:3,coverageUnit:"bundles / sq",price:40.25,priceUnit:"bundle",bundlesPerSquare:3},{name:"GAF Timberline UHDZ",coverage:5,coverageUnit:"bundles / sq",price:54.05,priceUnit:"bundle",bundlesPerSquare:5},{name:"Malarkey Vista",coverage:3,coverageUnit:"bundles / sq",price:53.5,priceUnit:"bundle",bundlesPerSquare:3},{name:"Malarkey Legacy",coverage:4,coverageUnit:"bundles / sq",price:54.05,priceUnit:"bundle",bundlesPerSquare:4}];
const starterProducts:Product[]=[{name:"GAF Weatherblocker Starter Strip",coverage:100,coverageUnit:"linear ft / bundle",price:52.25,priceUnit:"bundle"},{name:"Malarkey Smart Start",coverage:114,coverageUnit:"linear ft / bundle",price:73.35,priceUnit:"bundle"}];
const capProducts:Product[]=[{name:"GAF Seal-A-Ridge",coverage:25,coverageUnit:"linear ft / bundle",price:52.2,priceUnit:"bundle"},{name:'Malarkey EZ Ridge XT 10"',coverage:20,coverageUnit:"linear ft / bundle",price:98,priceUnit:"bundle"}];
export const compatibleProducts=(row:number)=>row===12?shingleProducts:row===13?starterProducts:row===14?capProducts:[];
const pick=(items:Product[],name:string)=>structuredClone(items.find(x=>x.name===name)!);
export function createOptions():Record<OptionKey,OptionSettings>{const make=(key:OptionKey,label:string,shingle:string,starter:string,cap:string):OptionSettings=>({key,label,products:{12:pick(shingleProducts,shingle),13:pick(starterProducts,starter),14:pick(capProducts,cap)},overrides:{},contingencyPercent:4,markupPercent:30,manualFinalPrice:null,selectedStructureIds:[]});return{good:make("good","Good","GAF Timberline HDZ","GAF Weatherblocker Starter Strip","GAF Seal-A-Ridge"),better:make("better","Better","Malarkey Vista","Malarkey Smart Start",'Malarkey EZ Ridge XT 10"'),best:make("best","Best","Malarkey Legacy","Malarkey Smart Start",'Malarkey EZ Ridge XT 10"'),custom:make("custom","Custom","GAF Timberline HDZ","GAF Weatherblocker Starter Strip","GAF Seal-A-Ridge")}}
export function aggregateStructures(structures:RoofStructure[],selectedIds?:string[]):Measurements{const allowed=new Set(selectedIds?.length?selectedIds:structures.filter(s=>s.status==="included"&&s.selected).map(s=>s.id));const selected=structures.filter(s=>allowed.has(s.id)&&s.status!=="excluded");const pitches=Object.fromEntries(Array.from({length:17},(_,i)=>[i+1,0]));const result:Measurements={totalArea:0,pitches,ridgesHips:0,valleys:0,rakes:0,eaves:0,transition:0,goosenecks:0,vents:0,oatey:0,bVents:0,stepFlashing:0,wallFlashing:0,chimneyBackpan:0};for(const s of selected){for(const p of s.pitches){result.pitches[p.pitch]=(result.pitches[p.pitch]??0)+p.areaSqFt;result.totalArea+=p.areaSqFt}for(const k of ["ridgesHips","valleys","rakes","eaves","transition","goosenecks","oatey","bVents","stepFlashing","wallFlashing","chimneyBackpan"] as const)result[k]+=s.measurements[k]}result.vents=result.totalArea;return result}
export const cents=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;
export function workbookSquares(rows:{row:number;effectiveQuantity:number}[],products:Record<number,Product>){const qty=(row:number)=>rows.find(r=>r.row===row)?.effectiveQuantity??0;return qty(12)/(products[12]?.bundlesPerSquare||1)+qty(13)/3+qty(14)/3}
export function calculateOption(structures:RoofStructure[],settings:OptionSettings,defaults:WorksheetDefaults,switches:Switches=defaultSwitches,rounding:"ceiling"|"workbook"="ceiling"){const measurements=aggregateStructures(structures,settings.selectedStructureIds);const overrides={...settings.overrides};for(const row of [12,13,14]){const p=settings.products[row];overrides[row]={...overrides[row],product:p.name,coverage:row===12?100/(p.bundlesPerSquare||1):p.coverage,rate:p.price}}
 const rows=calculate(measurements,switches,overrides,rounding).map(r=>({...r,priceUnit:r.category==="labour"?"sq":r.row===79?"sq":settings.products[r.row]?.priceUnit??(r.purchasable?"each":"unit"),coverageUnit:settings.products[r.row]?.coverageUnit??"per unit"}));
 const squareRows=rows.map(r=>r.row>=43&&r.row<=59?{...r,rawOrderQuantity:measurements.totalArea?measurements.pitches[r.row-42]/measurements.totalArea*workbookSquares(rows,settings.products):0,roundedOrderQuantity:measurements.totalArea?measurements.pitches[r.row-42]/measurements.totalArea*workbookSquares(rows,settings.products):0,effectiveQuantity:measurements.totalArea?measurements.pitches[r.row-42]/measurements.totalArea*workbookSquares(rows,settings.products):0,rate:defaults.labourRates[r.row-42]??0,extension:cents((measurements.totalArea?measurements.pitches[r.row-42]/measurements.totalArea*workbookSquares(rows,settings.products):0)*(defaults.labourRates[r.row-42]??0))}:r.row===79?{...r,sourceQuantity:measurements.totalArea,requiredQuantity:measurements.totalArea,rawOrderQuantity:measurements.totalArea/100,roundedOrderQuantity:measurements.totalArea/100,effectiveQuantity:measurements.totalArea/100,rate:35,priceUnit:"sq",extension:cents(measurements.totalArea/100*35)}:{...r,extension:cents(r.extension)});
 const lineCost=cents(squareRows.reduce((n,r)=>n+r.extension,0)),contingency=cents(lineCost*settings.contingencyPercent/100),subtotalCost=cents(lineCost+contingency),markup=cents(subtotalCost*settings.markupPercent/100),suggested=cents(subtotalCost+markup),finalPrice=settings.manualFinalPrice??suggested,gst=cents(finalPrice*.05),customerTotal=cents(finalPrice+gst);return{measurements,rows:squareRows,workbookSquares:workbookSquares(squareRows,settings.products),lineCost,contingency,subtotalCost,markup,suggested,finalPrice,gst,customerTotal}}
